import { Fragment } from 'react';
import Svg, { ClipPath, Defs, G } from 'react-native-svg';

import { ROOM_NODES, ROOM_VIEWBOX } from '@/components/ascnd/koa/room-scene';
import type { Node, Op } from '@/components/ascnd/koa/koa-scene';
import { attrs, SHAPES } from '@/components/ascnd/koa/svg-shapes';

/**
 * The Mascot Room backdrop, drawn from the design export's room page.
 *
 * A neon ASCND sign, a mirror, a heavy bag, a city window, a dumbbell rack,
 * a treadmill, a bench and a plant, around a lit patch of floor the
 * character stands on. Generated by
 * `import-koa.py --room`, so a redesign is a re-run, not a redraw.
 *
 * Static by design: no flags, no keyframes, nothing per frame. It draws
 * once and then costs nothing, which is what lets it sit under a character
 * that does animate.
 */

/** the design's own aspect — the scene is 360 wide by 340 tall */
const [, , VB_W, VB_H] = ROOM_VIEWBOX.split(/\s+/).map(Number);
export const ROOM_ASPECT = VB_H / VB_W;

/**
 * Where the character's feet belong, in viewBox units: the centre of the lit
 * floor ellipse the scene is composed around.
 */
export const ROOM_FLOOR = { x: 180 / VB_W, y: 254 / VB_H };

function matrixOf(ops: Op[]): string {
  let m = [1, 0, 0, 1, 0, 0];
  for (const op of ops) {
    let n: number[];
    if (op[0] === 'r') {
      const r = (op[1] * Math.PI) / 180;
      const c = Math.cos(r);
      const s = Math.sin(r);
      n = [c, s, -s, c, 0, 0];
      if (op.length === 4) {
        const [, , cx, cy] = op as [string, number, number, number];
        n = [c, s, -s, c, cx - (c * cx - s * cy), cy - (s * cx + c * cy)];
      }
    } else if (op[0] === 't') n = [1, 0, 0, 1, op[1], op[2]];
    else n = [op[1], 0, 0, op[2], 0, 0];
    m = [
      m[0] * n[0] + m[2] * n[1],
      m[1] * n[0] + m[3] * n[1],
      m[0] * n[2] + m[2] * n[3],
      m[1] * n[2] + m[3] * n[3],
      m[0] * n[4] + m[2] * n[5] + m[4],
      m[1] * n[4] + m[3] * n[5] + m[5],
    ];
  }
  return `matrix(${m.join(' ')})`;
}

function RoomNode({ n }: { n: Node }) {
  const kids = n.kids ? n.kids.map((k, i) => <RoomNode key={i} n={k} />) : null;
  if (n.t === 'defs') return <Defs>{kids}</Defs>;
  if (n.t === 'clipPath') return <ClipPath id={String(n.id ?? '')}>{kids}</ClipPath>;

  const own = attrs(n.a);
  if (n.id) own.id = n.id;
  const Shape = SHAPES[n.t];
  if (Shape) {
    // `<text>` carries its label as character data, everything else is closed
    return n.x ? <Shape {...own}>{n.x}</Shape> : <Shape {...own} />;
  }
  if (n.t !== 'g') return <Fragment>{kids}</Fragment>;
  const t = n.tf?.length ? matrixOf(n.tf) : undefined;
  if (t) return <G {...own} transform={t}>{kids}</G>;
  // a bare group draws what its children draw — do not spend a view on it
  return Object.keys(own).length > 0 ? <G {...own}>{kids}</G> : <Fragment>{kids}</Fragment>;
}

export function KoaRoom({ width, height }: { width: number; height: number }) {
  return (
    <Svg width={width} height={height} viewBox={ROOM_VIEWBOX} preserveAspectRatio="xMidYMax slice">
      {ROOM_NODES.map((n, i) => (
        <RoomNode key={i} n={n} />
      ))}
    </Svg>
  );
}
