import type { AppLang } from './i18n';

/**
 * Strings specific to the native app's screens, in both languages.
 * The big ported dictionary (i18n.ts) covers web-page copy; these cover
 * the native layouts. Merged with it in useI18n().
 */
const en = {
  // Today
  nGoodMorning: 'Good morning',
  nGoodAfternoon: 'Good afternoon',
  nGoodEvening: 'Good evening',
  nReadiness: 'Readiness',
  nReadinessHint: 'Log sleep and training to get your score',
  nActivity: 'Activity',
  nSteps: 'steps',
  nKcalToday: 'kcal today',
  nSleep: 'Sleep',
  nLastNight: 'Last night',
  nWater: 'Water',
  nStayHydrated: 'stay hydrated',
  nOfTarget: 'of {x} target',
  nTodoDone: 'Logged',
  nTodoOff: 'Off',
  nTodoOn: 'On',
  nTodoSkip: 'Skip today',
  nTodoSkipAsk: 'Skip {n} today?',
  nTodoSkipWhy: "It comes back tomorrow — today's count drops by one.",
  nTodoSkipped: 'Skipped',
  nTodoUnskip: 'Put back',
  nTodoEdit: 'Edit',
  nTodoRemindOff: 'Reminder off',
  nTodoTitle: "Today's to-do",
  nTodoMeal: 'Meal',
  nTodoWorkout: 'Workout',
  nTodoBio: 'Biometrics',
  nTodoLog: 'Log',
  nSyncHealth: 'Sync Apple Health',
  nLogShort: 'Log',
  nQuality: 'Quality',

  // Nutrition
  nToday: 'Today',
  nProtein: 'Protein',
  nCarbs: 'Carbs',
  nKcalLeft: 'left',
  nFat: 'Fat',
  nLogMealBtn: 'Log Meal',
  nNoMeals: 'No meals yet',
  nNoMealsHint: 'Log your first meal of the day above',
  nBreakfast: 'Breakfast',
  nLunch: 'Lunch',
  nDinner: 'Dinner',
  nSnack: 'Snack',
  nPreWorkout: 'Pre-workout',
  nPostWorkout: 'Post-workout',
  nFavorites: 'Favorites',
  nRecent: 'Recent',

  // Workouts
  nThisWeek: 'This week',
  nSessions: 'sessions',
  nVolume: 'Volume',
  nKgLifted: 'kg lifted',
  nLogWorkoutBtn: 'Log Workout',
  nNoWorkouts: 'No workouts yet',
  nNoWorkoutsHint: 'Log your first session — readiness adapts to your training load',

  // Progress
  nWeight: 'Weight',
  nLast30d: 'Last 30 days',
  nLast14d: 'Last 14 days',
  nNotEnoughData: 'Not enough data yet',
  nBuildTrendHint: 'Log sleep and training to build your trend',

  // Log Meal sheet
  nLogMealTitle: 'Log Meal',
  nSearchFoods: 'Search foods…',
  nWhatDidYouEat: 'What did you eat? (optional)',
  nCalories: 'Calories (kcal)',
  nProteinG: 'Protein g',
  nCarbsG: 'Carbs g',
  nFatG: 'Fat g',
  nSaveMeal: 'Save Meal',

  // Log Workout sheet
  nLogWorkoutTitle: 'Log Workout',
  nWorkoutName: 'Workout name (e.g. Push Day)',
  nSets: 'Sets',
  nExercise: 'Exercise',
  nReps: 'reps',
  nAddSet: 'Add set',
  nRpe: 'Session effort (RPE)',
  nSaveWorkout: 'Save Workout',
  nLgBwHint: 'Leave the weight empty for a bodyweight set.',
  nLgNewExercise: 'Different exercise',
  nLgNeedReps: 'A set is saved once it has reps.',

  // Log Sleep sheet
  nLogSleepTitle: 'Log Sleep',
  nBedtime: 'Bedtime',
  nWaketime: 'Wake',
  nWakeUp: 'Wake up',
  nDuration: 'Duration',
  nHowSleep: 'How did you sleep?',
  nSaveSleep: 'Save Sleep',

  // Settings
  nDailyTarget: 'Daily target',
  /* Một câu SỰ VIỆC, không phải một lời mắng. Nó nói ra con số và chiều, rồi
     dừng — người dùng có thể cố ý muốn một tỉ lệ khác, và app không chặn lưu. */
  nMacroDriftOver: 'These four add up to {sum} kcal — {drift} over your daily target.',
  nMacroDriftUnder: 'These four add up to {sum} kcal — {drift} under your daily target.',
  nGoal: 'Goal',
  nTrainingLevel: 'Training level',
  nAbout: 'About',
  nVersion: 'Version',
  nSignOut: 'Sign Out',
  nSignOutConfirm: 'Are you sure you want to sign out?',
  nCancel: 'Cancel',

  // Auth
  nSignInSubtitle: 'Sign in to continue',
  nSignUpSubtitle: 'Create your account',
  nYourName: 'Your name',
  nEmail: 'Email',
  nPassword: 'Password',
  nSignIn: 'Sign In',
  nSignUp: 'Sign Up',
  nNoAccount: "Don't have an account? ",
  nHaveAccount: 'Already have an account? ',

  // AI Coach
  nAskCoach: 'Ask your coach',
  nAskCoachHint: 'Training, nutrition, recovery — answers use your real data',
  nMessageCoach: 'Message your coach…',
  nHistory: 'History',
  nNoHistory: 'No conversations yet',

  // Extras
  nAwards: 'Awards',
  nNoAwards: 'No awards yet',
  nNoAwardsHint: 'Keep logging — achievements unlock automatically',
  nChallenges: 'Challenges',
  nNoChallenges: 'No challenges this week',
  nNoChallengesHint: 'Weekly challenges appear when you start logging',
  nCompleted: 'Completed',
  nChallengeDone: 'Challenge complete',
  nGrocery: 'Shopping list',
  nAddItem: 'Add an item…',
  nGroceryLeft: '{n} left',
  nNoGrocery: 'List is empty',
  nNoGroceryHint: 'Add ingredients you need to buy',

  // Library screens
  nSupplements: 'Supplements',
  nTakenToday: 'taken today',
  nWeightTitle: 'Weight check-in',
  nLogWeight: 'Log',
  /* Màn `/log-weight` — xem `src/app/log-weight.tsx`. */
  nWeighTitle: 'Update body stats',
  nWeighSub: 'Small changes make a better you, every day 🌱',
  nWeighHint: 'Drag to adjust',
  nWeighSave: 'Save changes',
  nAllSupplementsDone: 'All done for today',
  nReadinessTrend: 'Readiness trend',
  nSmartTips: 'Smart tips',
  nTipsHint: 'AI insights from your recent data',
  nTipsLoading: 'Reading your trends…',
  nTipsRefresh: 'Refresh',
  nTipsEmpty: 'Log more to unlock tips',
  // read failed — deliberately not the same words as an empty day
  // Segment-neutral on purpose: this card appears on Progress and Workouts too,
  // and "Could not load today" is wrong on a screen showing three months of
  // weight history.
  nLoadFailed: 'Could not load your data',
  nLoadFailedHint: 'Your data is safe. The app just could not reach it.',
  nCrashTitle: 'This screen stopped working',
  nCrashHint: 'Your data is safe — nothing was lost. Open the screen again.',
  nCrashStuck: 'It still will not open. Close the app and start it again.',
  /* Thẻ trong Cài Đặt, không phải màn báo lỗi ở trên. Hai chuỗi này từng được
     viết THẲNG trong `settings.tsx` bằng `lang === 'vi' ? … : …` — chỗ duy nhất
     của màn ấy không đi qua bảng dịch, nên không luật nào soi được chúng. */
  nCrashLogTitle: 'Crash log',
  nCrashLogHint: 'Last {n} — tap to send',
  /* Thẻ số đo ghép trái/phải. KHÔNG cắt " trái" ra khỏi `measureBicepL`:
     tiếng Anh đặt bên ở ĐẦU ("Left bicep"), nên phép cắt chỉ đúng một thứ tiếng. */
  nMeasureBiceps: 'Biceps',
  nMeasureThighs: 'Thighs',
  nMeasureCalves: 'Calves',
  nMeasureSides: 'left · right',
  nMeasureLatest: 'Last measured {date}',
  /* Hai segment của tab Tập luyện kể từ khi Tiến trình gộp vào (24/09). */
  nSegTraining: 'Training',
  nSegBody: 'Body',
  /* Tab Cộng đồng — một VỎ, xem `app/(tabs)/community.tsx`. */
  nCommunityTitle: 'Community',
  /* Cộng đồng, giai đoạn 1 (nền móng + bài Workout). */
  nCmFollowing: 'Following',
  nCmDiscover: 'Discover',
  nCmSetupTitle: 'Create your community profile',
  nCmSetupHint: 'Pick a name and a mascot to share workouts and follow people.',
  nCmSetupCta: 'Create profile',
  nCmComposer: 'Share a workout…',
  nCmEmptyFollowing: 'You\'re not following anyone yet',
  nCmEmptyFollowingHint: 'Open Discover to find people to train with.',
  nCmEmptyDiscover: 'No posts yet',
  nCmEmptyDiscoverHint: 'Share your first workout.',
  nCmOpenDiscover: 'Open Discover',
  nCmWorkout: 'Workout',
  nCmMinutes: '~{n} min',
  nCmMoreExercises: '+ {n} more exercises',
  nCmTry: 'Try workout',
  nCmTried: 'Added to your workouts',
  nCmTriedSkipped: '{n} of the author\'s own exercises couldn\'t be copied',
  nCmTryNone: 'This workout only has custom exercises — nothing to copy',
  nCmFollowersOnly: 'Followers only',
  nCmHiddenNotice: 'Hidden from others after reports',
  nCmVerified: 'Official account',
  nCmLike: 'Like',
  nCmComment: 'Comment',
  nCmSave: 'Save',
  nCmShare: 'Share',
  nCmMore: 'More',
  nCmShareText: '{title} on ASCND — {n} exercises',
  nCmJustNow: 'just now',
  nCmMinAgo: '{n}m ago',
  nCmHourAgo: '{n}h ago',
  nCmDayAgo: '{n}d ago',
  nCmReport: 'Report',
  nCmReportWhy: 'Why are you reporting this?',
  nCmReasonSpam: 'Spam',
  nCmReasonHarass: 'Harassment',
  nCmReasonInappropriate: 'Inappropriate',
  nCmReasonMisleading: 'Misleading or unsafe',
  nCmReported: 'Report sent. Thank you.',
  nCmBlock: 'Block @{h}',
  nCmBlockConfirm: 'Block @{h}?',
  nCmBlockBody: 'You won\'t see each other\'s posts, and any follows between you are removed.',
  nCmBlocked: 'Blocked',
  nCmDeletePost: 'Delete post',
  nCmDeletePostBody: 'The post and all its comments will be deleted.',
  nCmPostTitle: 'Post',
  nCmCommentsEmpty: 'No comments yet',
  nCmCommentPlaceholder: 'Add a comment…',
  nCmSend: 'Send',
  nCmDeleteComment: 'Delete comment',
  nCmPostGone: 'This post is no longer available',
  nCmProfileTitle: 'Community profile',
  nCmHandle: 'Username',
  nCmHandleHint: '3–24 characters: lowercase letters, numbers, . and _',
  nCmHandleTaken: 'That username is taken',
  nCmDisplayName: 'Display name',
  nCmBio: 'Bio',
  nCmAvatar: 'Your mascot',
  nCmRulesAgree: 'By creating a profile you agree to the Community Rules: no tolerance for objectionable, abusive or harmful content. Violations are removed and accounts can be suspended.',
  nCmRulesLink: 'Read the Terms',
  nCmSaveProfile: 'Save profile',
  nCmFollowers: 'Followers',
  nCmFollow: 'Follow',
  nCmEditProfile: 'Edit profile',
  nCmUserGone: 'Profile not found',
  nCmShareTitle: 'Share workout',
  nCmPickSession: 'Choose a workout',
  nCmNoSessions: 'No workouts to share yet',
  nCmShared: 'Shared',
  nCmCaption: 'Caption',
  nCmCaptionPh: 'How did it go?',
  nCmVisibility: 'Who can see this',
  nCmPublic: 'Everyone',
  nCmPost: 'Post',
  nCmPosted: 'Posted to the community',
  nCmPrivacyNote: 'Only what\'s on this card is shared. Your weight, measurements and workout history stay private.',
  nCmAlreadyShared: 'This workout is already shared',
  /* Cộng đồng — bài Progress (#8, A). B thêm khối nRc… riêng của mình. */
  nPgTitle: 'Progress · {n} weeks',
  nPgFromTo: 'From {a} → {b}',
  nPgWeight: 'Weight',
  nPgWaist: 'Waist',
  nPgShareTitle: 'Share progress',
  nPgRange: 'Time range',
  nPgWeeks: '{n} wk',
  nPgInclude: 'What to share',
  nPgLift: 'Strength lift',
  nPgNoLift: 'None',
  nPgNothing: 'Not enough data in this range — each number needs at least two entries.',
  nPgEntry: 'Share your progress',
  nPgShareText: '{n}-week progress on ASCND',
  nPgPrivacy: 'Only the numbers you switch on are shared. Your day-by-day weigh-ins and measurements stay private.',
  nPgAsk: 'What do you want to share?',
  nPgAskWorkout: 'A workout',
  nPgAskProgress: 'My progress',
  nPgCaptionPh: 'What changed for you?',
  /* Cộng đồng — Thử thách (#9, A). */
  nChBadge: 'Challenge',
  nChDays: '{a} / {b} days',
  nChPeople: '{n} joined',
  nChJoin: 'Join',
  nChClaim: 'Claim {n} coins',
  nChClaimed: 'Reward claimed',
  nChEndsIn: '{n} days left',
  nChEnded: 'Ended',
  nChStartsIn: 'Starts in {n} days',
  nChLeave: 'Leave challenge',
  nChLeaveBody: 'Your logged workouts stay. You can join again while it is open.',
  nChReward: 'Reward',
  nChCoins: '{n} coins',
  nChHow: 'Counts days with at least one logged workout, in your local time.',
  nChDone: 'Challenge complete!',
  nChGot: '+{n} coins',
  nChTitle: 'Challenge',
  nChGone: 'This challenge is no longer available',
  nClTitle: 'Challenges',
  nClSeeAll: 'All challenges',
  nClJoined: 'Joined',
  nClOpen: 'Open to join',
  nClSoon: 'Starting soon',
  nClDone: 'Completed',
  nClReady: 'Goal reached — claim your reward',
  nClClaimedOn: 'Completed {d}',
  nClNone: 'No challenges right now',
  nClNoneHint: 'New challenges show up here, and the ones you finish stay here.',
  nPvTitle: 'Privacy',
  nPvDefault: 'Default audience',
  nPvDefaultHint: 'Used for each new post. You can still change it while posting.',
  nPvBlocked: 'Blocked',
  nPvBlockedHint: "People you block can't see your posts, and you won't see theirs. Unblocking doesn't follow them again.",
  nPvBlockedNone: "You haven't blocked anyone.",
  nPvUnblock: 'Unblock',
  nPvUnblockTitle: 'Unblock {name}?',
  nPvUnblockBody: "You'll see each other's posts again. They won't be notified.",
  nPvNoProfile: 'Deleted profile',
  nPvSince: 'Blocked {date}',
  nPvPosts: 'Your posts',
  nPvDeleteAll: 'Delete all my posts',
  nPvDeleteAllHint: 'Your profile and followers stay.',
  nPvDeleteAllTitle: 'Delete all your posts?',
  nPvDeleteAllBody: 'Every post you have shared goes, with its likes and comments.',
  nPvDeleteAllSure: "This can't be undone",
  nPvDeleteAllSureBody: 'Delete every post for good?',
  nPvContinue: 'Continue',
  nPvDeleteForGood: 'Delete for good',
  nPvDeleted: 'Deleted {n} posts',
  nPvNothing: 'You have no posts to delete',
  nNtTitle: 'Notifications',
  nNtOpenNew: 'Notifications, new activity',
  nNtLike: '{name} liked your post',
  nNtLikeMany: '{name} and {n} others liked your post',
  nNtComment: '{name} commented on your post',
  nNtFollow: '{name} started following you',
  nNtEmpty: 'No notifications yet',
  nNtEmptyHint: "When someone likes, comments on or follows you, you'll see it here.",
  nRmReached: 'You reached {title}',
  nRmLeft: 'Claim {c} coins · {n} days left',
  nRmLast: 'Claim {c} coins · today is the last day',
  nRmLeftPlain: '{n} days left to claim',
  nRmLastPlain: 'Today is the last day to claim',
  nNtUnread: 'unread',
  nShShare: 'Share',
  nShChallenge: '{title}: {a}/{b} days',
  nSrTitle: 'Find people',
  nSrPlaceholder: 'Name or @handle',
  nSrClear: 'Clear search',
  nSrMin: 'Type at least 2 letters',
  nSrSuggested: 'Suggested for you',
  nSrWhyOfficial: 'Official ASCND account',
  nSrWhyActive: '{n} posts in the last 2 weeks',
  nSrNone: 'No one matches "{q}"',
  nSrNoneHint: 'Try the start of a name or @handle.',
  nSrNoSuggestions: 'No suggestions right now',
  nSrFind: 'Find people to follow',
  nUpAll: 'All',
  nUpProgress: 'Progress',
  nUpRecipe: 'Recipes',
  // What the target-calibration card promises, and it has to be true: this
  // runs on the device, not on a model.
  nCalibrateHint:
    'Measures what you actually burn from your intake and what the scale did, then suggests a calorie target that matches it.',
  nRetry: 'Try again',
  // ── screen-reader names for icon-only buttons ──
  // Verbs, not nouns: the reader already says "button", so the label supplies
  // the action. "Trash" leaves the listener guessing; "Delete photo" does not.
  a11yBack: 'Go back',
  a11yClose: 'Close',
  a11yDismiss: 'Dismiss',
  a11yDelete: 'Delete',
  a11yEdit: 'Edit',
  a11yAdd: 'Add',
  a11yMore: 'More options',
  a11yIncrease: 'Increase',
  a11yDecrease: 'Decrease',
  a11ySettings: 'Open settings',
  a11ySearch: 'Search',
  a11yClearSearch: 'Clear search',
  a11yLogMeal: 'Log a meal',
  a11yAskCoach: 'Ask the coach',
  a11yCloseCoach: 'Close the coach',
  a11yFavourite: 'Toggle favourite',
  a11yTakePhoto: 'Take photo',
  a11ySwitchCamera: 'Switch camera',
  a11yPrevWeek: 'Previous week',
  a11yNextWeek: 'Next week',
  a11yEditGoal: 'Edit goal',
  a11yOpenRoom: 'Open Koa’s room',
  a11yCheckOff: 'Mark as taken',
  a11yExpand: 'Show details',
  a11ySend: 'Send message',
  a11yHistory: 'Chat history',
  a11yNewChat: 'New chat',
  a11yShare: 'Share',
  a11yScanFood: 'Scan food with camera',
  a11yScanBarcode: 'Scan barcode',
  a11yRemove: 'Remove',
  /* Nhãn HIỆN của nút Sửa trên hàng tiêu đề mục. Ngắn vì nó ngồi cạnh một
     tiêu đề 14 điểm, không phải trong một ô riêng — `a11yEditLayout` ngay dưới
     là câu đầy đủ cho trình đọc màn hình. */
  editLayout: 'Edit',
  a11yEditLayout: 'Rearrange dashboard',
  a11yDoneEditing: 'Done rearranging',
  a11yAcceptTerms: 'Accept the terms',
  a11yMoveUp: 'Move up',
  a11yMoveDown: 'Move down',
  a11ySleepQuality: 'Sleep quality {x} of {max}',
  // ── deleting an account ──
  nDeleteAccount: 'Delete account',
  nDeleteAccountDesc: 'Permanently removes your account and everything in it',
  nDeleteAccountTitle: 'Delete your account?',
  nDeleteAccountBody:
    'This erases your meals, workouts, sleep, weight and Koa’s wardrobe. It cannot be undone. Export your data first if you want to keep it.',
  nDeleteAccountConfirm: 'Delete everything',
  nDeleteAccountDone: 'Your account has been deleted.',
  nDeleteAccountNotSetUp: 'Account deletion is not available on this server yet.',
  nDeleteAccountFailed: 'Could not delete the account. Nothing was removed.',
  nDeleteAccountPartial:
    'Could not delete the account. Your progress photos have already been removed and cannot be recovered — please try again to finish deleting the account.',
  a11yPrevItem: 'Previous item',
  a11yNextItem: 'Next item',
  a11yAddWater: 'Add {x} {unit}',
  // ── weight history, and correcting it ──
  nWeightHistory: 'Logged weights',
  nWeightEntries: '{n} entries',
  nWeightEntriesOne: '1 entry',
  nWeightSeeAll: 'See all {n} entries',
  nHeroMore: 'See all details',
  nHeroDetails: 'Details for {n}',
  nDeleteWeight: 'Remove this weight',
  nDeleteWeightMsg: 'Remove the {x} entry? The chart and your BMI will be recalculated.',
  // ── logged sessions, and correcting them ──
  nDeleteSession: 'Remove this session',
  nDeleteSessionMsg: 'Remove {x}? Your training load and readiness will be recalculated.',
  // AI edge functions — one message per distinct cause, so wiring a new
  // Supabase project up tells you what is missing instead of "it failed"
  aiNotDeployed: 'This AI feature is not set up on the server yet.',
  aiProviderError: 'The AI service could not answer. Try again in a moment.',
  aiSignedOut: 'Please sign in again to use AI features.',
  aiOffline: 'No connection — AI needs the internet.',
  aiRateLimited: 'You have used up the AI for now. Try again later.',
  aiUnknown: 'Something went wrong with the AI request.',
  nDiaryLoadFailed: 'Could not load your meals',
  nNoSupplements: 'No supplements yet',
  nNoSupplementsHint: 'Add your stack in the web app — the checklist syncs here',
  nExercises: 'Exercise Library',
  nSearchExercises: 'Search exercises…',
  nNoExercises: 'No exercises found',
  nNoExercisesHint: 'Your exercise library syncs from the web app',
  nRoutine: 'Weekly Routine',
  /* The name of the destination, in both languages on purpose — see the entry
     for it in `tools/i18n.mjs`. */
  nPlan: 'Plan',
  nPlanNewWorkout: 'Create a new workout',
  nTodayTraining: 'Today',
  nStartWorkout: 'Start workout',
  nTodayRest: 'Rest day',
  nTodayRestHint: 'Rest, or something light',
  nTodayNone: 'No workout planned',
  nTodayNoneHint: 'Pick one for today, or just log what you do',
  nTodayPick: 'Pick a workout',
  nTodayDone: 'Done today',
  nLogFree: 'Log a session',
  nTodayExtra: 'Log an extra session',
  nSeePlan: 'See plan',
  nYourWorkouts: 'Workout templates',
  nSetsShort: 'sets',
  nToolsExercises: 'Exercise library',
  nToolsInsight: 'Per-exercise progress',
  nLibraryHistory: 'Library & history',
  nSessionCount: '{n} sessions logged',
  nExerciseCount: '{n} exercises',
  nAboutMinutes: '~{n} min',
  nPlanNothingToday: 'Nothing planned today',
  nPlanAdded: 'Added to Plan · {d}',
  nRest: 'Rest',
  nDeload: 'Deload',
  nChooseWorkout: 'Choose workout',
  nRoutineHint: 'Tap a day to assign a workout, mark rest, or set deload',
  nRoutineDone: 'Done',
  nRoutineTodo: 'To do',
  nRoutineMissed: 'Not trained',
  nRoutineRestDay: 'Rest day',
  nRoutineRestHint: 'Rest, or something light',
  nRoutineExercises: '{n} exercises',
  nRoutineMinutes: '{n} min',
  nRoutineEffort: 'RPE {x}',
  nRoutineEffortRange: 'RPE {a}–{b}',
  nRoutineToday: 'Today',
  nRoutineNoTemplates: 'No saved workouts yet — build one first.',
  nRdSet: 'Set {n}',
  nRdProgress: '{done}/{total} sets',
  /* Số hiệp khi KHÔNG có một bộ số nào đại diện được — xem `blockSummary`. */
  nRdSetsN: '{n} sets',
  nRdFinish: 'Finish workout',
  nRdFuture: 'Not this day yet',
  nRestNext: 'Up next',
  nRestSetOf: 'Set {n}/{t}',
  nRdAddExercise: 'Add an exercise',
  nRdAddSet: 'Add set',
  nRdExtraName: 'Exercise name',
  nRdResting: 'Rest',
  nRdSkip: 'Skip',
  nRdEmptyPlan: 'This day has no workout on it',
  nRdSaved: 'Workout logged',
  nRdBodyweight: 'Bodyweight',
  nExKind: 'Kind of movement',
  nExKindHint: 'It decides what "progress" means for this one',
  nExKindcompound: 'Compound',
  nExKindisolation: 'Isolation',
  nExKindbodyweight: 'Bodyweight',
  nExKindtimed: 'Hold',
  nLgWarmup: 'Warm-up set',
  nLgWarmupShort: 'W',
  nLgHoldHint: 'For a hold, type the seconds — 45s.',
  nXiTitle: 'Exercise progress',
  nXiSubtitle: 'How each movement is going, from what you have logged',
  nXiEmpty: 'No exercises logged in the last 90 days',
  nXiEmptyHint: 'Log a workout and this fills in on its own',
  nXiSessions: '{n} sessions',
  nXiOneSession: '1 session',
  nXiE1rm: 'Est. 1RM',
  nXiE1rmNote: 'An estimate from your best set, not a max you have lifted',
  nXiBest: 'Best set',
  nXiBodyweightUnknown: 'Counted in reps — no weigh-in on record',
  nXiScopeToday: "Today's plan",
  nXiScopeWeek: 'Weekly plan',
  nXiScopeAll: 'All',
  nXiScopeEmptyToday: 'Nothing scheduled today',
  nXiScopeUnlogged: 'Nothing logged yet for the exercises on your plan',
  nXiScopeEmptyWeek: 'Your week has no exercises on it yet',
  nXiScopeHint: 'Set a weekly plan and this filters to what you are actually training',
  nXiOnly: 'Showing one exercise',
  nXiShowAll: 'Show all',
  nXiNeedsAttention: 'Worth a look',
  nXiGoingWell: 'Going well',
  nXiNotYet: 'Needs more sessions',
  nXiSummary: '{a} improving · {b} worth a look',
  nXiSummaryThin: 'Nothing has enough sessions yet — {n} waiting',
  nXiWindowNote: 'Every number on this page reads the last {n} days.',
  nXiTapMore: 'Details',
  nXiFootnote: 'Estimated one-rep maxes come from your best set. They are estimates, not maxes you have lifted, and are only computed up to 10 reps.',
  nXiAt: 'at {w}',
  nLgLastTime: 'Last time {v}',
  nXiEvidence: 'Recent comparable sessions',
  nXiLastToday: 'Trained today',
  nXiLastDays: 'Last trained {n} days ago',
  nXiAgoShort: '{n}d ago',
  nXiStale: "Out of step with how often you usually train this — the reading below is about a block you've left",
  nXiVolatile: 'Your worst session sat {p}% under your best — something outside the programme is moving these',
  nXiWindowWeight: 'Best load in 90 days: {v} {unit}, up from {prev}',
  nXiWindowReps: 'Best in 90 days: {v} reps at {w} {unit}, up from {prev}',
  nXiWindowRepsBody: 'Best in 90 days: {v} reps, up from {prev}',
  nXiWindowAgo: '{n} days ago',
  nXiNeedMore: 'Needs {n} sessions before this can say anything',
  nXiTrendIMPROVING: 'Improving',
  nXiTrendSTABLE: 'Holding steady',
  nXiTrendPLATEAU: 'Plateau',
  nXiTrendDECLINING: 'Going down',
  nXiTrendINSUFFICIENT_DATA: 'Not enough yet',
  nXiReadyREADY_TO_PROGRESS: 'Ready for more',
  nXiReadyMAINTAIN: 'Keep as is',
  nXiReadyNOT_READY: 'Not yet',
  nXiKindcompound: 'Compound',
  nXiKindisolation: 'Isolation',
  nXiKindbodyweight: 'Bodyweight',
  nXiKindtimed: 'Hold',
  nXiChangeUp: 'up {p}% on your best before',
  nXiChangeDown: 'down {p}% on your best before',
  nXiChangeFlat: 'level with your best before',
  nXiNoUpward: 'Last {n} comparable sessions show no meaningful upward trend',
  nXiConf: 'Confidence: {c}',
  nXiConfhigh: 'high',
  nXiConfmedium: 'medium',
  nXiConflow: 'low',
  nXiConfnone: 'none',
  nXiOpen: 'Exercise progress',
  /* ── Exercise Guide ── */
  nEgTitle: 'How to perform',
  nEgOpen: 'How to perform this exercise',
  nEgCues: 'Form cues',
  nEgMistakes: 'Common mistakes',
  nEgEquipment: 'Equipment',
  nEgMuscles: 'Target muscles',
  nEgNoMedia: 'No demonstration yet',
  nEgNoMediaHint: 'The cues below still describe the movement',
  nEgMediaFailed: 'Demonstration could not load',
  nEgEmpty: 'No guidance for this exercise yet',
  nEgEmptyHint: 'Guidance comes from the exercise library, and this one has none yet',
  nEgMediaDemo: 'Temporary illustration, not a demonstration of this exercise',
  nEgMediaAlt: 'Demonstration of {v}',
  /*
    ── bốn nhãn tab, và nay cả bốn BẤM ĐƯỢC ──

    Hai lượt trước chúng là hình vẽ: không nhận chạm, giấu khỏi cây trợ năng,
    vì ba trong bốn "không có dữ liệu ở sau". Chủ dự án đã đọc lý do ấy và chốt
    ngược lại — *"bấm được cả và search để thêm thông tin cho các mục đó"*.

    Nên lượt này đi TÌM dữ liệu thay vì bịa ra màn hình cho nó. Cả ba tab sau
    đều đọc thứ repo đã có:

        Cơ tác động   `muscleArtKeysFor` + bộ hình giải phẫu `muscle-art.tsx`
        Thiết bị      nhãn dụng cụ + bài khác cùng dụng cụ (`guide-related.ts`)
        Liên quan     bài khác cùng nhóm cơ (cùng tệp ấy)

    Không một dòng nào trong ba tab ấy do màn hình nghĩ ra, và tab nào không có
    gì thật để nói thì nói THẲNG là chưa có — xem `nEgNoMuscles` và hai câu
    dưới nó. Đặt hàng: *"Do not create fake screens merely to make the tab
    clickable."*
  */
  nEgTabOverview: 'Overview',
  nEgTabMuscles: 'Muscles & gear',
  nEgTabRelated: 'Related',
  /*
    Ba câu "chưa có gì", và chúng nói ba sự thật KHÁC NHAU.

    Gộp thành một câu chung ("Chưa có dữ liệu") là xoá mất thông tin duy nhất
    một tab rỗng còn mang được: nhóm cơ thì thư viện không nhận ra chuỗi đang
    lưu, dụng cụ thì cột ấy trống, còn "liên quan" thì thư viện thật sự không
    có bài nào khác đánh vào cùng chỗ.
  */
  nEgNoMuscles: 'This exercise has no muscle group recorded',
  nEgNoEquipment: 'This exercise has no equipment recorded',
  nEgNoRelated: 'No other exercise in your library works these muscles',
  /** Tiêu đề danh sách bài khác — `{v}` là nhãn dụng cụ, đã dịch. */
  nEgAlsoEquipment: 'Other exercises using {v}',
  nEgAlsoMuscles: 'Other exercises for these muscles',
  /* Nút này ĐÓNG sheet — cùng hành động với dấu ✕ và cú vuốt xuống. Màn này
     mở từ trong một buổi đang chạy, nên "bắt đầu bài tập" nghĩa là thôi đọc và
     quay lại làm. Nó KHÔNG tạo hành vi sản phẩm mới.

     Dấu trang cạnh nó KHÔNG có khoá chữ nào, và đó là chủ ý: nó bị giấu khỏi
     cây trợ năng nên không có gì để đọc lên. Lượt đầu tôi thêm `a11yBookmark`
     theo phản xạ, và luật "chữ chết" của cổng bắt ngay — một nhãn không ai
     dựng là một lời hứa rằng thứ kia bấm được. Khi dấu trang có kho để lưu
     vào, nhãn quay lại CÙNG với hành động, không trước. */
  /* Nhãn trợ năng của nút mở media. "Open", không phải "Play": với một tấm
     ảnh thì "phát" là nói sai loại, và bộ đọc màn hình là chỗ sai ấy nghe rõ
     nhất. Glyph vẫn theo ảnh tham chiếu — xem `styles.play`. */
  nEgOpenMedia: 'Open illustration',
  nEgStart: 'Start Exercise',
  nRdAlready: 'Already logged',
  nRdExtra: 'Did something extra? Log it separately',
  nRdAppend: 'Add to today\u2019s workout',
  nRdAppended: 'Added to today\u2019s workout',
  nRdAppendOffline: 'Needs a connection to add to a workout already saved. Log it separately for now.',
  nRdUntickTitle: 'Undo this set?',
  nRdUntickMsg: 'It is ticked as done. Unticking says it did not happen, and takes it out of what gets saved.',
  nRdUntickConfirm: 'Untick',
  nRdNeedInfo: 'Name the exercise and enter reps (or seconds) before ticking it done.',
  nRdSetRemoved: 'Set removed from the workout',
  nRdLoggedAt: 'at {t}',
  nRdPlanToday: "Today's plan",
  nRdUsePlan: 'Use',
  nMealPlans: 'Meal Plans',
  nMealPlanNone: 'No meal plans yet',
  nMealPlanWhat: 'A meal plan is a few days of eating written down in advance, so "what do I eat today" is already answered.',
  nMealPlanNew: 'New meal plan',
  nMealPlanOpen: 'Open',
  nMealsPerDay: 'meals/day',
  nDay: 'Day',
  nNoMealPlans: 'No meal plans yet',
  nMpAddFood: 'Add food',
  nMpStepPlanHint: 'What you will call this plan when you come back to it',
  nMpStepSlotsHint: 'How many meals each day of the plan has',
  nMpPreview: 'What you will get',
  nMpPreviewSum: '{d} days · {m} meals a day · {t} meals in all',
  nMpPlanNameEg: 'e.g. Meal Prep Week 1',
  nMpNextAddFood: 'Create and add food',
  nExNameHint: 'What you will search for when you add it to a workout',
  nExGroupHint: 'Where it files itself in the library',
  nExGearHint: 'Optional — barbell, dumbbell, machine, or nothing at all',
  nMpStepPlan: 'Plan',
  nMpStepDay: 'Day',
  nMpStepMeal: 'Meal',
  nMpStepFood: 'Food',
  nMpStepDayHint: 'Which day of the plan this goes on',
  nMpStepMealHint: 'Which meal of that day',
  nMpStepFoodHint: 'Search, then tap to add. The sheet stays open — a meal is rarely one food.',
  nMpAddTitle: 'Add food',
  nMpAddedN: '{n} added',
  nMpDone: 'Done',
  nMpPickFood: 'Pick a food',
  nMpEmptyDay: 'Nothing planned',
  nMpAvgPerDay: '{x} kcal/day',
  nMpTarget: 'target {x}',
  nMpPctTarget: '{p}% of target',
  nMpDayEmptyHint: 'Nothing planned for this day yet.',
  nMpPlanEmpty: 'This plan has no food in it yet',
  nMpWeekTotal: '{x} kcal across the week',
  nMpFromList: 'From your list',
  nMpNoMatch: 'No food matches “{x}”',
  nMpAlready: 'added',
  nMpEatIt: 'Log to today',
  nMpEaten: 'In today',
  nMpAgainTitle: 'Already in today',
  nMpAgainBody: 'Today already has a {m} with exactly these foods. Log it a second time?',
  nMpAgainYes: 'Log again',
  nMpEatDone: '{m} added to today’s diary',
  nMpEatQueued: '{m} saved — will sync when you are back online',
  nMpNoFibre: 'Logged from a plan carries no fibre — the plan does not record it.',
  // Repeating a meal you have already eaten
  nRmTitle: 'Eat this again',
  nRmHint: 'Fills the form — check it, then save.',
  nRmYesterday: 'yesterday',
  nRmToday: 'today',
  nRmDaysAgo: '{n} days ago',
  nRmFoods: '{n} foods',
  nWeeklyReview: 'Weekly Review',
  nAiAnalysis: 'AI Analysis',
  nWeeklyReviewHint: 'Let AI analyze your week and give recommendations for the next one',
  nAnalyzeWeek: 'Analyze with AI',
  nWeekScore: 'Week score',

  // Mascot
  nMascotTitle: 'Companion',
  nMascotToggleHint: 'Your companion nudges you based on today\u2019s data',
  nMusicLabel: 'Music',
  nKoaCompanionTitle: 'Koa follows you',
  nKoaCompanionHint: 'Koa stands beside you on every screen and moves as your day changes. Turn this off to keep Koa on Today only.',
  nMascotRoomTitle: 'Companion room, shop & challenges',
  /* ── what a failed write says, when the thing that failed wrote SQL ──
     Keys, not sentences, at the throw site: see `lib/error-copy.ts`. Each one
     names what happened and what to do; none names a table or a constraint. */
  errOffline: 'No connection — your change is not saved yet. It will go through when you are back online.',
  errOnlineOnly: 'No connection — not sent, and not kept to send later.',
  errSignedOut: 'Your session has expired. Sign in again and try once more.',
  errDuplicate: 'This is already saved — no need to add it twice.',
  errInvalid: 'That value could not be saved. Check it and try again.',
  errNotFound: 'This is no longer here. Refresh and have another look.',
  errServer: 'The server had a problem. Nothing was lost — try again in a moment.',
  errUnknown: 'Could not save. Try again in a moment.',
  nStreakFreezeFailed: 'Could not use your streak insurance — we will try again next time you open the app',
  nMascotSleep: 'Morning! How did you sleep? Log it so I can compute your readiness 😴',
  nMascotMeal: 'No meals logged yet today — fuel up and log it! 🍽',
  nMascotWater: 'Hydration check — you\u2019re under half your water target 💧',
  nMascotWorkout: 'Great window for a workout right now. Ready when you are 💪',
  nMascotPraise: 'You\u2019re crushing it today. Keep the streak alive! 🔥',
  nMascotHello: 'I\u2019m watching your stats — log something and I\u2019ll cheer you on!',
  // ── Koa naming what you did, then what is left ──
  // Short on purpose: the two get joined into one speech bubble, and a bubble
  // people actually read is one line.
  nMascotWinSleep: 'Sleep logged 😴',
  nMascotWinMeal: 'Meals logged 🍽',
  nMascotWinWater: 'Water on target 💧',
  nMascotWinWorkout: 'Workout done 💪',
  nMascotGapSleep: 'log last night too',
  nMascotGapMeal: 'log a meal next',
  nMascotGapWater: 'drink some water',
  nMascotGapWorkout: 'a session would round it off',
  nMascotThen: '{win} — {gap}',
  nMascotLocked: 'Locked',
  nMascotPro: 'PRO · coming soon',
  nMascotUnlockedBadge: 'Unlocked',
  nMascotUnlockedTitle: 'New companion unlocked!',
  nMascotUse: 'Use now',
  nMascotLater: 'Later',

  // Scanner
  nCameraNeeded: 'Camera access needed',
  nCameraHint: 'ASCND scans barcodes to log packaged foods instantly',
  nAllowCamera: 'Allow Camera',
  nPointBarcode: 'Point at a barcode',
  nLookingUp: 'Looking up product…',
  nNotFound: 'Product not found — try again',

  // AI food scan
  nScanFood: 'Scan food',
  nAiScanTitle: 'AI Food Scan',
  nScanModeFood: 'Dish',
  nScanModeLabel: 'Label',
  nScanFoodHint: 'Point at your meal and tap the shutter',
  nScanLabelHint: 'Frame the nutrition facts panel',
  nAnalyzing: 'Analyzing…',
  nScanNoFood: 'No food detected — try again',
  /* Where the numbers came from. Two of these three modes read a printed
     figure; one guesses a portion size from a picture, and they are nowhere
     near equally accurate. Check what they are before adding. */
  nScanFromPhoto: 'Estimated from the photo — portion size is a guess. Check before adding.',
  nScanFromLabel: 'Read off the nutrition panel.',
  nScanRetake: 'Retake',
  nScanAdd: 'Add {n} items',
  nScanAddOne: 'Add 1 item',
  nRetake: 'Retake',
  nScanError: 'Scan failed — try again',

  nLegal: 'Policies & Legal',
  nTemplates: 'Templates',
  nTemplateName: 'Template name',
  nCreateExercise: 'New exercise',
  nMuscleGroup: 'Muscle group',
  nEquipment: 'Equipment',
  nExerciseName: 'Exercise name',
  nNoExercisesFound: 'No exercises found',
  nSuggestions: 'Suggestions',
  nRestSec: 'Rest',
  nDeleteTemplate: 'Delete template?',

  // Workout builder — the two-step flow
  nWbTitle: 'New workout',
  nWbStepPick: 'Choose exercises',
  nWbStepReview: 'Sets & name',
  nWbPickHint: 'Tap what you want in this workout. Sets and reps come next.',
  nWbAll: 'All',
  nWbSelected: '{n} selected',
  nWbNext: 'Next',
  nWbNoMatch: 'Nothing matches “{x}”',
  nWbCreateNamed: 'Create “{x}”',
  nWbLibraryEmpty: 'Your exercise library is empty',
  nWbAddMore: 'Add more exercises',
  nWbSummary: '{n} exercises · {s} sets · about {m} min',
  nWbNameHint: 'Named from the muscles you picked — change it if you like.',
  nWbNameOne: '{x} day',
  nWbNameTwo: '{a} & {b}',
  nWbType: 'Type',
  nWbSave: 'Save workout',
  nWbSets: 'Sets',
  nWbReps: 'Reps',
  nWbLoad: 'Weight',
  nWbBodyweight: 'Bodyweight',
  nWbRest: 'Rest between sets',
  nWbEffort: 'Effort',
  nWbEffortHint: 'How the last rep should feel. 10 is failure.',

  // Saved workout card — rest and effort read back
  nTplRest: 'Rest {x}',
  nTplNoRest: 'No rest',
  nTplEffort: 'Effort {x}/10',
  nWbMoveUp: 'Move earlier',
  nWbMoveDown: 'Move later',
  nWbRemove: 'Remove from workout',
  nWbDone: 'Done',
  nWbTypePush: 'Push',
  nWbTypePull: 'Pull',
  nWbTypeLegs: 'Legs',
  nWbTypeUpper: 'Upper body',
  nWbTypeLower: 'Lower body',
  nWbTypeFullBody: 'Full body',
  nWbTypeStrength: 'Strength',
  nWbTypeHypertrophy: 'Hypertrophy',
  nWbTypeCardio: 'Cardio',
  nWbTypeCustom: 'Custom',

  // Water & Steps detail
  nWaterTitle: 'Hydration',
  nStepsTitle: 'Steps',
  nLast7Days: 'Last 7 days',
  nAverage: 'Average',
  nRangeWeek: 'Week',
  nRangeMonth: 'Month',
  nRangeYear: 'Year',
  nRangeAll: 'All',
  nDailyAvg: 'Daily average',
  nTodayTotal: 'Today',
  nTodayLogs: 'Today’s log',
  nStepsGoal: 'Goal {x}',
  nQuickAdd: 'Quick add',
  // manual entry, for the amounts the presets do not cover
  nWaterCustom: 'Another amount',
  nWaterEntries: '{n} entries',
  nWaterEntriesOne: '1 entry',
  nWaterCustomTitle: 'How much did you drink?',
  nWaterTooMuch: 'That is more than {x} in one go — check the number',

  // Progress photos
  nPhotoFront: 'Front',
  nPhotoSide: 'Side',
  nPhotoBack: 'Back',
  nPhotoUploading: 'Uploading…',
  nPhotoDelete: 'Delete photo?',
  nPhotoAdd: 'Add progress photo',
  nPhotoCapture: 'Capture',

  // Today's diary — collapsed meal cards + quick stats
  nDiaryItems: '{n} items',
  nDiaryItemsOne: '1 item',
  nDiaryEntries: '{n} meals',

  // A day that is not today — the `/diary` screen
  nDiaryOtherDays: 'Other days',
  nDiaryTitle: 'Meal diary',
  nDiaryToday: 'Today',
  nDiaryYesterday: 'Yesterday',
  nDiaryPrevDay: 'Previous day',
  nDiaryNextDay: 'Next day',
  nDiaryDayTotal: 'Day total',
  nDiaryAddMeal: 'Log a meal for this day',
  // editing what is already logged
  nItemEdit: 'Edit servings',
  nItemDelete: 'Remove from log',
  nItemDeleteMsg: 'Remove {name} from today\'s log?',
  /* The same question about a day that is not today. Kept as a second string
     rather than making the first one vaguer: "today's log" is the more precise
     sentence and it is the one asked almost every time. */
  nItemDeleteMsgDay: 'Remove {name} from this day\'s log?',
  /* Vuốt trên thẻ bữa ăn — nhãn ngắn vì chúng ngồi trong một ô chừng 76 điểm. */
  nMealSwipeAdd: 'Add',
  nMealSwipeDelete: 'Delete',
  nMealDeleteTitle: 'Delete {meal}?',
  nMealDeleteMsg: 'This removes all {n} foods logged under {meal} today.',
  nMealDeleteMsgDay: 'This removes all {n} foods logged under {meal} on this day.',
  nItemServings: 'Servings',
  nServingsMore: 'More servings',
  nServingsLess: 'Fewer servings',
  nItemUpdated: 'Log updated',
  nUndo: 'Undo',
  nItemRestored: 'Put back',
  nQuickCalories: 'Calories',
  nQuickProtein: 'Protein',
  nQuickWater: 'Water',

  // Weight changes card (Progress)
  nWeightChanges: 'Weight Changes',
  nWcDays: '{n} day',
  nWcAllTime: 'All Time',
  nWcNoChange: 'No change',
  nWcIncrease: 'Increase',
  nWcDecrease: 'Decrease',
  nWcNoData: 'Log your weight to see changes here',

  // Weight goal (Progress weight chart)
  nQuickActions: 'Quick actions',
  nHealthAssistant: 'Health assistant',
  nQuickActionsClose: 'Close quick actions',
  nWeightGoal: 'Goal',
  nWeightGoalUnset: 'Not set',
  nWeightGoalTitle: 'Target weight',
  nWeightGoalEdit: 'Edit Weight Goal',
  nWeightGoalDone: 'Done',
  nWeightGoalGain: 'Gain weight',
  nWeightGoalLose: 'Lose weight',
  nWeightGoalMaintain: 'Maintain weight',
  nWeightGoalClear: 'Clear',
  nWeightGoalToGo: '{x} to go',
  nWeightGoalReached: 'Target reached',

  // The four ways to log a meal.
  //
  // Two labels each, and both are needed. `nWay*` is what the tile says — a
  // quarter of a card's width, so it has to hold on one line. `nAdd*` is what
  // VoiceOver says, where there is no width to fit and "Tìm món" alone does
  // not say what is being searched.
  nWayPhoto: 'Photo',
  nWayBarcode: 'Barcode',
  nWaySearch: 'Search',
  nWayManual: 'Manual',
  nAddCamera: 'Scan a meal',
  nAddBarcode: 'Scan a barcode',
  nAddSearch: 'Search food',
  nAddManual: 'Enter manually',

  // Meal builder
  nMealItems: 'Items',
  nMealNoItems: 'Search, scan, or add a food to start',
  nNutritionTotal: 'Nutrition total',
  nServings: 'Servings',
  nAiSuggest: 'AI suggest',
  nAiSuggestTitle: 'AI Meal Ideas',
  nAiSuggestHint: 'Based on your remaining macros today',
  nAiThinking: 'Cooking up ideas…',
  nAddThis: 'Add',
  nPrepTime: '{n} min',
  nAiNoIdeas: 'No suggestions right now — try later',

  // Reminders (local notifications)
  nRemindersTitle: 'Reminders',
  nRemindersDesc: 'Daily nudges to keep your streak',
  nRemindersEnable: 'Allow notifications',
  nRemindersDenied: 'Notifications are off. Enable them in iOS Settings › ASCND.',
  nReminderWater: 'Drink water',
  nReminderWaterBody: 'Time for a glass of water 💧',
  nReminderSupplements: 'Supplements',
  nReminderSupplementsBody: 'Take your supplements 💊',
  nReminderBedtime: 'Wind down',
  nReminderBedtimeBody: 'Bedtime soon — start winding down 😴',
  nReminderWeighIn: 'Morning weigh-in',
  nReminderWeighInBody: 'Log your weight before breakfast ⚖️',
  nReminderWorkout: 'Train today',
  nReminderWorkoutBody: 'Your plan has a session scheduled 💪',
  nReminderMeal: 'Log a meal',
  nReminderMealBody: "Nothing logged today yet — what did you eat? 🍽",
  nReminderBiometrics: 'Morning readings',
  nReminderBiometricsBody: 'Resting heart rate and HRV, before you get up ❤️',
  nReminderSleepLog: 'Log last night',
  nReminderSleepLogBody: 'How did you sleep? Write it down 🌙',
  nTodoRemindAt: 'Remind at',
  nTodoSetReminder: 'Set a time',
  nTodoReminderOff: 'Turn reminder off',
  nReminderTime: 'Time',
  nReminderEveryHours: 'Every {n}h',

  // Offline
  nOffline: 'Offline — showing saved data',
  nReconnecting: 'Reconnecting — catching up',
  nLoadingData: 'Loading your data',
  nHealthSynced: 'Apple Health synced!',

  // Mascot room
  nRoomQuests: 'Daily quests',
  nRoomQuestsHint: 'Train, eat, hydrate — earn coins for your buddy',
  nRoomWeeklyBonus: 'Weekly challenge bonus',
  nRoomShop: 'Shop',
  nRoomDressing: 'Dressing Room',
  nRoomOverview: 'Room',
  nRoomOverviewHint: 'Pick a corner of the room above.',
  nRoomOutfits: 'Outfits',
  nRoomCloset: 'Closet',
  nRoomGymGear: 'Gym gear',
  nRoomStageSkins: 'Stages',
  nRoomUse: 'Use',
  nRoomUsing: 'Using',
  nRoomClaim: 'Claim',
  nRoomClaimed: 'Claimed',
  nRoomBuy: 'Buy',
  nRoomWear: 'Wear',
  nRoomTakeOff: 'Take off',
  nRoomWearing: 'Wearing',
  nRoomPlaced: 'In your gym',
  nRoomPlace: 'Place',
  nRoomAll: 'All',
  nRoomOwned: 'Owned',
  nRoomLockLevel: 'Lv.{n}',
  nRoomCollections: 'Collections',
  nRoomCollectionsHint: 'Collect a full set for a special reward!',
  nRoomSetProgress: '{a}/{b} owned',
  nRoomSetDone: 'Set complete!',
  nRoomEmptyCat: 'More coming soon',
  /* The closet is empty because nothing has been bought yet — a different fact
     from the catalogue being empty, and the one the shop can do something
     about. Saying "more coming soon" there tells the user the app has run out
     of things while thirty-six outfits sit one tab away. */
  nRoomEmptyCloset: 'Nothing worn yet — pick something from Outfits',
  nRoomGoToOutfits: 'Browse outfits',
  nRoomSetClaimed: 'Reward claimed',
  nRoomNotEnough: 'Not enough coins yet — finish more quests!',
  nShopOffline: 'The shop needs a connection — coins are spent on the server.',
  nRoomCoins: 'coins',
  nRoomEarned: '+{n} coins!',
  nRoomBought: 'Purchased!',
  nRoomUpgrades: 'Room upgrades',
  nRoomInstalled: 'Installed',
  nRoomStreak: '{n}-day streak',
  nRoomLearned: 'Koa has noticed: you usually log {what} around {time}',
  /* Koa's seven deterministic lines. Short, specific, and never a motivational
     quote — the engine picks the intent, this picks the words. */
  nKoaPraiseSmall: 'Nice one.',
  nKoaPraiseBig: 'That one counts. Well done.',
  nKoaProudRecord: 'That was your strongest one yet.',
  nKoaWelcomeBack: 'Good to see you. Let\u2019s pick it back up.',
  nKoaStreakSaved: 'Covered that day for you \u2014 streak\u2019s still on.',
  nKoaStreakRisk: 'Still time to keep the streak tonight.',
  nKoaDayComplete: 'All five, done. That was a good day.',
  /* The record moment. Every line names the number it beat, because "new
     record" on its own is a noise an app makes — what makes it worth stopping
     for is seeing what it used to be. */
  nPrTitle: 'New personal record',
  nPrTitleMany: '{n} new records',
  nPrWeightLine: '{ex} — {value} {unit}, was {prev}',
  nPrRepsLine: '{ex} — {value} reps at {w} {unit}, was {prev}',
  nPrRepsBodyLine: '{ex} — {value} reps, was {prev}',
  nPrFirstLoad: '{ex} — {value} {unit}, first time loaded',
  nPrContinue: 'Tap to continue',
  /* Smart scheduling. Every line names the reading it came from — a suggested
     time with no stated source is the app asserting something about somebody's
     life without saying how it knows. */
  nSmartFrom: 'Koa noticed: {what}',
  nSmartBedtime: 'you go to bed at {t}',
  nSmartWake: 'you wake at {t}',
  nSmartWorkout: 'you usually log training around {t}',
  nSmartMove: 'Remind at {t}',
  nSmartMoved: 'Moved to {t}',
  nFreezeTitle: 'Streak Freeze',
  nFreezeHeld: '{n}/{max} in the drawer',
  nFreezeHint: 'Covers one missed day automatically. Koa only spends one when it actually saves the streak.',
  nFreezeBuy: 'Buy · {n}',
  nFreezeFull: 'Drawer full',
  nFreezeSaved: 'A freeze covered {n} day',
  nFreezeSavedPlural: 'Freezes covered {n} days',
  /* Nouns, for the sentence above. The win phrases nearby are whole sentences
     with emoji in them ("Meals logged 🍽") and read as nonsense inside another
     sentence — a label is not a message. */
  nThingMeal: 'meals',
  nThingWorkout: 'training',
  nThingWater: 'water',
  nThingSleep: 'sleep',
  nThingSteps: 'steps',
  nStreakLit: '{n}-day streak, today is logged',
  nStreakAtRisk: '{n}-day streak, nothing logged today yet',
  nStageStreak: 'Day streak',
  nStageQuests: 'Quests',
  nRoomLevel: 'Level {n}',
  nRoomLevelHint: '{n} XP to the next level',
  nRoomLevelUp: 'Level up! Your buddy reached level {n}',
  nRoomMoodTired: "I'm feeling sluggish today… log a meal or a workout to wake me up!",
  nRoomWardrobe: 'Wardrobe',
  nRoomChangeBuddy: 'Change buddy',
  nRoomWelcome: 'Welcome gift: +{n} coins!',
  // Rank ladder
  nRoomNextRank: 'Next: {r} at level {n}',
  nRoomMaxRank: 'Top rank reached — legendary!',
  nRoomRankUp: 'New rank unlocked: {r}!',
  nRoomJourney: 'Journey',
  nRoomLevelsToRank: '{n} levels to {r}',
  // Today's energy
  nRoomEnergy: "Today's energy",
  nRoomEnergyEmpty: 'Running on empty — log a meal or a workout to wake me up.',
  nRoomEnergyLow: 'Just getting started — keep the day going!',
  nRoomEnergyMid: 'Feeling good — a couple more to go.',
  nRoomEnergyFull: 'Fully charged! Every daily goal is done.',
  nRoomSigMeal: 'Meal',
  nRoomSigWorkout: 'Workout',
  nRoomSigWater: 'Water',
  nRoomSigSleep: 'Sleep',
  nRoomSigSteps: 'Steps',

  // App lock (Face ID / biometrics)
  nLockTitle: 'App Lock',
  nLockDesc: 'Require Face ID to open ASCND',
  nLockUnavailable: 'Biometric lock is unavailable on this device',
  nLockPrompt: 'Unlock ASCND',
  nLockLocked: 'ASCND is locked',
  nLockUnlock: 'Unlock',

  /* ── Cộng đồng · bài RECIPE (#7, người làm: B) ──
     Tiền tố `nRc`, theo luật chơi ở issue #6. Những câu dùng chung với các loại
     bài khác (chú thích, ai thấy được, Đăng, Đã chia sẻ) đọc lại khoá `nCm…`
     của A chứ không chép thành bản thứ hai. */
  nRcRecipe: 'Recipe',
  nRcGrams: '{n} g',
  nRcMoreIngredients: '+ {n} more ingredients',
  nRcAddToMeal: 'Add to a meal',
  nRcAddWhich: 'Add to which meal today?',
  nRcAdded: 'Added to today · {meal}',
  nRcAddedQueued: 'Saved to today · {meal} — will sync when you are back online',
  nRcShareText: '{title} on ASCND — {kcal} kcal',
  nRcShareTitle: 'Share a recipe',
  nRcPickMeal: 'Choose a meal you logged',
  nRcNoMeals: 'No meals logged in the last 30 days',
  nRcItems: '{n} foods',
  nRcName: 'Dish name',
  nRcNamePh: 'e.g. High-protein chicken bowl',
  nRcNameNeeded: 'Give the dish a name first',
  nRcCaptionPh: 'What makes it good?',
  nRcPrivacyNote: 'Only this meal is shared — its foods, amounts and totals. The rest of your diary stays private.',
  nRcAlreadyShared: 'This meal is already shared',
  nRcEmptyMeal: 'This meal has no foods to share',
  nRcAsk: 'A recipe',

  /* ── Cộng đồng · Thư viện Đã lưu (#10, người làm: B) ── */
  nSvTitle: 'Saved',
  nBdTitle: 'Challenge badges',
  nBdHint: 'Show the challenges you have completed on your community profile. Off means nobody sees them — not even on your own profile.',
  nBdHide: 'Hidden',
  nBdShow: 'Shown',
  nBdA11y: 'Badge: {title}',
  nSvSaved: 'Saved to your library',
  nSvOpen: 'View library',
  nSvWorkouts: 'Workouts',
  nSvRecipes: 'Recipes',
  nSvAll: 'All',
  nSvEmpty: 'Nothing saved yet',
  nSvEmptyHint: 'Tap the bookmark on a post to keep it here.',
  nSvEmptyWorkouts: 'No saved workouts',
  nSvEmptyRecipes: 'No saved recipes',
};

const vi: typeof en = {
  nGoodMorning: 'Chào buổi sáng',
  nGoodAfternoon: 'Chào buổi chiều',
  nGoodEvening: 'Chào buổi tối',
  nReadiness: 'Mức sẵn sàng',
  nReadinessHint: 'Ghi giấc ngủ và buổi tập để có điểm số',
  nActivity: 'Hoạt động',
  nSteps: 'bước',
  nKcalToday: 'kcal hôm nay',
  nSleep: 'Giấc ngủ',
  nLastNight: 'Đêm qua',
  nWater: 'Nước',
  nStayHydrated: 'uống đủ nước nhé',
  nOfTarget: 'mục tiêu {x}',
  nTodoDone: 'Đã ghi',
  nTodoOff: 'Tắt',
  nTodoOn: 'Bật',
  nTodoSkip: 'Bỏ qua hôm nay',
  nTodoSkipAsk: 'Bỏ qua {n} hôm nay?',
  nTodoSkipWhy: 'Việc này sẽ quay lại vào ngày mai, và hôm nay bớt đi một việc.',
  nTodoSkipped: 'Đã bỏ qua',
  nTodoUnskip: 'Lấy lại',
  nTodoEdit: 'Sửa lại',
  nTodoRemindOff: 'Tắt nhắc',
  nTodoTitle: 'Cần làm hôm nay',
  nTodoMeal: 'Bữa ăn',
  nTodoWorkout: 'Buổi tập',
  nTodoBio: 'Sinh trắc',
  nTodoLog: 'Ghi',
  nSyncHealth: 'Đồng bộ Apple Health',
  nLogShort: 'Ghi',
  nQuality: 'Chất lượng',

  nToday: 'Hôm nay',
  nProtein: 'Đạm',
  nCarbs: 'Tinh bột',
  nKcalLeft: 'còn lại',
  nFat: 'Béo',
  nLogMealBtn: 'Ghi bữa ăn',
  nNoMeals: 'Chưa có bữa nào',
  nNoMealsHint: 'Ghi bữa đầu tiên trong ngày ở nút phía trên',
  nBreakfast: 'Bữa sáng',
  nLunch: 'Bữa trưa',
  nDinner: 'Bữa tối',
  nSnack: 'Ăn vặt',
  nPreWorkout: 'Trước tập',
  nPostWorkout: 'Sau tập',
  nFavorites: 'Yêu thích',
  nRecent: 'Gần đây',

  nThisWeek: 'Tuần này',
  nSessions: 'buổi tập',
  nVolume: 'Khối lượng',
  nKgLifted: 'kg đã nâng',
  nLogWorkoutBtn: 'Ghi buổi tập',
  nNoWorkouts: 'Chưa có buổi tập nào',
  nNoWorkoutsHint: 'Ghi buổi đầu tiên — mức sẵn sàng sẽ thích ứng theo khối lượng tập',

  nWeight: 'Cân nặng',
  nLast30d: '30 ngày qua',
  nLast14d: '14 ngày qua',
  nNotEnoughData: 'Chưa đủ dữ liệu',
  nBuildTrendHint: 'Ghi giấc ngủ và buổi tập để dựng xu hướng',

  nLogMealTitle: 'Ghi bữa ăn',
  nSearchFoods: 'Tìm món ăn…',
  nWhatDidYouEat: 'Bạn đã ăn gì? (không bắt buộc)',
  nCalories: 'Calo (kcal)',
  nProteinG: 'Đạm (g)',
  nCarbsG: 'Tinh bột (g)',
  nFatG: 'Béo (g)',
  nSaveMeal: 'Lưu bữa ăn',

  nLogWorkoutTitle: 'Ghi buổi tập',
  nWorkoutName: 'Tên buổi tập (VD: Ngày đẩy)',
  nSets: 'Các set',
  nExercise: 'Bài tập',
  nReps: 'reps',
  nAddSet: 'Thêm set',
  nRpe: 'Độ gắng sức (RPE)',
  nSaveWorkout: 'Lưu buổi tập',
  nLgBwHint: 'Bỏ trống ô cân nặng nếu là set tay không.',
  nLgNewExercise: 'Bài tập khác',
  nLgNeedReps: 'Set có số rep thì mới được lưu.',

  nLogSleepTitle: 'Ghi giấc ngủ',
  nBedtime: 'Giờ đi ngủ',
  nWaketime: 'Giờ dậy',
  nWakeUp: 'Giờ dậy',
  nDuration: 'Thời lượng',
  nHowSleep: 'Bạn ngủ thế nào?',
  nSaveSleep: 'Lưu giấc ngủ',

  nDailyTarget: 'Mục tiêu ngày',
  nMacroDriftOver: 'Bốn số này cộng lại {sum} kcal — vượt mục tiêu ngày {drift}.',
  nMacroDriftUnder: 'Bốn số này cộng lại {sum} kcal — thiếu so với mục tiêu ngày {drift}.',
  nGoal: 'Mục tiêu',
  nTrainingLevel: 'Trình độ tập',
  nAbout: 'Thông tin',
  nVersion: 'Phiên bản',
  nSignOut: 'Đăng xuất',
  nSignOutConfirm: 'Bạn chắc chắn muốn đăng xuất?',
  nCancel: 'Huỷ',

  nSignInSubtitle: 'Đăng nhập để tiếp tục',
  nSignUpSubtitle: 'Tạo tài khoản của bạn',
  nYourName: 'Tên của bạn',
  nEmail: 'Email',
  nPassword: 'Mật khẩu',
  nSignIn: 'Đăng nhập',
  nSignUp: 'Đăng ký',
  nNoAccount: 'Chưa có tài khoản? ',
  nHaveAccount: 'Đã có tài khoản? ',

  nAskCoach: 'Hỏi huấn luyện viên',
  nAskCoachHint: 'Tập luyện, dinh dưỡng, phục hồi — trả lời dựa trên dữ liệu thật của bạn',
  nMessageCoach: 'Nhắn cho coach…',
  nHistory: 'Lịch sử',
  nNoHistory: 'Chưa có hội thoại nào',

  nAwards: 'Thành tích',
  nNoAwards: 'Chưa có thành tích nào',
  nNoAwardsHint: 'Cứ ghi chép đều — thành tích sẽ tự mở khoá',
  nChallenges: 'Thử thách',
  nNoChallenges: 'Tuần này chưa có thử thách',
  nNoChallengesHint: 'Thử thách tuần xuất hiện khi bạn bắt đầu ghi chép',
  nCompleted: 'Hoàn thành',
  nChallengeDone: 'Hoàn thành thử thách',
  nGrocery: 'Danh sách đi chợ',
  nAddItem: 'Thêm món cần mua…',
  nGroceryLeft: 'còn {n} món',
  nNoGrocery: 'Danh sách trống',
  nNoGroceryHint: 'Thêm nguyên liệu bạn cần mua',

  nSupplements: 'Thực phẩm bổ sung',
  nTakenToday: 'đã uống hôm nay',
  nWeightTitle: 'Ghi cân nặng',
  nLogWeight: 'Ghi',
  /* Màn `/log-weight` — xem `src/app/log-weight.tsx`. */
  nWeighTitle: 'Cập nhật chỉ số cơ thể',
  nWeighSub: 'Những thay đổi nhỏ tạo nên phiên bản tốt hơn mỗi ngày 🌱',
  nWeighHint: 'Kéo để điều chỉnh',
  nWeighSave: 'Lưu thay đổi',
  nAllSupplementsDone: 'Hôm nay uống đủ rồi',
  nReadinessTrend: 'Xu hướng sẵn sàng',
  nSmartTips: 'Gợi ý thông minh',
  nTipsHint: 'AI phân tích từ dữ liệu gần đây của bạn',
  nTipsLoading: 'Đang đọc xu hướng…',
  nTipsRefresh: 'Làm mới',
  nTipsEmpty: 'Ghi thêm để mở khoá gợi ý',
  // read failed — deliberately not the same words as an empty day
  // Cố ý không nhắc "hôm nay": thẻ này còn hiện ở Tiến trình và Buổi tập.
  nLoadFailed: 'Không tải được dữ liệu',
  nLoadFailedHint: 'Dữ liệu của bạn vẫn an toàn, chỉ là app chưa lấy được.',
  nCrashTitle: 'Màn hình này vừa dừng lại',
  nCrashHint: 'Dữ liệu của bạn vẫn an toàn, không mất gì cả. Thử mở lại màn hình.',
  nCrashStuck: 'Vẫn chưa mở lại được. Hãy đóng app rồi khởi động lại.',
  nCrashLogTitle: 'Nhật ký sự cố',
  nCrashLogHint: '{n} lần gần nhất — chạm để gửi đi',
  nMeasureBiceps: 'Bắp tay',
  nMeasureThighs: 'Đùi',
  nMeasureCalves: 'Bắp chân',
  nMeasureSides: 'trái · phải',
  nMeasureLatest: 'Lần đo gần nhất {date}',
  nSegTraining: 'Buổi tập',
  nSegBody: 'Cơ thể',
  nCommunityTitle: 'Cộng đồng',
  nCmFollowing: 'Đang theo dõi',
  nCmDiscover: 'Khám phá',
  nCmSetupTitle: 'Tạo hồ sơ cộng đồng',
  nCmSetupHint: 'Chọn tên và linh vật để chia sẻ buổi tập và theo dõi người khác.',
  nCmSetupCta: 'Tạo hồ sơ',
  nCmComposer: 'Chia sẻ một buổi tập…',
  nCmEmptyFollowing: 'Chưa theo dõi ai',
  nCmEmptyFollowingHint: 'Mở Khám phá để tìm người tập cùng.',
  nCmEmptyDiscover: 'Chưa có bài nào',
  nCmEmptyDiscoverHint: 'Chia sẻ buổi tập đầu tiên của bạn.',
  nCmOpenDiscover: 'Mở Khám phá',
  nCmWorkout: 'Buổi tập',
  nCmMinutes: '~{n} phút',
  nCmMoreExercises: '+ {n} bài tập khác',
  nCmTry: 'Thử workout',
  nCmTried: 'Đã thêm vào Buổi tập của bạn',
  nCmTriedSkipped: '{n} bài tự tạo của người đăng không chép được',
  nCmTryNone: 'Buổi này chỉ có bài tập tự tạo — không chép được',
  nCmFollowersOnly: 'Chỉ người theo dõi',
  nCmHiddenNotice: 'Đang ẩn với người khác vì bị báo cáo',
  nCmVerified: 'Tài khoản chính thức',
  nCmLike: 'Thích',
  nCmComment: 'Bình luận',
  nCmSave: 'Lưu',
  nCmShare: 'Chia sẻ',
  nCmMore: 'Thêm',
  nCmShareText: '{title} trên ASCND — {n} bài tập',
  nCmJustNow: 'vừa xong',
  nCmMinAgo: '{n} phút trước',
  nCmHourAgo: '{n} giờ trước',
  nCmDayAgo: '{n} ngày trước',
  nCmReport: 'Báo cáo',
  nCmReportWhy: 'Vì sao bạn báo cáo?',
  nCmReasonSpam: 'Nội dung rác',
  nCmReasonHarass: 'Quấy rối',
  nCmReasonInappropriate: 'Nội dung không phù hợp',
  nCmReasonMisleading: 'Sai lệch hoặc nguy hiểm',
  nCmReported: 'Đã gửi báo cáo. Cảm ơn bạn.',
  nCmBlock: 'Chặn @{h}',
  nCmBlockConfirm: 'Chặn @{h}?',
  nCmBlockBody: 'Hai bạn sẽ không thấy bài của nhau, và theo dõi giữa hai bạn bị gỡ.',
  nCmBlocked: 'Đã chặn',
  nCmDeletePost: 'Xoá bài',
  nCmDeletePostBody: 'Bài và mọi bình luận trên bài sẽ bị xoá.',
  nCmPostTitle: 'Bài đăng',
  nCmCommentsEmpty: 'Chưa có bình luận',
  nCmCommentPlaceholder: 'Viết bình luận…',
  nCmSend: 'Gửi',
  nCmDeleteComment: 'Xoá bình luận',
  nCmPostGone: 'Bài không còn nữa',
  nCmProfileTitle: 'Hồ sơ cộng đồng',
  nCmHandle: 'Tên người dùng',
  nCmHandleHint: '3–24 ký tự: chữ thường, số, dấu chấm, gạch dưới',
  nCmHandleTaken: 'Tên này đã có người dùng',
  nCmDisplayName: 'Tên hiển thị',
  nCmBio: 'Giới thiệu',
  nCmAvatar: 'Linh vật đại diện',
  nCmRulesAgree: 'Khi tạo hồ sơ, bạn đồng ý với Quy tắc cộng đồng: không dung thứ nội dung phản cảm, quấy rối hay gây nguy hiểm. Nội dung vi phạm bị gỡ và tài khoản có thể bị khoá.',
  nCmRulesLink: 'Đọc Điều khoản',
  nCmSaveProfile: 'Lưu hồ sơ',
  nCmFollowers: 'Người theo dõi',
  nCmFollow: 'Theo dõi',
  nCmEditProfile: 'Sửa hồ sơ',
  nCmUserGone: 'Không tìm thấy hồ sơ này',
  nCmShareTitle: 'Chia sẻ buổi tập',
  nCmPickSession: 'Chọn buổi tập',
  nCmNoSessions: 'Chưa có buổi tập nào để chia sẻ',
  nCmShared: 'Đã chia sẻ',
  nCmCaption: 'Chú thích',
  nCmCaptionPh: 'Buổi hôm nay thế nào?',
  nCmVisibility: 'Ai thấy được',
  nCmPublic: 'Mọi người',
  nCmPost: 'Đăng',
  nCmPosted: 'Đã đăng lên cộng đồng',
  nCmPrivacyNote: 'Chỉ những gì trên thẻ này được chia sẻ. Cân nặng, số đo và lịch sử buổi tập vẫn là của riêng bạn.',
  nCmAlreadyShared: 'Buổi này đã được chia sẻ rồi',
  nPgTitle: 'Tiến trình · {n} tuần',
  nPgFromTo: 'Từ {a} → {b}',
  nPgWeight: 'Cân nặng',
  nPgWaist: 'Vòng eo',
  nPgShareTitle: 'Chia sẻ tiến trình',
  nPgRange: 'Khoảng thời gian',
  nPgWeeks: '{n} tuần',
  nPgInclude: 'Chia sẻ những số nào',
  nPgLift: 'Bài sức mạnh',
  nPgNoLift: 'Không',
  nPgNothing: 'Chưa đủ dữ liệu trong khoảng này — mỗi số cần ít nhất hai lần ghi.',
  nPgEntry: 'Chia sẻ tiến trình lên cộng đồng',
  nPgShareText: 'Tiến trình {n} tuần trên ASCND',
  nPgPrivacy: 'Chỉ những số bạn bật ở trên được chia sẻ. Nhật ký cân và số đo từng ngày vẫn là của riêng bạn.',
  nPgAsk: 'Bạn muốn chia sẻ gì?',
  nPgAskWorkout: 'Một buổi tập',
  nPgAskProgress: 'Tiến trình của tôi',
  nPgCaptionPh: 'Hành trình vừa qua của bạn thế nào?',
  nChBadge: 'Thử thách',
  nChDays: '{a} / {b} ngày',
  nChPeople: '{n} người tham gia',
  nChJoin: 'Tham gia',
  nChClaim: 'Nhận {n} xu',
  nChClaimed: 'Đã nhận thưởng',
  nChEndsIn: 'Còn {n} ngày',
  nChEnded: 'Đã kết thúc',
  nChStartsIn: 'Bắt đầu sau {n} ngày',
  nChLeave: 'Rời thử thách',
  nChLeaveBody: 'Buổi tập đã ghi vẫn còn nguyên. Bạn có thể tham gia lại khi thử thách còn mở.',
  nChReward: 'Phần thưởng',
  nChCoins: '{n} xu',
  nChHow: 'Tính những ngày có ít nhất một buổi tập được ghi, theo giờ địa phương của bạn.',
  nChDone: 'Hoàn thành thử thách!',
  nChGot: '+{n} xu',
  nChTitle: 'Thử thách',
  nChGone: 'Thử thách không còn nữa',
  nClTitle: 'Thử thách',
  nClSeeAll: 'Tất cả thử thách',
  nClJoined: 'Đang tham gia',
  nClOpen: 'Đang mở',
  nClSoon: 'Sắp bắt đầu',
  nClDone: 'Đã hoàn thành',
  nClReady: 'Đã đạt — nhận thưởng',
  nClClaimedOn: 'Hoàn thành {d}',
  nClNone: 'Chưa có thử thách nào',
  nClNoneHint: 'Thử thách mới sẽ hiện ở đây, và những thử thách bạn hoàn thành cũng ở lại đây.',
  nPvTitle: 'Quyền riêng tư',
  nPvDefault: 'Mặc định khi đăng',
  nPvDefaultHint: 'Áp cho mỗi bài mới. Lúc đăng vẫn đổi được.',
  nPvBlocked: 'Đã chặn',
  nPvBlockedHint: 'Người bị chặn không thấy bài của bạn, và bạn không thấy bài của họ. Bỏ chặn không tự theo dõi lại.',
  nPvBlockedNone: 'Bạn chưa chặn ai.',
  nPvUnblock: 'Bỏ chặn',
  nPvUnblockTitle: 'Bỏ chặn {name}?',
  nPvUnblockBody: 'Hai bạn sẽ lại thấy bài của nhau. Họ không được báo.',
  nPvNoProfile: 'Hồ sơ đã xoá',
  nPvSince: 'Chặn từ {date}',
  nPvPosts: 'Bài của bạn',
  nPvDeleteAll: 'Xoá mọi bài của tôi',
  nPvDeleteAllHint: 'Hồ sơ và người theo dõi vẫn giữ nguyên.',
  nPvDeleteAllTitle: 'Xoá mọi bài của bạn?',
  nPvDeleteAllBody: 'Mọi bài bạn đã chia sẻ sẽ mất, cùng lượt thích và bình luận trên chúng.',
  nPvDeleteAllSure: 'Không hoàn tác được',
  nPvDeleteAllSureBody: 'Xoá hẳn mọi bài?',
  nPvContinue: 'Tiếp tục',
  nPvDeleteForGood: 'Xoá hẳn',
  nPvDeleted: 'Đã xoá {n} bài',
  nPvNothing: 'Bạn chưa có bài nào để xoá',
  nNtTitle: 'Thông báo',
  nNtOpenNew: 'Thông báo, có mục mới',
  nNtLike: '{name} đã thích bài của bạn',
  nNtLikeMany: '{name} và {n} người khác đã thích bài của bạn',
  nNtComment: '{name} đã bình luận bài của bạn',
  nNtFollow: '{name} đã theo dõi bạn',
  nNtEmpty: 'Chưa có thông báo nào',
  nNtEmptyHint: 'Khi có người thích, bình luận hay theo dõi bạn, bạn sẽ thấy ở đây.',
  nRmReached: 'Bạn đã đạt {title}',
  nRmLeft: 'Nhận {c} xu · còn {n} ngày',
  nRmLast: 'Nhận {c} xu · hôm nay là ngày cuối',
  nRmLeftPlain: 'Còn {n} ngày để nhận',
  nRmLastPlain: 'Hôm nay là ngày cuối để nhận',
  nNtUnread: 'chưa đọc',
  nShShare: 'Chia sẻ',
  nShChallenge: '{title}: {a}/{b} ngày',
  nSrTitle: 'Tìm người',
  nSrPlaceholder: 'Tên hoặc @handle',
  nSrClear: 'Xoá chữ đã gõ',
  nSrMin: 'Gõ ít nhất 2 ký tự',
  nSrSuggested: 'Gợi ý cho bạn',
  nSrWhyOfficial: 'Tài khoản chính thức ASCND',
  nSrWhyActive: '{n} bài trong 2 tuần qua',
  nSrNone: 'Không ai khớp "{q}"',
  nSrNoneHint: 'Thử gõ phần đầu của tên hoặc @handle.',
  nSrNoSuggestions: 'Chưa có gợi ý nào',
  nSrFind: 'Tìm người để theo dõi',
  nUpAll: 'Tất cả',
  nUpProgress: 'Tiến trình',
  nUpRecipe: 'Công thức',
  nCalibrateHint:
    'Đo tiêu hao thật của bạn từ lượng ăn và biến động cân nặng, rồi đề xuất mục tiêu calo khớp với nó.',
  nRetry: 'Thử lại',
  // ── tên cho trình đọc màn hình, nút chỉ có icon ──
  a11yBack: 'Quay lại',
  a11yClose: 'Đóng',
  a11yDismiss: 'Bỏ qua',
  a11yDelete: 'Xoá',
  a11yEdit: 'Sửa',
  a11yAdd: 'Thêm',
  a11yMore: 'Thêm tuỳ chọn',
  a11yIncrease: 'Tăng',
  a11yDecrease: 'Giảm',
  a11ySettings: 'Mở cài đặt',
  a11ySearch: 'Tìm kiếm',
  a11yClearSearch: 'Xoá ô tìm kiếm',
  a11yLogMeal: 'Ghi bữa ăn',
  a11yAskCoach: 'Hỏi huấn luyện viên',
  a11yCloseCoach: 'Đóng huấn luyện viên',
  a11yFavourite: 'Bật/tắt yêu thích',
  a11yTakePhoto: 'Chụp ảnh',
  a11ySwitchCamera: 'Đổi camera',
  a11yPrevWeek: 'Tuần trước',
  a11yNextWeek: 'Tuần sau',
  a11yEditGoal: 'Sửa mục tiêu',
  a11yOpenRoom: 'Mở phòng của Koa',
  a11yCheckOff: 'Đánh dấu đã dùng',
  a11yExpand: 'Xem chi tiết',
  a11ySend: 'Gửi tin nhắn',
  a11yHistory: 'Lịch sử trò chuyện',
  a11yNewChat: 'Cuộc trò chuyện mới',
  a11yShare: 'Chia sẻ',
  a11yScanFood: 'Quét món ăn bằng camera',
  a11yScanBarcode: 'Quét mã vạch',
  a11yRemove: 'Bỏ khỏi danh sách',
  editLayout: 'Sửa',
  a11yEditLayout: 'Sắp xếp lại bảng điều khiển',
  a11yDoneEditing: 'Xong sắp xếp',
  a11yAcceptTerms: 'Đồng ý điều khoản',
  a11yMoveUp: 'Chuyển lên',
  a11yMoveDown: 'Chuyển xuống',
  a11ySleepQuality: 'Chất lượng giấc ngủ {x} trên {max}',
  // ── xoá tài khoản ──
  nDeleteAccount: 'Xoá tài khoản',
  nDeleteAccountDesc: 'Xoá vĩnh viễn tài khoản và toàn bộ dữ liệu trong đó',
  nDeleteAccountTitle: 'Xoá tài khoản của bạn?',
  nDeleteAccountBody:
    'Thao tác này xoá sạch bữa ăn, buổi tập, giấc ngủ, cân nặng và tủ đồ của Koa. Không thể hoàn tác. Hãy xuất dữ liệu trước nếu bạn muốn giữ lại.',
  nDeleteAccountConfirm: 'Xoá tất cả',
  nDeleteAccountDone: 'Tài khoản của bạn đã được xoá.',
  nDeleteAccountNotSetUp: 'Máy chủ chưa bật chức năng xoá tài khoản.',
  nDeleteAccountFailed: 'Không xoá được tài khoản. Chưa có gì bị xoá.',
  nDeleteAccountPartial:
    'Không xoá được tài khoản. Ảnh tiến trình của bạn thì đã bị xoá và không khôi phục được — hãy thử lại để xoá nốt tài khoản.',
  a11yPrevItem: 'Món trước',
  a11yNextItem: 'Món sau',
  a11yAddWater: 'Thêm {x} {unit}',
  // ── lịch sử cân nặng và sửa sai ──
  nWeightHistory: 'Cân nặng đã ghi',
  nWeightEntries: '{n} lần',
  nWeightEntriesOne: '1 lần',
  nWeightSeeAll: 'Xem tất cả {n} lần ghi',
  nHeroMore: 'Xem chi tiết đầy đủ',
  nHeroDetails: 'Chi tiết {n}',
  nDeleteWeight: 'Xoá số cân này',
  nDeleteWeightMsg: 'Xoá bản ghi {x}? Biểu đồ và BMI sẽ được tính lại.',
  // ── buổi tập đã ghi và sửa sai ──
  nDeleteSession: 'Xoá buổi tập này',
  nDeleteSessionMsg: 'Xoá {x}? Khối lượng tập và điểm sẵn sàng sẽ được tính lại.',
  // AI edge functions — one message per distinct cause, so wiring a new
  // Supabase project up tells you what is missing instead of "it failed"
  aiNotDeployed: 'Tính năng AI này chưa được cài trên máy chủ.',
  aiProviderError: 'Dịch vụ AI chưa trả lời được. Thử lại sau một lát nhé.',
  aiSignedOut: 'Bạn cần đăng nhập lại để dùng tính năng AI.',
  aiOffline: 'Không có kết nối — AI cần internet.',
  aiRateLimited: 'Bạn đã dùng hết lượt AI lúc này. Thử lại sau nhé.',
  aiUnknown: 'Có lỗi khi gọi AI.',
  nDiaryLoadFailed: 'Không tải được các bữa ăn',
  nNoSupplements: 'Chưa có supplement nào',
  nNoSupplementsHint: 'Thêm stack của bạn trên bản web — checklist sẽ đồng bộ về đây',
  nExercises: 'Thư viện bài tập',
  nSearchExercises: 'Tìm bài tập…',
  nNoExercises: 'Không tìm thấy bài tập',
  nNoExercisesHint: 'Thư viện bài tập đồng bộ từ bản web',
  nRoutine: 'Lịch tập tuần',
  nPlan: 'Plan',
  nPlanNewWorkout: 'Tạo buổi tập mới',
  nTodayTraining: 'Hôm nay',
  nStartWorkout: 'Bắt đầu buổi tập',
  nTodayRest: 'Ngày nghỉ',
  nTodayRestHint: 'Nghỉ ngơi hoặc vận động nhẹ',
  nTodayNone: 'Chưa có buổi tập',
  nTodayNoneHint: 'Chọn một buổi cho hôm nay, hoặc cứ ghi lại những gì bạn tập',
  nTodayPick: 'Chọn buổi tập',
  nTodayDone: 'Đã tập hôm nay',
  nLogFree: 'Ghi buổi tập',
  nTodayExtra: 'Ghi thêm buổi phát sinh',
  nSeePlan: 'Xem kế hoạch',
  nYourWorkouts: 'Mẫu buổi tập',
  nSetsShort: 'hiệp',
  nToolsExercises: 'Thư viện bài tập',
  nToolsInsight: 'Tiến bộ từng bài',
  nLibraryHistory: 'Thư viện & lịch sử',
  nSessionCount: 'Đã ghi {n} buổi tập',
  nExerciseCount: '{n} bài',
  nAboutMinutes: '~{n} phút',
  nPlanNothingToday: 'Hôm nay chưa có kế hoạch',
  nPlanAdded: 'Đã thêm vào Plan · {d}',
  nRest: 'Nghỉ',
  nDeload: 'Deload',
  nChooseWorkout: 'Chọn buổi tập',
  nRoutineHint: 'Chạm vào một ngày để gán buổi tập, đánh dấu nghỉ, hoặc bật deload',
  nRoutineDone: 'Hoàn thành',
  nRoutineTodo: 'Chờ tập',
  nRoutineMissed: 'Chưa tập',
  nRoutineRestDay: 'Nghỉ ngơi',
  nRoutineRestHint: 'Nghỉ ngơi hoặc vận động nhẹ',
  nRoutineExercises: '{n} bài tập',
  nRoutineMinutes: '{n} phút',
  nRoutineEffort: 'RPE {x}',
  nRoutineEffortRange: 'RPE {a}–{b}',
  nRoutineToday: 'Hôm nay',
  nRoutineNoTemplates: 'Chưa lưu buổi tập nào — tạo một cái trước đã.',
  nRdSet: 'Set {n}',
  nRdProgress: '{done}/{total} set',
  nRdSetsN: '{n} hiệp',
  nRdFinish: 'Hoàn thành buổi tập',
  nRdFuture: 'Chưa tới ngày này',
  nRestNext: 'Tiếp theo',
  nRestSetOf: 'Set {n}/{t}',
  nRdAddExercise: 'Thêm bài tập',
  nRdAddSet: 'Thêm hiệp',
  nRdExtraName: 'Tên bài tập',
  nRdResting: 'Nghỉ',
  nRdSkip: 'Bỏ qua',
  nRdEmptyPlan: 'Ngày này chưa có buổi tập nào',
  nRdSaved: 'Đã ghi buổi tập',
  nRdBodyweight: 'Không tạ',
  nExKind: 'Loại động tác',
  nExKindHint: 'Nó quyết định "tiến bộ" nghĩa là gì với bài này',
  nExKindcompound: 'Nhiều nhóm cơ',
  nExKindisolation: 'Cô lập',
  nExKindbodyweight: 'Không tạ',
  nExKindtimed: 'Giữ tư thế',
  nLgWarmup: 'Set khởi động',
  nLgWarmupShort: 'K',
  nLgHoldHint: 'Bài giữ tư thế thì gõ số giây — 45s.',
  nXiTitle: 'Tiến bộ từng bài',
  nXiSubtitle: 'Từng động tác đang đi thế nào, đọc từ những gì bạn đã ghi',
  nXiEmpty: 'Chưa ghi bài tập nào trong 90 ngày qua',
  nXiEmptyHint: 'Ghi một buổi tập là mục này tự đầy lên',
  nXiSessions: '{n} buổi',
  nXiOneSession: '1 buổi',
  nXiE1rm: '1RM ước lượng',
  nXiE1rmNote: 'Ước lượng từ set tốt nhất, không phải mức bạn đã nâng thật',
  nXiBest: 'Set tốt nhất',
  nXiBodyweightUnknown: 'Đang đếm bằng số rep — chưa có lần cân nào',
  nXiScopeToday: 'Lịch hôm nay',
  nXiScopeWeek: 'Lịch tuần',
  nXiScopeAll: 'Tất cả',
  nXiScopeEmptyToday: 'Hôm nay lịch không có bài nào',
  nXiScopeUnlogged: 'Các bài trong lịch chưa có buổi nào được ghi',
  nXiScopeEmptyWeek: 'Lịch tuần của bạn chưa có bài nào',
  nXiScopeHint: 'Đặt lịch tập tuần thì mục này sẽ lọc đúng những bài bạn đang tập',
  nXiOnly: 'Đang xem một bài',
  nXiShowAll: 'Xem tất cả',
  nXiNeedsAttention: 'Đáng để ý',
  nXiGoingWell: 'Đang ổn',
  nXiNotYet: 'Cần thêm buổi',
  nXiSummary: '{a} đang tiến bộ · {b} đáng để ý',
  nXiSummaryThin: 'Chưa bài nào đủ buổi để nói được gì — {n} đang chờ',
  nXiWindowNote: 'Mọi con số trên trang này đọc từ {n} ngày gần nhất.',
  nXiTapMore: 'Chi tiết',
  nXiFootnote: '1RM ước lượng tính từ set tốt nhất của bạn. Đó là ước lượng, không phải mức bạn đã nâng thật, và chỉ tính tới 10 rep.',
  nXiAt: 'ở {w}',
  nLgLastTime: 'Lần trước {v}',
  nXiEvidence: 'Các buổi so sánh được gần đây',
  nXiLastToday: 'Tập hôm nay',
  nXiLastDays: 'Tập gần nhất {n} ngày trước',
  nXiAgoShort: '{n} ngày trước',
  nXiStale: 'Lệch so với nhịp bạn thường tập bài này — các số dưới đây nói về một khối tập bạn đã rời khỏi',
  nXiVolatile: 'Buổi kém nhất thấp hơn buổi tốt nhất {p}% — có thứ ngoài giáo án đang chi phối những con số này',
  nXiWindowWeight: 'Mức tạ tốt nhất 90 ngày: {v} {unit}, hơn mức {prev} trước đó',
  nXiWindowReps: 'Tốt nhất 90 ngày: {v} rep ở {w} {unit}, hơn {prev} trước đó',
  nXiWindowRepsBody: 'Tốt nhất 90 ngày: {v} rep, hơn {prev} trước đó',
  nXiWindowAgo: '{n} ngày trước',
  nXiNeedMore: 'Cần {n} buổi mới nói được gì',
  nXiTrendIMPROVING: 'Đang tiến bộ',
  nXiTrendSTABLE: 'Giữ vững',
  nXiTrendPLATEAU: 'Đang chững',
  nXiTrendDECLINING: 'Đang đi xuống',
  nXiTrendINSUFFICIENT_DATA: 'Chưa đủ dữ liệu',
  nXiReadyREADY_TO_PROGRESS: 'Sẵn sàng tăng',
  nXiReadyMAINTAIN: 'Giữ nguyên',
  nXiReadyNOT_READY: 'Chưa nên',
  nXiKindcompound: 'Nhiều nhóm cơ',
  nXiKindisolation: 'Cô lập',
  nXiKindbodyweight: 'Không tạ',
  nXiKindtimed: 'Giữ tư thế',
  nXiChangeUp: 'hơn {p}% so với mức tốt nhất trước đó',
  nXiChangeDown: 'kém {p}% so với mức tốt nhất trước đó',
  nXiChangeFlat: 'ngang mức tốt nhất trước đó',
  nXiNoUpward: '{n} buổi so sánh được gần nhất không cho thấy xu hướng đi lên rõ rệt',
  nXiConf: 'Độ tin cậy: {c}',
  nXiConfhigh: 'cao',
  nXiConfmedium: 'vừa',
  nXiConflow: 'thấp',
  nXiConfnone: 'không có',
  nXiOpen: 'Tiến bộ từng bài',
  /* ── Hướng dẫn bài tập ── */
  nEgTitle: 'Cách thực hiện',
  nEgOpen: 'Cách thực hiện bài này',
  nEgCues: 'Điểm kỹ thuật',
  nEgMistakes: 'Lỗi thường gặp',
  nEgEquipment: 'Dụng cụ',
  nEgMuscles: 'Nhóm cơ chính',
  nEgNoMedia: 'Chưa có hình minh hoạ',
  nEgNoMediaHint: 'Các điểm kỹ thuật bên dưới vẫn mô tả động tác',
  nEgMediaFailed: 'Không tải được hình minh hoạ',
  nEgEmpty: 'Bài này chưa có hướng dẫn',
  nEgEmptyHint: 'Hướng dẫn đến từ thư viện bài tập, và bài này chưa có',
  nEgMediaDemo: 'Hình minh hoạ tạm, không phải bản demo của bài tập này',
  nEgMediaAlt: 'Hình minh hoạ {v}',
  nEgTabOverview: 'Tổng quan',
  nEgTabMuscles: 'Cơ & dụng cụ',
  nEgTabRelated: 'Liên quan',
  nEgNoMuscles: 'Bài này chưa ghi nhóm cơ',
  nEgNoEquipment: 'Bài này chưa ghi dụng cụ',
  nEgNoRelated: 'Thư viện chưa có bài nào khác đánh vào những nhóm cơ này',
  nEgAlsoEquipment: 'Bài khác dùng {v}',
  nEgAlsoMuscles: 'Bài khác cho những nhóm cơ này',
  nEgOpenMedia: 'Mở hình minh hoạ',
  nEgStart: 'Bắt đầu bài tập',
  nRdAlready: 'Đã ghi buổi tập',
  nRdExtra: 'Tập thêm bài phát sinh? Ghi riêng tại đây',
  nRdAppend: 'Ghi thêm vào buổi hôm nay',
  nRdAppended: 'Đã ghi thêm vào buổi hôm nay',
  nRdAppendOffline: 'Cần mạng để ghi thêm vào buổi đã lưu. Tạm thời hãy ghi riêng.',
  nRdUntickTitle: 'Bỏ tích hiệp này?',
  nRdUntickMsg: 'Hiệp này đang được tích là đã xong. Bỏ tích tức là nói nó KHÔNG xảy ra, và nó sẽ không được ghi.',
  nRdUntickConfirm: 'Bỏ tích',
  nRdNeedInfo: 'Đặt tên bài và nhập số rep (hoặc số giây) rồi mới tích hoàn thành được.',
  nRdSetRemoved: 'Đã gỡ hiệp khỏi buổi tập',
  nRdLoggedAt: 'lúc {t}',
  nRdPlanToday: 'Theo lịch hôm nay',
  nRdUsePlan: 'Dùng',
  nMealPlans: 'Kế hoạch ăn',
  nMealPlanNone: 'Chưa có kế hoạch ăn nào',
  nMealPlanWhat: 'Kế hoạch ăn là vài ngày ăn được viết sẵn, để câu "hôm nay ăn gì" đã có câu trả lời từ trước.',
  nMealPlanNew: 'Tạo kế hoạch ăn',
  nMealPlanOpen: 'Mở',
  nMealsPerDay: 'bữa/ngày',
  nDay: 'Ngày',
  nNoMealPlans: 'Chưa có kế hoạch ăn',
  nMpAddFood: 'Thêm món',
  nMpStepPlanHint: 'Tên bạn sẽ gọi kế hoạch ăn này khi quay lại',
  nMpStepSlotsHint: 'Mỗi ngày trong kế hoạch ăn có mấy bữa',
  nMpPreview: 'Sẽ tạo ra',
  nMpPreviewSum: '{d} ngày · {m} bữa mỗi ngày · tổng {t} bữa',
  nMpPlanNameEg: 'VD: Meal Prep Tuần 1',
  nMpNextAddFood: 'Tạo rồi thêm món',
  nExNameHint: 'Tên bạn sẽ gõ để tìm khi thêm vào buổi tập',
  nExGroupHint: 'Bài này nằm ở nhóm nào trong thư viện',
  nExGearHint: 'Không bắt buộc — tạ đòn, tạ đơn, máy, hoặc không gì cả',
  nMpStepPlan: 'Kế hoạch',
  nMpStepDay: 'Ngày',
  nMpStepMeal: 'Bữa',
  nMpStepFood: 'Món',
  nMpStepDayHint: 'Món này thuộc ngày nào trong kế hoạch ăn',
  nMpStepMealHint: 'Bữa nào trong ngày đó',
  nMpStepFoodHint: 'Tìm rồi chạm để thêm. Bảng không đóng lại — một bữa hiếm khi chỉ có một món.',
  nMpAddTitle: 'Thêm món',
  nMpAddedN: 'Đã thêm {n}',
  nMpDone: 'Xong',
  nMpPickFood: 'Chọn món',
  nMpEmptyDay: 'Chưa có món nào',
  nMpAvgPerDay: '{x} kcal/ngày',
  nMpTarget: 'mục tiêu {x}',
  nMpPctTarget: '{p}% mục tiêu',
  nMpDayEmptyHint: 'Ngày này chưa có món nào.',
  nMpPlanEmpty: 'Kế hoạch này chưa có món nào',
  nMpWeekTotal: '{x} kcal cả tuần',
  nMpFromList: 'Từ danh sách của bạn',
  nMpNoMatch: 'Không có món nào khớp “{x}”',
  nMpAlready: 'đã thêm',
  nMpEatIt: 'Ghi vào hôm nay',
  nMpEaten: 'Có trong hôm nay',
  nMpAgainTitle: 'Hôm nay đã có rồi',
  nMpAgainBody: 'Nhật ký hôm nay đã có một bữa {m} đúng các món này. Ghi thêm lần nữa?',
  nMpAgainYes: 'Ghi thêm',
  nMpEatDone: 'Đã thêm {m} vào nhật ký hôm nay',
  nMpEatQueued: 'Đã lưu {m} — sẽ đồng bộ khi có mạng',
  nMpNoFibre: 'Ghi từ kế hoạch ăn thì không có chất xơ — kế hoạch ăn không lưu số đó.',
  // Ăn lại bữa đã ăn
  nRmTitle: 'Ăn lại bữa này',
  nRmHint: 'Điền sẵn vào form — xem lại rồi lưu.',
  nRmYesterday: 'hôm qua',
  nRmToday: 'hôm nay',
  nRmDaysAgo: '{n} ngày trước',
  nRmFoods: '{n} món',
  nWeeklyReview: 'Tổng kết tuần',
  nAiAnalysis: 'Phân tích AI',
  nWeeklyReviewHint: 'Để AI phân tích tuần của bạn và đưa gợi ý cho tuần tới',
  nAnalyzeWeek: 'Phân tích với AI',
  nWeekScore: 'Điểm tuần',

  nMascotTitle: 'Bạn đồng hành',
  nMascotToggleHint: 'Linh vật sẽ nhắc bạn dựa trên dữ liệu hôm nay',
  nMusicLabel: 'Nhạc',
  nKoaCompanionTitle: 'Koa đi cùng bạn',
  nKoaCompanionHint: 'Koa đứng cạnh bạn ở mọi màn và đổi chỗ theo diễn biến trong ngày. Tắt đi thì Koa chỉ ở lại màn Hôm nay.',
  nMascotRoomTitle: 'Phòng bạn đồng hành, cửa hàng & thử thách',
  errOffline: 'Không có kết nối — thay đổi chưa được lưu. App sẽ gửi lại khi bạn online.',
  errOnlineOnly: 'Không có kết nối — chưa gửi, và không giữ lại để gửi sau.',
  errSignedOut: 'Phiên đăng nhập đã hết hạn. Hãy đăng nhập lại rồi thử lần nữa.',
  errDuplicate: 'Mục này đã được lưu rồi — không cần thêm lần nữa.',
  errInvalid: 'Giá trị này chưa lưu được. Kiểm tra lại rồi thử lần nữa.',
  errNotFound: 'Mục này không còn ở đây. Tải lại rồi xem lại giúp bạn nhé.',
  errServer: 'Máy chủ đang gặp sự cố. Không mất gì cả — thử lại sau một chút.',
  errUnknown: 'Chưa lưu được. Thử lại sau một chút.',
  nStreakFreezeFailed: 'Chưa dùng được bảo hiểm chuỗi — app sẽ thử lại lần mở tới',
  nMascotSleep: 'Chào buổi sáng! Đêm qua ngủ sao rồi? Ghi lại để mình tính điểm sẵn sàng nhé 😴',
  nMascotMeal: 'Hôm nay chưa ghi bữa nào — nạp năng lượng rồi ghi lại nha! 🍽',
  nMascotWater: 'Kiểm tra nước nè — bạn mới uống chưa được nửa mục tiêu 💧',
  nMascotWorkout: 'Giờ này tập là đẹp đó. Sẵn sàng chưa? 💪',
  nMascotPraise: 'Hôm nay bạn làm tốt lắm. Giữ vững phong độ nha! 🔥',
  nMascotHello: 'Mình đang theo dõi chỉ số của bạn — ghi gì đó đi, mình cổ vũ!',
  // ── Koa naming what you did, then what is left ──
  // Short on purpose: the two get joined into one speech bubble, and a bubble
  // people actually read is one line.
  nMascotWinSleep: 'Ghi giấc ngủ rồi 😴',
  nMascotWinMeal: 'Có ghi bữa rồi 🍽',
  nMascotWinWater: 'Đủ nước rồi 💧',
  nMascotWinWorkout: 'Tập xong rồi 💪',
  nMascotGapSleep: 'ghi thêm đêm qua nữa nhé',
  nMascotGapMeal: 'ghi bữa ăn nữa nha',
  nMascotGapWater: 'uống thêm nước đi',
  nMascotGapWorkout: 'tập một buổi nữa là đẹp',
  nMascotThen: '{win} — {gap}',
  nMascotLocked: 'Chưa mở khoá',
  nMascotPro: 'PRO · sắp ra mắt',
  nMascotUnlockedBadge: 'Đã mở khoá',
  nMascotUnlockedTitle: 'Mở khoá nhân vật mới!',
  nMascotUse: 'Dùng ngay',
  nMascotLater: 'Để sau',

  nCameraNeeded: 'Cần quyền camera',
  nCameraHint: 'ASCND quét mã vạch để ghi thực phẩm đóng gói tức thì',
  nAllowCamera: 'Cho phép Camera',
  nPointBarcode: 'Hướng camera vào mã vạch',
  nLookingUp: 'Đang tra cứu sản phẩm…',
  nNotFound: 'Không tìm thấy — thử lại',

  // AI food scan
  nScanFood: 'Quét món ăn',
  nAiScanTitle: 'Quét món bằng AI',
  nScanModeFood: 'Món ăn',
  nScanModeLabel: 'Nhãn',
  nScanFoodHint: 'Hướng vào bữa ăn rồi nhấn chụp',
  nScanLabelHint: 'Đưa bảng thành phần dinh dưỡng vào khung',
  nAnalyzing: 'Đang phân tích…',
  nScanNoFood: 'Không nhận ra món ăn — thử lại',
  nScanFromPhoto: 'Ước tính từ ảnh — khẩu phần là phỏng đoán. Kiểm lại trước khi thêm.',
  nScanFromLabel: 'Đọc từ bảng dinh dưỡng.',
  nScanRetake: 'Chụp lại',
  nScanAdd: 'Thêm {n} món',
  nScanAddOne: 'Thêm 1 món',
  nRetake: 'Chụp lại',
  nScanError: 'Quét thất bại — thử lại',

  nLegal: 'Chính sách & Pháp lý',
  nTemplates: 'Mẫu buổi tập',
  nTemplateName: 'Tên mẫu',
  nCreateExercise: 'Bài tập mới',
  nMuscleGroup: 'Nhóm cơ',
  nEquipment: 'Dụng cụ',
  nExerciseName: 'Tên bài tập',
  nNoExercisesFound: 'Không tìm thấy bài tập',
  nSuggestions: 'Gợi ý',
  nRestSec: 'Nghỉ',
  nDeleteTemplate: 'Xoá mẫu này?',

  // Workout builder — the two-step flow
  nWbTitle: 'Buổi tập mới',
  nWbStepPick: 'Chọn bài tập',
  nWbStepReview: 'Số set & tên',
  nWbPickHint: 'Chạm vào bài bạn muốn tập. Số set và rep chỉnh ở bước sau.',
  nWbAll: 'Tất cả',
  nWbSelected: 'Đã chọn {n}',
  nWbNext: 'Tiếp',
  nWbNoMatch: 'Không có bài nào khớp “{x}”',
  nWbCreateNamed: 'Tạo “{x}”',
  nWbLibraryEmpty: 'Thư viện bài tập đang trống',
  nWbAddMore: 'Thêm bài tập',
  nWbSummary: '{n} bài · {s} set · khoảng {m} phút',
  nWbNameHint: 'Tên đặt theo nhóm cơ bạn chọn — đổi lại nếu muốn.',
  nWbNameOne: 'Tập {x}',
  nWbNameTwo: '{a} & {b}',
  nWbType: 'Kiểu buổi tập',
  nWbSave: 'Lưu buổi tập',
  nWbSets: 'Số set',
  nWbReps: 'Số rep',
  nWbLoad: 'Mức tạ',
  nWbBodyweight: 'Không tạ',
  nWbRest: 'Nghỉ giữa các set',
  nWbEffort: 'Độ gắng sức',
  nWbEffortHint: 'Rep cuối nên nặng cỡ nào. 10 là hết sức.',

  // Saved workout card — rest and effort read back
  nTplRest: 'Nghỉ {x}',
  nTplNoRest: 'Không nghỉ',
  nTplEffort: 'Gắng sức {x}/10',
  nWbMoveUp: 'Đưa lên trước',
  nWbMoveDown: 'Đưa xuống sau',
  nWbRemove: 'Bỏ khỏi buổi tập',
  nWbDone: 'Xong',
  nWbTypePush: 'Đẩy',
  nWbTypePull: 'Kéo',
  nWbTypeLegs: 'Chân',
  nWbTypeUpper: 'Thân trên',
  nWbTypeLower: 'Thân dưới',
  nWbTypeFullBody: 'Toàn thân',
  nWbTypeStrength: 'Sức mạnh',
  nWbTypeHypertrophy: 'Phì đại cơ',
  nWbTypeCardio: 'Cardio',
  nWbTypeCustom: 'Tuỳ chỉnh',

  // Water & Steps detail
  nWaterTitle: 'Nước uống',
  nStepsTitle: 'Bước chân',
  nLast7Days: '7 ngày qua',
  nAverage: 'Trung bình',
  nRangeWeek: 'Tuần',
  nRangeMonth: 'Tháng',
  nRangeYear: 'Năm',
  nRangeAll: 'Tất cả',
  nDailyAvg: 'Trung bình ngày',
  nTodayTotal: 'Hôm nay',
  nTodayLogs: 'Nhật ký hôm nay',
  nStepsGoal: 'Mục tiêu {x}',
  nQuickAdd: 'Thêm nhanh',
  // manual entry, for the amounts the presets do not cover
  nWaterCustom: 'Lượng khác',
  nWaterEntries: '{n} lần',
  nWaterEntriesOne: '1 lần',
  nWaterCustomTitle: 'Bạn đã uống bao nhiêu?',
  nWaterTooMuch: 'Nhiều hơn {x} trong một lần — kiểm tra lại số nhé',

  // Progress photos
  nPhotoFront: 'Trước',
  nPhotoSide: 'Nghiêng',
  nPhotoBack: 'Sau',
  nPhotoUploading: 'Đang tải lên…',
  nPhotoDelete: 'Xoá ảnh?',
  nPhotoAdd: 'Thêm ảnh tiến trình',
  nPhotoCapture: 'Chụp',

  // Today's diary — collapsed meal cards + quick stats
  nDiaryItems: '{n} món',
  nDiaryItemsOne: '1 món',
  nDiaryEntries: '{n} bữa',

  // A day that is not today — the `/diary` screen
  nDiaryOtherDays: 'Ngày khác',
  nDiaryTitle: 'Nhật ký bữa ăn',
  nDiaryToday: 'Hôm nay',
  nDiaryYesterday: 'Hôm qua',
  nDiaryPrevDay: 'Ngày trước',
  nDiaryNextDay: 'Ngày sau',
  nDiaryDayTotal: 'Tổng cả ngày',
  nDiaryAddMeal: 'Ghi một bữa cho ngày này',
  // editing what is already logged
  nItemEdit: 'Sửa khẩu phần',
  nItemDelete: 'Xoá khỏi nhật ký',
  nItemDeleteMsg: 'Xoá {name} khỏi nhật ký hôm nay?',
  nItemDeleteMsgDay: 'Xoá {name} khỏi nhật ký ngày này?',
  nMealSwipeAdd: 'Thêm',
  nMealSwipeDelete: 'Xoá',
  nMealDeleteTitle: 'Xoá {meal}?',
  nMealDeleteMsg: 'Thao tác này xoá cả {n} món đã ghi trong {meal} hôm nay.',
  nMealDeleteMsgDay: 'Thao tác này xoá cả {n} món đã ghi trong {meal} ngày này.',
  nItemServings: 'Khẩu phần',
  nServingsMore: 'Tăng khẩu phần',
  nServingsLess: 'Giảm khẩu phần',
  nItemUpdated: 'Đã cập nhật nhật ký',
  nUndo: 'Hoàn tác',
  nItemRestored: 'Đã lấy lại',
  nQuickCalories: 'Calo',
  nQuickProtein: 'Protein',
  nQuickWater: 'Nước',

  // Weight changes card (Progress)
  nWeightChanges: 'Thay đổi cân nặng',
  nWcDays: '{n} ngày',
  nWcAllTime: 'Toàn bộ',
  nWcNoChange: 'Không đổi',
  nWcIncrease: 'Tăng',
  nWcDecrease: 'Giảm',
  nWcNoData: 'Ghi cân nặng để xem thay đổi ở đây',

  // Weight goal (Progress weight chart)
  nQuickActions: 'Thao tác nhanh',
  nHealthAssistant: 'Trợ lý sức khoẻ',
  nQuickActionsClose: 'Đóng thao tác nhanh',
  nWeightGoal: 'Mục tiêu',
  nWeightGoalUnset: 'Chưa đặt',
  nWeightGoalTitle: 'Cân nặng mục tiêu',
  nWeightGoalEdit: 'Sửa mục tiêu cân nặng',
  nWeightGoalDone: 'Xong',
  nWeightGoalGain: 'Tăng cân',
  nWeightGoalLose: 'Giảm cân',
  nWeightGoalMaintain: 'Giữ cân',
  nWeightGoalClear: 'Xoá',
  nWeightGoalToGo: 'còn {x}',
  nWeightGoalReached: 'Đã đạt mục tiêu',

  // Bốn cách ghi một bữa ăn — xem chú thích ở bản tiếng Anh
  nWayPhoto: 'Chụp ảnh',
  nWayBarcode: 'Mã vạch',
  nWaySearch: 'Tìm món',
  nWayManual: 'Nhập tay',
  nAddCamera: 'Quét bữa ăn',
  nAddBarcode: 'Quét mã vạch',
  nAddSearch: 'Tìm thực phẩm',
  nAddManual: 'Nhập tay số liệu',

  // Meal builder
  nMealItems: 'Các món',
  nMealNoItems: 'Tìm, quét hoặc thêm món để bắt đầu',
  nNutritionTotal: 'Tổng dinh dưỡng',
  nServings: 'Khẩu phần',
  nAiSuggest: 'AI gợi ý',
  nAiSuggestTitle: 'AI gợi ý bữa ăn',
  nAiSuggestHint: 'Dựa trên lượng macro còn lại hôm nay',
  nAiThinking: 'Đang nghĩ món…',
  nAddThis: 'Thêm',
  nPrepTime: '{n} phút',
  nAiNoIdeas: 'Chưa có gợi ý — thử lại sau',

  // Reminders (local notifications)
  nRemindersTitle: 'Nhắc nhở',
  nRemindersDesc: 'Nhắc mỗi ngày để giữ chuỗi thói quen',
  nRemindersEnable: 'Cho phép thông báo',
  nRemindersDenied: 'Thông báo đang tắt. Bật trong Cài đặt iOS › ASCND.',
  nReminderWater: 'Uống nước',
  nReminderWaterBody: 'Đến giờ uống một cốc nước rồi 💧',
  nReminderSupplements: 'Thực phẩm bổ sung',
  nReminderSupplementsBody: 'Nhớ uống thực phẩm bổ sung 💊',
  nReminderBedtime: 'Chuẩn bị ngủ',
  nReminderBedtimeBody: 'Sắp đến giờ ngủ — thư giãn thôi 😴',
  nReminderWeighIn: 'Cân buổi sáng',
  nReminderWeighInBody: 'Ghi cân nặng trước bữa sáng ⚖️',
  nReminderWorkout: 'Tập hôm nay',
  nReminderWorkoutBody: 'Lịch của bạn có buổi tập hôm nay 💪',
  nReminderMeal: 'Ghi bữa ăn',
  nReminderMealBody: 'Hôm nay chưa ghi bữa nào — bạn đã ăn gì? 🍽',
  nReminderBiometrics: 'Số đo buổi sáng',
  nReminderBiometricsBody: 'Nhịp tim nghỉ và HRV, trước khi rời giường ❤️',
  nReminderSleepLog: 'Ghi đêm qua',
  nReminderSleepLogBody: 'Đêm qua ngủ thế nào? Ghi lại nhé 🌙',
  nTodoRemindAt: 'Nhắc lúc',
  nTodoSetReminder: 'Hẹn giờ',
  nTodoReminderOff: 'Tắt nhắc',
  nReminderTime: 'Giờ',
  nReminderEveryHours: 'Mỗi {n} giờ',

  // Offline
  nOffline: 'Ngoại tuyến — đang hiển thị dữ liệu đã lưu',
  nReconnecting: 'Đang kết nối lại — app đang tải phần đã lỡ',
  nLoadingData: 'Đang tải dữ liệu của bạn',
  nHealthSynced: 'Đã đồng bộ Apple Health!',

  // Mascot room
  nRoomQuests: 'Nhiệm vụ hôm nay',
  nRoomQuestsHint: 'Tập, ăn, uống nước — kiếm xu cho bạn đồng hành',
  nRoomWeeklyBonus: 'Thưởng thử thách tuần',
  nRoomShop: 'Cửa hàng',
  nRoomDressing: 'Phòng thay đồ',
  nRoomOverview: 'Toàn cảnh',
  nRoomOverviewHint: 'Chọn một góc phòng ở trên.',
  nRoomOutfits: 'Trang phục',
  nRoomCloset: 'Tủ đồ',
  nRoomGymGear: 'Đồ phòng gym',
  nRoomStageSkins: 'Sân khấu',
  nRoomUse: 'Dùng',
  nRoomUsing: 'Đang dùng',
  nRoomClaim: 'Nhận',
  nRoomClaimed: 'Đã nhận',
  nRoomBuy: 'Mua',
  nRoomWear: 'Mặc',
  nRoomTakeOff: 'Cởi',
  nRoomWearing: 'Đang mặc',
  nRoomPlaced: 'Đã đặt trong phòng',
  nRoomPlace: 'Đặt vào',
  nRoomAll: 'Tất cả',
  nRoomOwned: 'Đã sở hữu',
  nRoomLockLevel: 'Lv.{n}',
  nRoomCollections: 'Bộ sưu tập',
  nRoomCollectionsHint: 'Thu thập đủ bộ để nhận thưởng đặc biệt!',
  nRoomSetProgress: 'Đã có {a}/{b}',
  nRoomSetDone: 'Đủ bộ!',
  nRoomEmptyCat: 'Sắp có thêm đồ',
  nRoomEmptyCloset: 'Tủ đồ còn trống — chọn một món ở tab Trang phục nhé',
  nRoomGoToOutfits: 'Xem trang phục',
  nRoomSetClaimed: 'Đã nhận thưởng',
  nRoomNotEnough: 'Chưa đủ xu — hoàn thành thêm nhiệm vụ nhé!',
  nShopOffline: 'Cửa hàng cần mạng — xu được trừ ở máy chủ.',
  nRoomCoins: 'xu',
  nRoomEarned: '+{n} xu!',
  nRoomBought: 'Đã mua!',
  nRoomUpgrades: 'Nâng cấp phòng',
  nRoomInstalled: 'Đã lắp đặt',
  nRoomStreak: 'Chuỗi {n} ngày',
  nRoomLearned: 'Koa để ý: bạn thường ghi {what} vào khoảng {time}',
  nKoaPraiseSmall: 'Ngon.',
  nKoaPraiseBig: 'Cái này đáng kể đấy. Giỏi lắm.',
  nKoaProudRecord: 'Đó là lần khoẻ nhất của bạn từ trước tới giờ.',
  nKoaWelcomeBack: 'Gặp lại bạn rồi. Mình bắt đầu lại nhé.',
  nKoaStreakSaved: 'Ngày đó mình bù cho bạn rồi — chuỗi vẫn còn.',
  nKoaStreakRisk: 'Vẫn còn kịp giữ chuỗi tối nay.',
  nKoaDayComplete: 'Xong cả năm việc. Hôm nay ổn đấy.',
  nPrTitle: 'Kỷ lục mới',
  nPrTitleMany: '{n} kỷ lục mới',
  nPrWeightLine: '{ex} — {value} {unit}, trước là {prev}',
  nPrRepsLine: '{ex} — {value} lần ở {w} {unit}, trước là {prev}',
  nPrRepsBodyLine: '{ex} — {value} lần, trước là {prev}',
  nPrFirstLoad: '{ex} — {value} {unit}, lần đầu có tạ',
  nPrContinue: 'Chạm để tiếp tục',
  nSmartFrom: 'Koa để ý: {what}',
  nSmartBedtime: 'bạn đi ngủ lúc {t}',
  nSmartWake: 'bạn dậy lúc {t}',
  nSmartWorkout: 'bạn thường ghi buổi tập quanh {t}',
  nSmartMove: 'Nhắc lúc {t}',
  nSmartMoved: 'Đã chuyển sang {t}',
  nFreezeTitle: 'Bảo hiểm chuỗi',
  nFreezeHeld: 'Đang có {n}/{max}',
  nFreezeHint: 'Tự bù một ngày lỡ. Koa chỉ dùng khi nó thật sự cứu được chuỗi.',
  nFreezeBuy: 'Mua · {n}',
  nFreezeFull: 'Đã đầy',
  nFreezeSaved: 'Đã bù {n} ngày',
  nFreezeSavedPlural: 'Đã bù {n} ngày',
  nThingMeal: 'bữa ăn',
  nThingWorkout: 'buổi tập',
  nThingWater: 'nước uống',
  nThingSleep: 'giấc ngủ',
  nThingSteps: 'bước chân',
  nStreakLit: 'Chuỗi {n} ngày, hôm nay đã ghi',
  nStreakAtRisk: 'Chuỗi {n} ngày, hôm nay chưa ghi gì',
  nStageStreak: 'Ngày streak',
  nStageQuests: 'Nhiệm vụ',
  nRoomLevel: 'Cấp {n}',
  nRoomLevelHint: 'Còn {n} XP tới cấp tiếp theo',
  nRoomLevelUp: 'Lên cấp! Bạn đồng hành đạt cấp {n}',
  nRoomMoodTired: 'Hôm nay tớ uể oải quá… ghi một bữa ăn hoặc tập một chút cho tớ tỉnh nhé!',
  nRoomWardrobe: 'Tủ đồ',
  nRoomChangeBuddy: 'Đổi linh vật',
  nRoomWelcome: 'Quà chào mừng: +{n} xu!',
  // Rank ladder
  nRoomNextRank: 'Tiếp theo: {r} ở cấp {n}',
  nRoomMaxRank: 'Đã đạt danh hiệu cao nhất — huyền thoại!',
  nRoomRankUp: 'Mở danh hiệu mới: {r}!',
  nRoomJourney: 'Hành trình',
  nRoomLevelsToRank: 'Còn {n} cấp tới {r}',
  // Today's energy
  nRoomEnergy: 'Năng lượng hôm nay',
  nRoomEnergyEmpty: 'Đang cạn năng lượng — ghi bữa ăn hoặc buổi tập để đánh thức tớ nhé.',
  nRoomEnergyLow: 'Vừa khởi động — tiếp tục nào!',
  nRoomEnergyMid: 'Đang khoẻ dần — còn vài mục nữa thôi.',
  nRoomEnergyFull: 'Nạp đầy năng lượng! Hoàn thành mọi mục tiêu hôm nay.',
  nRoomSigMeal: 'Ăn',
  nRoomSigWorkout: 'Tập',
  nRoomSigWater: 'Nước',
  nRoomSigSleep: 'Ngủ',
  nRoomSigSteps: 'Bước',

  // App lock (Face ID / sinh trắc)
  nLockTitle: 'Khoá ứng dụng',
  nLockDesc: 'Yêu cầu Face ID để mở ASCND',
  nLockUnavailable: 'Thiết bị không hỗ trợ khoá sinh trắc',
  nLockPrompt: 'Mở khoá ASCND',
  nLockLocked: 'ASCND đang khoá',
  nLockUnlock: 'Mở khoá',

  /* ── Cộng đồng · bài RECIPE (#7, người làm: B) — xem khối tiếng Anh. ── */
  nRcRecipe: 'Công thức',
  nRcGrams: '{n} g',
  nRcMoreIngredients: '+ {n} nguyên liệu khác',
  nRcAddToMeal: 'Thêm vào bữa ăn',
  nRcAddWhich: 'Thêm vào bữa nào hôm nay?',
  nRcAdded: 'Đã thêm vào hôm nay · {meal}',
  nRcAddedQueued: 'Đã lưu vào hôm nay · {meal} — sẽ đồng bộ khi có mạng',
  nRcShareText: '{title} trên ASCND — {kcal} kcal',
  nRcShareTitle: 'Chia sẻ công thức',
  nRcPickMeal: 'Chọn một bữa bạn đã ghi',
  nRcNoMeals: 'Chưa có bữa nào trong 30 ngày qua',
  nRcItems: '{n} món',
  nRcName: 'Tên món',
  nRcNamePh: 'Ví dụ: Cơm gà nhiều đạm',
  nRcNameNeeded: 'Đặt tên cho món trước đã',
  nRcCaptionPh: 'Món này ngon ở chỗ nào?',
  nRcPrivacyNote: 'Chỉ bữa này được chia sẻ — các món, khối lượng và tổng. Phần còn lại của nhật ký vẫn riêng tư.',
  nRcAlreadyShared: 'Bữa này đã được chia sẻ',
  nRcEmptyMeal: 'Bữa này không có món nào để chia sẻ',
  nRcAsk: 'Một công thức',

  /* ── Cộng đồng · Thư viện Đã lưu (#10, người làm: B) ── */
  nSvTitle: 'Đã lưu',
  nBdTitle: 'Huy hiệu thử thách',
  nBdHint: 'Hiện các thử thách bạn đã hoàn thành trên hồ sơ cộng đồng. Tắt thì không ai thấy — kể cả trên hồ sơ của chính bạn.',
  nBdHide: 'Ẩn',
  nBdShow: 'Hiện',
  nBdA11y: 'Huy hiệu: {title}',
  nSvSaved: 'Đã lưu vào thư viện',
  nSvOpen: 'Xem thư viện',
  nSvWorkouts: 'Buổi tập',
  nSvRecipes: 'Công thức',
  nSvAll: 'Tất cả',
  nSvEmpty: 'Chưa lưu bài nào',
  nSvEmptyHint: 'Chạm biểu tượng Lưu trên một bài để giữ nó ở đây.',
  nSvEmptyWorkouts: 'Chưa lưu buổi tập nào',
  nSvEmptyRecipes: 'Chưa lưu công thức nào',
};

export const nativeStrings: Record<AppLang, typeof en> = { vi, en };
export type NativeStrings = typeof en;
