import type { AppLang } from './i18n';

/**
 * Strings specific to the native app's screens, in both languages.
 * The big ported dictionary (i18n.ts) covers web-page copy; these cover
 * the native layouts. Merged with it in useI18n().
 */
const en = {
  // Today
  nGoodMorning: 'Good morning',
  nGoodAfternoon: 'Good afternoon',
  nGoodEvening: 'Good evening',
  nReadiness: 'Readiness',
  nReadinessHint: 'Log sleep and training to get your score',
  nActivity: 'Activity',
  nSteps: 'steps',
  nKcalToday: 'kcal today',
  nSleep: 'Sleep',
  nLastNight: 'Last night',
  nWater: 'Water',
  nStayHydrated: 'stay hydrated',
  nOfTarget: 'of {x} target',
  nSyncHealth: 'Sync Apple Health',
  nLogShort: 'Log',
  nQuality: 'Quality',

  // Nutrition
  nToday: 'Today',
  nProtein: 'Protein',
  nCarbs: 'Carbs',
  nFat: 'Fat',
  nLogMealBtn: 'Log Meal',
  nNoMeals: 'No meals yet',
  nNoMealsHint: 'Log your first meal of the day above',
  nBreakfast: 'Breakfast',
  nLunch: 'Lunch',
  nDinner: 'Dinner',
  nSnack: 'Snack',
  nPreWorkout: 'Pre-workout',
  nPostWorkout: 'Post-workout',
  nFavorites: 'Favorites',
  nRecent: 'Recent',

  // Workouts
  nThisWeek: 'This week',
  nSessions: 'sessions',
  nVolume: 'Volume',
  nKgLifted: 'kg lifted',
  nLogWorkoutBtn: 'Log Workout',
  nNoWorkouts: 'No workouts yet',
  nNoWorkoutsHint: 'Log your first session — readiness adapts to your training load',

  // Progress
  nWeight: 'Weight',
  nLast30d: 'Last 30 days',
  nLast14d: 'Last 14 days',
  nNotEnoughData: 'Not enough data yet',
  nBuildTrendHint: 'Log sleep and training to build your trend',

  // Log Meal sheet
  nLogMealTitle: 'Log Meal',
  nSearchFoods: 'Search foods…',
  nWhatDidYouEat: 'What did you eat? (optional)',
  nCalories: 'Calories (kcal)',
  nProteinG: 'Protein g',
  nCarbsG: 'Carbs g',
  nFatG: 'Fat g',
  nSaveMeal: 'Save Meal',

  // Log Workout sheet
  nLogWorkoutTitle: 'Log Workout',
  nWorkoutName: 'Workout name (e.g. Push Day)',
  nSets: 'Sets',
  nExercise: 'Exercise',
  nReps: 'reps',
  nAddSet: 'Add set',
  nRpe: 'Session effort (RPE)',
  nSaveWorkout: 'Save Workout',

  // Log Sleep sheet
  nLogSleepTitle: 'Log Sleep',
  nBedtime: 'Bedtime',
  nWakeUp: 'Wake up',
  nDuration: 'Duration',
  nHowSleep: 'How did you sleep?',
  nSaveSleep: 'Save Sleep',

  // Settings
  nDailyTarget: 'Daily target',
  nGoal: 'Goal',
  nTrainingLevel: 'Training level',
  nAbout: 'About',
  nVersion: 'Version',
  nSignOut: 'Sign Out',
  nSignOutConfirm: 'Are you sure you want to sign out?',
  nCancel: 'Cancel',

  // Auth
  nSignInSubtitle: 'Sign in to continue',
  nSignUpSubtitle: 'Create your account',
  nYourName: 'Your name',
  nEmail: 'Email',
  nPassword: 'Password',
  nSignIn: 'Sign In',
  nSignUp: 'Sign Up',
  nNoAccount: "Don't have an account? ",
  nHaveAccount: 'Already have an account? ',

  // AI Coach
  nAskCoach: 'Ask your coach',
  nAskCoachHint: 'Training, nutrition, recovery — answers use your real data',
  nMessageCoach: 'Message your coach…',
  nHistory: 'History',
  nNoHistory: 'No conversations yet',

  // Extras
  nAwards: 'Awards',
  nNoAwards: 'No awards yet',
  nNoAwardsHint: 'Keep logging — achievements unlock automatically',
  nChallenges: 'Challenges',
  nNoChallenges: 'No challenges this week',
  nNoChallengesHint: 'Weekly challenges appear when you start logging',
  nCompleted: 'Completed',
  nChallengeDone: 'Challenge complete',
  nGrocery: 'Grocery List',
  nAddItem: 'Add an item…',
  nNoGrocery: 'List is empty',
  nNoGroceryHint: 'Add ingredients you need to buy',

  // Library screens
  nSupplements: 'Supplements',
  nTakenToday: 'taken today',
  nWeightTitle: 'Weight check-in',
  nLogWeight: 'Log',
  nAllSupplementsDone: 'All done for today',
  nReadinessTrend: 'Readiness trend',
  nSmartTips: 'Smart tips',
  nTipsHint: 'AI insights from your recent data',
  nTipsLoading: 'Reading your trends…',
  nTipsRefresh: 'Refresh',
  nTipsEmpty: 'Log more to unlock tips',
  nNoSupplements: 'No supplements yet',
  nNoSupplementsHint: 'Add your stack in the web app — the checklist syncs here',
  nExercises: 'Exercise Library',
  nSearchExercises: 'Search exercises…',
  nNoExercises: 'No exercises found',
  nNoExercisesHint: 'Your exercise library syncs from the web app',
  nRoutine: 'Weekly Routine',
  nRest: 'Rest',
  nDeload: 'Deload',
  nChooseWorkout: 'Choose workout',
  nRoutineHint: 'Tap a day to assign a workout, mark rest, or set deload',
  nMealPlans: 'Meal Plans',
  nMealsPerDay: 'meals/day',
  nDay: 'Day',
  nNoMealPlans: 'No meal plans yet',
  nNoMealPlansHint: 'Create a plan in the web app — it appears here',
  nWeeklyReview: 'Weekly Review',
  nAiAnalysis: 'AI Analysis',
  nWeeklyReviewHint: 'Let AI analyze your week and give recommendations for the next one',
  nAnalyzeWeek: 'Analyze with AI',
  nWeekScore: 'Week score',

  // Mascot
  nMascotTitle: 'Companion',
  nMascotToggleHint: 'Your companion nudges you based on today\u2019s data',
  nMascotSleep: 'Morning! How did you sleep? Log it so I can compute your readiness 😴',
  nMascotMeal: 'No meals logged yet today — fuel up and log it! 🍽',
  nMascotWater: 'Hydration check — you\u2019re under half your water target 💧',
  nMascotWorkout: 'Great window for a workout right now. Ready when you are 💪',
  nMascotPraise: 'You\u2019re crushing it today. Keep the streak alive! 🔥',
  nMascotHello: 'I\u2019m watching your stats — log something and I\u2019ll cheer you on!',
  nMascotLocked: 'Locked',
  nMascotPro: 'PRO · coming soon',
  nMascotUnlockedBadge: 'Unlocked',
  nMascotUnlockedTitle: 'New companion unlocked!',
  nMascotUse: 'Use now',
  nMascotLater: 'Later',

  // Scanner
  nCameraNeeded: 'Camera access needed',
  nCameraHint: 'ASCND scans barcodes to log packaged foods instantly',
  nAllowCamera: 'Allow Camera',
  nPointBarcode: 'Point at a barcode',
  nLookingUp: 'Looking up product…',
  nNotFound: 'Product not found — try again',

  // AI food scan
  nScanFood: 'Scan food',
  nAiScanTitle: 'AI Food Scan',
  nScanModeFood: 'Dish',
  nScanModeLabel: 'Label',
  nScanFoodHint: 'Point at your meal and tap the shutter',
  nScanLabelHint: 'Frame the nutrition facts panel',
  nAnalyzing: 'Analyzing…',
  nScanNoFood: 'No food detected — try again',
  nScanRetake: 'Retake',
  nScanAdd: 'Add {n} items',
  nScanAddOne: 'Add 1 item',
  nRetake: 'Retake',
  nScanError: 'Scan failed — try again',

  nLegal: 'Policies & Legal',
  nTemplates: 'Templates',
  nTemplateName: 'Template name',
  nCreateExercise: 'New exercise',
  nMuscleGroup: 'Muscle group',
  nEquipment: 'Equipment',
  nExerciseName: 'Exercise name',
  nNoExercisesFound: 'No exercises found',
  nSuggestions: 'Suggestions',
  nRestSec: 'Rest',
  nDeleteTemplate: 'Delete template?',

  // Water & Steps detail
  nWaterTitle: 'Hydration',
  nStepsTitle: 'Steps',
  nLast7Days: 'Last 7 days',
  nDailyAvg: 'Daily average',
  nTodayTotal: 'Today',
  nTodayLogs: 'Today’s log',
  nStepsGoal: 'Goal {x}',
  nQuickAdd: 'Quick add',

  // Progress photos
  nPhotoFront: 'Front',
  nPhotoSide: 'Side',
  nPhotoBack: 'Back',
  nPhotoUploading: 'Uploading…',
  nPhotoDelete: 'Delete photo?',
  nPhotoAdd: 'Add progress photo',
  nPhotoCapture: 'Capture',

  // Meal builder
  nMealItems: 'Items',
  nMealNoItems: 'Search, scan, or add a food to start',
  nNutritionTotal: 'Nutrition total',
  nServings: 'Servings',
  nAiSuggest: 'AI suggest',
  nAiSuggestTitle: 'AI Meal Ideas',
  nAiSuggestHint: 'Based on your remaining macros today',
  nAiThinking: 'Cooking up ideas…',
  nAddThis: 'Add',
  nPrepTime: '{n} min',
  nAiNoIdeas: 'No suggestions right now — try later',

  // Reminders (local notifications)
  nRemindersTitle: 'Reminders',
  nRemindersDesc: 'Daily nudges to keep your streak',
  nRemindersEnable: 'Allow notifications',
  nRemindersDenied: 'Notifications are off. Enable them in iOS Settings › ASCND.',
  nReminderWater: 'Drink water',
  nReminderWaterBody: 'Time for a glass of water 💧',
  nReminderSupplements: 'Supplements',
  nReminderSupplementsBody: 'Take your supplements 💊',
  nReminderBedtime: 'Wind down',
  nReminderBedtimeBody: 'Bedtime soon — start winding down 😴',
  nReminderWeighIn: 'Morning weigh-in',
  nReminderWeighInBody: 'Log your weight before breakfast ⚖️',
  nReminderWorkout: 'Train today',
  nReminderWorkoutBody: 'Your plan has a session scheduled 💪',
  nReminderTime: 'Time',
  nReminderEveryHours: 'Every {n}h',

  // Offline
  nOffline: 'Offline — showing saved data',
  nHealthSynced: 'Apple Health synced!',

  // Mascot room
  nRoomQuests: 'Daily quests',
  nRoomQuestsHint: 'Train, eat, hydrate — earn coins for your buddy',
  nRoomWeeklyBonus: 'Weekly challenge bonus',
  nRoomShop: 'Shop',
  nRoomOutfits: 'Outfits',
  nRoomGymGear: 'Gym gear',
  nRoomClaim: 'Claim',
  nRoomClaimed: 'Claimed',
  nRoomBuy: 'Buy',
  nRoomWear: 'Wear',
  nRoomWearing: 'Wearing',
  nRoomPlaced: 'In your gym',
  nRoomNotEnough: 'Not enough coins yet — finish more quests!',
  nRoomCoins: 'coins',
  nRoomEarned: '+{n} coins!',
  nRoomBought: 'Purchased!',

  // App lock (Face ID / biometrics)
  nLockTitle: 'App Lock',
  nLockDesc: 'Require Face ID to open ASCND',
  nLockUnavailable: 'Biometric lock is unavailable on this device',
  nLockPrompt: 'Unlock ASCND',
  nLockLocked: 'ASCND is locked',
  nLockUnlock: 'Unlock',
};

const vi: typeof en = {
  nGoodMorning: 'Chào buổi sáng',
  nGoodAfternoon: 'Chào buổi chiều',
  nGoodEvening: 'Chào buổi tối',
  nReadiness: 'Mức sẵn sàng',
  nReadinessHint: 'Ghi giấc ngủ và buổi tập để có điểm số',
  nActivity: 'Hoạt động',
  nSteps: 'bước',
  nKcalToday: 'kcal hôm nay',
  nSleep: 'Giấc ngủ',
  nLastNight: 'Đêm qua',
  nWater: 'Nước',
  nStayHydrated: 'uống đủ nước nhé',
  nOfTarget: 'mục tiêu {x}',
  nSyncHealth: 'Đồng bộ Apple Health',
  nLogShort: 'Ghi',
  nQuality: 'Chất lượng',

  nToday: 'Hôm nay',
  nProtein: 'Đạm',
  nCarbs: 'Tinh bột',
  nFat: 'Béo',
  nLogMealBtn: 'Ghi bữa ăn',
  nNoMeals: 'Chưa có bữa nào',
  nNoMealsHint: 'Ghi bữa đầu tiên trong ngày ở nút phía trên',
  nBreakfast: 'Bữa sáng',
  nLunch: 'Bữa trưa',
  nDinner: 'Bữa tối',
  nSnack: 'Ăn vặt',
  nPreWorkout: 'Trước tập',
  nPostWorkout: 'Sau tập',
  nFavorites: 'Yêu thích',
  nRecent: 'Gần đây',

  nThisWeek: 'Tuần này',
  nSessions: 'buổi tập',
  nVolume: 'Khối lượng',
  nKgLifted: 'kg đã nâng',
  nLogWorkoutBtn: 'Ghi buổi tập',
  nNoWorkouts: 'Chưa có buổi tập nào',
  nNoWorkoutsHint: 'Ghi buổi đầu tiên — mức sẵn sàng sẽ thích ứng theo khối lượng tập',

  nWeight: 'Cân nặng',
  nLast30d: '30 ngày qua',
  nLast14d: '14 ngày qua',
  nNotEnoughData: 'Chưa đủ dữ liệu',
  nBuildTrendHint: 'Ghi giấc ngủ và buổi tập để dựng xu hướng',

  nLogMealTitle: 'Ghi bữa ăn',
  nSearchFoods: 'Tìm món ăn…',
  nWhatDidYouEat: 'Bạn đã ăn gì? (không bắt buộc)',
  nCalories: 'Calo (kcal)',
  nProteinG: 'Đạm (g)',
  nCarbsG: 'Tinh bột (g)',
  nFatG: 'Béo (g)',
  nSaveMeal: 'Lưu bữa ăn',

  nLogWorkoutTitle: 'Ghi buổi tập',
  nWorkoutName: 'Tên buổi tập (VD: Ngày đẩy)',
  nSets: 'Các set',
  nExercise: 'Bài tập',
  nReps: 'reps',
  nAddSet: 'Thêm set',
  nRpe: 'Độ gắng sức (RPE)',
  nSaveWorkout: 'Lưu buổi tập',

  nLogSleepTitle: 'Ghi giấc ngủ',
  nBedtime: 'Giờ đi ngủ',
  nWakeUp: 'Giờ dậy',
  nDuration: 'Thời lượng',
  nHowSleep: 'Bạn ngủ thế nào?',
  nSaveSleep: 'Lưu giấc ngủ',

  nDailyTarget: 'Mục tiêu ngày',
  nGoal: 'Mục tiêu',
  nTrainingLevel: 'Trình độ tập',
  nAbout: 'Thông tin',
  nVersion: 'Phiên bản',
  nSignOut: 'Đăng xuất',
  nSignOutConfirm: 'Bạn chắc chắn muốn đăng xuất?',
  nCancel: 'Huỷ',

  nSignInSubtitle: 'Đăng nhập để tiếp tục',
  nSignUpSubtitle: 'Tạo tài khoản của bạn',
  nYourName: 'Tên của bạn',
  nEmail: 'Email',
  nPassword: 'Mật khẩu',
  nSignIn: 'Đăng nhập',
  nSignUp: 'Đăng ký',
  nNoAccount: 'Chưa có tài khoản? ',
  nHaveAccount: 'Đã có tài khoản? ',

  nAskCoach: 'Hỏi huấn luyện viên',
  nAskCoachHint: 'Tập luyện, dinh dưỡng, phục hồi — trả lời dựa trên dữ liệu thật của bạn',
  nMessageCoach: 'Nhắn cho coach…',
  nHistory: 'Lịch sử',
  nNoHistory: 'Chưa có hội thoại nào',

  nAwards: 'Thành tích',
  nNoAwards: 'Chưa có thành tích nào',
  nNoAwardsHint: 'Cứ ghi chép đều — thành tích sẽ tự mở khoá',
  nChallenges: 'Thử thách',
  nNoChallenges: 'Tuần này chưa có thử thách',
  nNoChallengesHint: 'Thử thách tuần xuất hiện khi bạn bắt đầu ghi chép',
  nCompleted: 'Hoàn thành',
  nChallengeDone: 'Hoàn thành thử thách',
  nGrocery: 'Đi chợ',
  nAddItem: 'Thêm món cần mua…',
  nNoGrocery: 'Danh sách trống',
  nNoGroceryHint: 'Thêm nguyên liệu bạn cần mua',

  nSupplements: 'Thực phẩm bổ sung',
  nTakenToday: 'đã uống hôm nay',
  nWeightTitle: 'Ghi cân nặng',
  nLogWeight: 'Ghi',
  nAllSupplementsDone: 'Hôm nay uống đủ rồi',
  nReadinessTrend: 'Xu hướng sẵn sàng',
  nSmartTips: 'Gợi ý thông minh',
  nTipsHint: 'AI phân tích từ dữ liệu gần đây của bạn',
  nTipsLoading: 'Đang đọc xu hướng…',
  nTipsRefresh: 'Làm mới',
  nTipsEmpty: 'Ghi thêm để mở khoá gợi ý',
  nNoSupplements: 'Chưa có supplement nào',
  nNoSupplementsHint: 'Thêm stack của bạn trên bản web — checklist sẽ đồng bộ về đây',
  nExercises: 'Thư viện bài tập',
  nSearchExercises: 'Tìm bài tập…',
  nNoExercises: 'Không tìm thấy bài tập',
  nNoExercisesHint: 'Thư viện bài tập đồng bộ từ bản web',
  nRoutine: 'Lịch tập tuần',
  nRest: 'Nghỉ',
  nDeload: 'Deload',
  nChooseWorkout: 'Chọn buổi tập',
  nRoutineHint: 'Chạm vào một ngày để gán buổi tập, đánh dấu nghỉ, hoặc bật deload',
  nMealPlans: 'Kế hoạch ăn',
  nMealsPerDay: 'bữa/ngày',
  nDay: 'Ngày',
  nNoMealPlans: 'Chưa có kế hoạch ăn',
  nNoMealPlansHint: 'Tạo kế hoạch trên bản web — nó sẽ hiện ở đây',
  nWeeklyReview: 'Tổng kết tuần',
  nAiAnalysis: 'Phân tích AI',
  nWeeklyReviewHint: 'Để AI phân tích tuần của bạn và đưa gợi ý cho tuần tới',
  nAnalyzeWeek: 'Phân tích với AI',
  nWeekScore: 'Điểm tuần',

  nMascotTitle: 'Bạn đồng hành',
  nMascotToggleHint: 'Linh vật sẽ nhắc bạn dựa trên dữ liệu hôm nay',
  nMascotSleep: 'Chào buổi sáng! Đêm qua ngủ sao rồi? Ghi lại để mình tính điểm sẵn sàng nhé 😴',
  nMascotMeal: 'Hôm nay chưa ghi bữa nào — nạp năng lượng rồi ghi lại nha! 🍽',
  nMascotWater: 'Kiểm tra nước nè — bạn mới uống chưa được nửa mục tiêu 💧',
  nMascotWorkout: 'Giờ này tập là đẹp đó. Sẵn sàng chưa? 💪',
  nMascotPraise: 'Hôm nay bạn làm tốt lắm. Giữ vững phong độ nha! 🔥',
  nMascotHello: 'Mình đang theo dõi chỉ số của bạn — ghi gì đó đi, mình cổ vũ!',
  nMascotLocked: 'Chưa mở khoá',
  nMascotPro: 'PRO · sắp ra mắt',
  nMascotUnlockedBadge: 'Đã mở khoá',
  nMascotUnlockedTitle: 'Mở khoá nhân vật mới!',
  nMascotUse: 'Dùng ngay',
  nMascotLater: 'Để sau',

  nCameraNeeded: 'Cần quyền camera',
  nCameraHint: 'ASCND quét mã vạch để ghi thực phẩm đóng gói tức thì',
  nAllowCamera: 'Cho phép Camera',
  nPointBarcode: 'Hướng camera vào mã vạch',
  nLookingUp: 'Đang tra cứu sản phẩm…',
  nNotFound: 'Không tìm thấy — thử lại',

  // AI food scan
  nScanFood: 'Quét món ăn',
  nAiScanTitle: 'Quét món bằng AI',
  nScanModeFood: 'Món ăn',
  nScanModeLabel: 'Nhãn',
  nScanFoodHint: 'Hướng vào bữa ăn rồi nhấn chụp',
  nScanLabelHint: 'Đưa bảng thành phần dinh dưỡng vào khung',
  nAnalyzing: 'Đang phân tích…',
  nScanNoFood: 'Không nhận ra món ăn — thử lại',
  nScanRetake: 'Chụp lại',
  nScanAdd: 'Thêm {n} món',
  nScanAddOne: 'Thêm 1 món',
  nRetake: 'Chụp lại',
  nScanError: 'Quét thất bại — thử lại',

  nLegal: 'Chính sách & Pháp lý',
  nTemplates: 'Mẫu buổi tập',
  nTemplateName: 'Tên mẫu',
  nCreateExercise: 'Bài tập mới',
  nMuscleGroup: 'Nhóm cơ',
  nEquipment: 'Dụng cụ',
  nExerciseName: 'Tên bài tập',
  nNoExercisesFound: 'Không tìm thấy bài tập',
  nSuggestions: 'Gợi ý',
  nRestSec: 'Nghỉ',
  nDeleteTemplate: 'Xoá mẫu này?',

  // Water & Steps detail
  nWaterTitle: 'Nước uống',
  nStepsTitle: 'Bước chân',
  nLast7Days: '7 ngày qua',
  nDailyAvg: 'Trung bình ngày',
  nTodayTotal: 'Hôm nay',
  nTodayLogs: 'Nhật ký hôm nay',
  nStepsGoal: 'Mục tiêu {x}',
  nQuickAdd: 'Thêm nhanh',

  // Progress photos
  nPhotoFront: 'Trước',
  nPhotoSide: 'Nghiêng',
  nPhotoBack: 'Sau',
  nPhotoUploading: 'Đang tải lên…',
  nPhotoDelete: 'Xoá ảnh?',
  nPhotoAdd: 'Thêm ảnh tiến trình',
  nPhotoCapture: 'Chụp',

  // Meal builder
  nMealItems: 'Các món',
  nMealNoItems: 'Tìm, quét hoặc thêm món để bắt đầu',
  nNutritionTotal: 'Tổng dinh dưỡng',
  nServings: 'Khẩu phần',
  nAiSuggest: 'AI gợi ý',
  nAiSuggestTitle: 'AI gợi ý bữa ăn',
  nAiSuggestHint: 'Dựa trên lượng macro còn lại hôm nay',
  nAiThinking: 'Đang nghĩ món…',
  nAddThis: 'Thêm',
  nPrepTime: '{n} phút',
  nAiNoIdeas: 'Chưa có gợi ý — thử lại sau',

  // Reminders (local notifications)
  nRemindersTitle: 'Nhắc nhở',
  nRemindersDesc: 'Nhắc mỗi ngày để giữ chuỗi thói quen',
  nRemindersEnable: 'Cho phép thông báo',
  nRemindersDenied: 'Thông báo đang tắt. Bật trong Cài đặt iOS › ASCND.',
  nReminderWater: 'Uống nước',
  nReminderWaterBody: 'Đến giờ uống một cốc nước rồi 💧',
  nReminderSupplements: 'Thực phẩm bổ sung',
  nReminderSupplementsBody: 'Nhớ uống thực phẩm bổ sung 💊',
  nReminderBedtime: 'Chuẩn bị ngủ',
  nReminderBedtimeBody: 'Sắp đến giờ ngủ — thư giãn thôi 😴',
  nReminderWeighIn: 'Cân buổi sáng',
  nReminderWeighInBody: 'Ghi cân nặng trước bữa sáng ⚖️',
  nReminderWorkout: 'Tập hôm nay',
  nReminderWorkoutBody: 'Lịch của bạn có buổi tập hôm nay 💪',
  nReminderTime: 'Giờ',
  nReminderEveryHours: 'Mỗi {n} giờ',

  // Offline
  nOffline: 'Ngoại tuyến — đang hiển thị dữ liệu đã lưu',
  nHealthSynced: 'Đã đồng bộ Apple Health!',

  // Mascot room
  nRoomQuests: 'Nhiệm vụ hôm nay',
  nRoomQuestsHint: 'Tập, ăn, uống nước — kiếm xu cho bạn đồng hành',
  nRoomWeeklyBonus: 'Thưởng thử thách tuần',
  nRoomShop: 'Cửa hàng',
  nRoomOutfits: 'Trang phục',
  nRoomGymGear: 'Đồ phòng gym',
  nRoomClaim: 'Nhận',
  nRoomClaimed: 'Đã nhận',
  nRoomBuy: 'Mua',
  nRoomWear: 'Mặc',
  nRoomWearing: 'Đang mặc',
  nRoomPlaced: 'Đã đặt trong phòng',
  nRoomNotEnough: 'Chưa đủ xu — hoàn thành thêm nhiệm vụ nhé!',
  nRoomCoins: 'xu',
  nRoomEarned: '+{n} xu!',
  nRoomBought: 'Đã mua!',

  // App lock (Face ID / sinh trắc)
  nLockTitle: 'Khoá ứng dụng',
  nLockDesc: 'Yêu cầu Face ID để mở ASCND',
  nLockUnavailable: 'Thiết bị không hỗ trợ khoá sinh trắc',
  nLockPrompt: 'Mở khoá ASCND',
  nLockLocked: 'ASCND đang khoá',
  nLockUnlock: 'Mở khoá',
};

export const nativeStrings: Record<AppLang, typeof en> = { vi, en };
export type NativeStrings = typeof en;
