import type { AppLang } from './i18n';

/**
 * Strings specific to the native app's screens, in both languages.
 * The big ported dictionary (i18n.ts) covers web-page copy; these cover
 * the native layouts. Merged with it in useI18n().
 */
const en = {
  // Today
  nGoodMorning: 'Good morning',
  nGoodAfternoon: 'Good afternoon',
  nGoodEvening: 'Good evening',
  nReadiness: 'Readiness',
  nReadinessHint: 'Log sleep and training to get your score',
  nActivity: 'Activity',
  nSteps: 'steps',
  nKcalToday: 'kcal today',
  nSleep: 'Sleep',
  nLastNight: 'Last night',
  nWater: 'Water',
  nStayHydrated: 'stay hydrated',
  nOfTarget: 'of {x} target',
  nSyncHealth: 'Sync Apple Health',
  nLogShort: 'Log',
  nQuality: 'Quality',

  // Nutrition
  nToday: 'Today',
  nProtein: 'Protein',
  nCarbs: 'Carbs',
  nFat: 'Fat',
  nLogMealBtn: 'Log Meal',
  nNoMeals: 'No meals yet',
  nNoMealsHint: 'Log your first meal of the day above',
  nBreakfast: 'Breakfast',
  nLunch: 'Lunch',
  nDinner: 'Dinner',
  nSnack: 'Snack',
  nPreWorkout: 'Pre-workout',
  nPostWorkout: 'Post-workout',
  nFavorites: 'Favorites',
  nRecent: 'Recent',

  // Workouts
  nThisWeek: 'This week',
  nSessions: 'sessions',
  nVolume: 'Volume',
  nKgLifted: 'kg lifted',
  nLogWorkoutBtn: 'Log Workout',
  nNoWorkouts: 'No workouts yet',
  nNoWorkoutsHint: 'Log your first session — readiness adapts to your training load',

  // Progress
  nWeight: 'Weight',
  nLast30d: 'Last 30 days',
  nLast14d: 'Last 14 days',
  nNotEnoughData: 'Not enough data yet',
  nBuildTrendHint: 'Log sleep and training to build your trend',

  // Log Meal sheet
  nLogMealTitle: 'Log Meal',
  nSearchFoods: 'Search foods…',
  nWhatDidYouEat: 'What did you eat? (optional)',
  nCalories: 'Calories (kcal)',
  nProteinG: 'Protein g',
  nCarbsG: 'Carbs g',
  nFatG: 'Fat g',
  nSaveMeal: 'Save Meal',

  // Log Workout sheet
  nLogWorkoutTitle: 'Log Workout',
  nWorkoutName: 'Workout name (e.g. Push Day)',
  nSets: 'Sets',
  nExercise: 'Exercise',
  nReps: 'reps',
  nAddSet: 'Add set',
  nRpe: 'Session effort (RPE)',
  nSaveWorkout: 'Save Workout',
  nLgBwHint: 'Leave the weight empty for a bodyweight set.',
  nLgNewExercise: 'Different exercise',
  nLgNeedReps: 'A set is saved once it has reps.',

  // Log Sleep sheet
  nLogSleepTitle: 'Log Sleep',
  nBedtime: 'Bedtime',
  nWakeUp: 'Wake up',
  nDuration: 'Duration',
  nHowSleep: 'How did you sleep?',
  nSaveSleep: 'Save Sleep',

  // Settings
  nDailyTarget: 'Daily target',
  nGoal: 'Goal',
  nTrainingLevel: 'Training level',
  nAbout: 'About',
  nVersion: 'Version',
  nSignOut: 'Sign Out',
  nSignOutConfirm: 'Are you sure you want to sign out?',
  nCancel: 'Cancel',

  // Auth
  nSignInSubtitle: 'Sign in to continue',
  nSignUpSubtitle: 'Create your account',
  nYourName: 'Your name',
  nEmail: 'Email',
  nPassword: 'Password',
  nSignIn: 'Sign In',
  nSignUp: 'Sign Up',
  nNoAccount: "Don't have an account? ",
  nHaveAccount: 'Already have an account? ',

  // AI Coach
  nAskCoach: 'Ask your coach',
  nAskCoachHint: 'Training, nutrition, recovery — answers use your real data',
  nMessageCoach: 'Message your coach…',
  nHistory: 'History',
  nNoHistory: 'No conversations yet',

  // Extras
  nAwards: 'Awards',
  nNoAwards: 'No awards yet',
  nNoAwardsHint: 'Keep logging — achievements unlock automatically',
  nChallenges: 'Challenges',
  nNoChallenges: 'No challenges this week',
  nNoChallengesHint: 'Weekly challenges appear when you start logging',
  nCompleted: 'Completed',
  nChallengeDone: 'Challenge complete',
  nGrocery: 'Shopping list',
  nAddItem: 'Add an item…',
  nGroceryLeft: '{n} left',
  nNoGrocery: 'List is empty',
  nNoGroceryHint: 'Add ingredients you need to buy',

  // Library screens
  nSupplements: 'Supplements',
  nTakenToday: 'taken today',
  nWeightTitle: 'Weight check-in',
  nLogWeight: 'Log',
  nAllSupplementsDone: 'All done for today',
  nReadinessTrend: 'Readiness trend',
  nSmartTips: 'Smart tips',
  nTipsHint: 'AI insights from your recent data',
  nTipsLoading: 'Reading your trends…',
  nTipsRefresh: 'Refresh',
  nTipsEmpty: 'Log more to unlock tips',
  // read failed — deliberately not the same words as an empty day
  // Segment-neutral on purpose: this card appears on Progress and Workouts too,
  // and "Could not load today" is wrong on a screen showing three months of
  // weight history.
  nLoadFailed: 'Could not load your data',
  nLoadFailedHint: 'Your data is safe. The app just could not reach it.',
  // What the target-calibration card promises, and it has to be true: this
  // runs on the device, not on a model.
  nCalibrateHint:
    'Measures what you actually burn from your intake and what the scale did, then suggests a calorie target that matches it.',
  nRetry: 'Try again',
  // ── screen-reader names for icon-only buttons ──
  // Verbs, not nouns: the reader already says "button", so the label supplies
  // the action. "Trash" leaves the listener guessing; "Delete photo" does not.
  a11yBack: 'Go back',
  a11yClose: 'Close',
  a11yDismiss: 'Dismiss',
  a11yDelete: 'Delete',
  a11yEdit: 'Edit',
  a11yAdd: 'Add',
  a11yMore: 'More options',
  a11yIncrease: 'Increase',
  a11yDecrease: 'Decrease',
  a11ySettings: 'Open settings',
  a11ySearch: 'Search',
  a11yClearSearch: 'Clear search',
  a11yLogMeal: 'Log a meal',
  a11yAskCoach: 'Ask the coach',
  a11yCloseCoach: 'Close the coach',
  a11yFavourite: 'Toggle favourite',
  a11yTakePhoto: 'Take photo',
  a11ySwitchCamera: 'Switch camera',
  a11yPrevWeek: 'Previous week',
  a11yNextWeek: 'Next week',
  a11yEditGoal: 'Edit goal',
  a11yOpenRoom: 'Open Koa’s room',
  a11yCheckOff: 'Mark as taken',
  a11yExpand: 'Show details',
  a11ySend: 'Send message',
  a11yHistory: 'Chat history',
  a11yNewChat: 'New chat',
  a11yShare: 'Share',
  a11yScanFood: 'Scan food with camera',
  a11yScanBarcode: 'Scan barcode',
  a11yRemove: 'Remove',
  a11yEditLayout: 'Rearrange dashboard',
  a11yDoneEditing: 'Done rearranging',
  a11yAcceptTerms: 'Accept the terms',
  a11yMoveUp: 'Move up',
  a11yMoveDown: 'Move down',
  a11ySleepQuality: 'Sleep quality {x} of 5',
  // ── deleting an account ──
  nDeleteAccount: 'Delete account',
  nDeleteAccountDesc: 'Permanently removes your account and everything in it',
  nDeleteAccountTitle: 'Delete your account?',
  nDeleteAccountBody:
    'This erases your meals, workouts, sleep, weight and Koa’s wardrobe. It cannot be undone. Export your data first if you want to keep it.',
  nDeleteAccountConfirm: 'Delete everything',
  nDeleteAccountDone: 'Your account has been deleted.',
  nDeleteAccountNotSetUp: 'Account deletion is not available on this server yet.',
  nDeleteAccountFailed: 'Could not delete the account. Nothing was removed.',
  a11yPrevItem: 'Previous item',
  a11yNextItem: 'Next item',
  a11yAddWater: 'Add {x} {unit}',
  // ── weight history, and correcting it ──
  nWeightHistory: 'Logged weights',
  nWeightEntries: '{n} entries',
  nWeightEntriesOne: '1 entry',
  nWeightSeeAll: 'See all {n} entries',
  nDeleteWeight: 'Remove this weight',
  nDeleteWeightMsg: 'Remove the {x} entry? The chart and your BMI will be recalculated.',
  // ── logged sessions, and correcting them ──
  nDeleteSession: 'Remove this session',
  nDeleteSessionMsg: 'Remove {x}? Your training load and readiness will be recalculated.',
  // AI edge functions — one message per distinct cause, so wiring a new
  // Supabase project up tells you what is missing instead of "it failed"
  aiNotDeployed: 'This AI feature is not set up on the server yet.',
  aiProviderError: 'The AI service could not answer. Try again in a moment.',
  aiSignedOut: 'Please sign in again to use AI features.',
  aiOffline: 'No connection — AI needs the internet.',
  aiRateLimited: 'You have used up the AI for now. Try again later.',
  aiUnknown: 'Something went wrong with the AI request.',
  nDiaryLoadFailed: 'Could not load your meals',
  nNoSupplements: 'No supplements yet',
  nNoSupplementsHint: 'Add your stack in the web app — the checklist syncs here',
  nExercises: 'Exercise Library',
  nSearchExercises: 'Search exercises…',
  nNoExercises: 'No exercises found',
  nNoExercisesHint: 'Your exercise library syncs from the web app',
  nRoutine: 'Weekly Routine',
  nRest: 'Rest',
  nDeload: 'Deload',
  nChooseWorkout: 'Choose workout',
  nRoutineHint: 'Tap a day to assign a workout, mark rest, or set deload',
  nRoutineDone: 'Done',
  nRoutineTodo: 'To do',
  nRoutineMissed: 'Not trained',
  nRoutineRestDay: 'Rest day',
  nRoutineRestHint: 'Rest, or something light',
  nRoutineExercises: '{n} exercises',
  nRoutineMinutes: '{n} min',
  nRoutineEffort: 'RPE {x}',
  nRoutineEffortRange: 'RPE {a}–{b}',
  nRoutineToday: 'Today',
  nRoutineNoTemplates: 'No saved workouts yet — build one first.',
  nRdSet: 'Set {n}',
  nRdProgress: '{done}/{total} sets',
  nRdFinish: 'Finish workout',
  nRdResting: 'Rest',
  nRdSkip: 'Skip',
  nRdEmptyPlan: 'This day has no workout on it',
  nRdSaved: 'Workout logged',
  nRdBodyweight: 'Bodyweight',
  nRdAlready: 'Already logged',
  nRdLoggedAt: 'at {t}',
  nRdPlanToday: "Today's plan",
  nRdUsePlan: 'Use',
  nMealPlans: 'Meal Plans',
  nMealPlanNone: 'No meal plans yet',
  nMealPlanWhat: 'A meal plan is a few days of eating written down in advance, so "what do I eat today" is already answered.',
  nMealPlanNew: 'New meal plan',
  nMealPlanOpen: 'Open',
  nMealsPerDay: 'meals/day',
  nDay: 'Day',
  nNoMealPlans: 'No meal plans yet',
  nMpAddFood: 'Add food',
  nMpStepPlanHint: 'What you will call this plan when you come back to it',
  nMpStepSlotsHint: 'How many meals each day of the plan has',
  nMpPlanNameEg: 'e.g. Meal Prep Week 1',
  nMpNextAddFood: 'Create and add food',
  nExNameHint: 'What you will search for when you add it to a workout',
  nExGroupHint: 'Where it files itself in the library',
  nExGearHint: 'Optional — barbell, dumbbell, machine, or nothing at all',
  nMpStepPlan: 'Plan',
  nMpStepDay: 'Day',
  nMpStepMeal: 'Meal',
  nMpStepFood: 'Food',
  nMpStepDayHint: 'Which day of the plan this goes on',
  nMpStepMealHint: 'Which meal of that day',
  nMpStepFoodHint: 'Search, then tap to add. The sheet stays open — a meal is rarely one food.',
  nMpAddTitle: 'Add food',
  nMpAddedN: '{n} added',
  nMpDone: 'Done',
  nMpPickFood: 'Pick a food',
  nMpEmptyDay: 'Nothing planned',
  nMpAvgPerDay: '{x} kcal/day',
  nMpTarget: 'target {x}',
  nMpPctTarget: '{p}% of target',
  nMpDayEmptyHint: 'Nothing planned for this day yet.',
  nMpPlanEmpty: 'This plan has no food in it yet',
  nMpWeekTotal: '{x} kcal across the week',
  nMpFromList: 'From your list',
  nMpNoMatch: 'No food matches “{x}”',
  nMpAlready: 'added',
  nMpEatIt: 'Log to today',
  nMpEaten: 'In today',
  nMpAgainTitle: 'Already in today',
  nMpAgainBody: 'Today already has a {m} with exactly these foods. Log it a second time?',
  nMpAgainYes: 'Log again',
  nMpEatDone: '{m} added to today’s diary',
  nMpNoFibre: 'Logged from a plan carries no fibre — the plan does not record it.',
  // Repeating a meal you have already eaten
  nRmTitle: 'Eat this again',
  nRmHint: 'Fills the form — check it, then save.',
  nRmYesterday: 'yesterday',
  nRmToday: 'today',
  nRmDaysAgo: '{n} days ago',
  nRmFoods: '{n} foods',
  nWeeklyReview: 'Weekly Review',
  nAiAnalysis: 'AI Analysis',
  nWeeklyReviewHint: 'Let AI analyze your week and give recommendations for the next one',
  nAnalyzeWeek: 'Analyze with AI',
  nWeekScore: 'Week score',

  // Mascot
  nMascotTitle: 'Companion',
  nMascotToggleHint: 'Your companion nudges you based on today\u2019s data',
  nMascotSleep: 'Morning! How did you sleep? Log it so I can compute your readiness 😴',
  nMascotMeal: 'No meals logged yet today — fuel up and log it! 🍽',
  nMascotWater: 'Hydration check — you\u2019re under half your water target 💧',
  nMascotWorkout: 'Great window for a workout right now. Ready when you are 💪',
  nMascotPraise: 'You\u2019re crushing it today. Keep the streak alive! 🔥',
  nMascotHello: 'I\u2019m watching your stats — log something and I\u2019ll cheer you on!',
  // ── Koa naming what you did, then what is left ──
  // Short on purpose: the two get joined into one speech bubble, and a bubble
  // people actually read is one line.
  nMascotWinSleep: 'Sleep logged 😴',
  nMascotWinMeal: 'Meals logged 🍽',
  nMascotWinWater: 'Water on target 💧',
  nMascotWinWorkout: 'Workout done 💪',
  nMascotGapSleep: 'log last night too',
  nMascotGapMeal: 'log a meal next',
  nMascotGapWater: 'drink some water',
  nMascotGapWorkout: 'a session would round it off',
  nMascotThen: '{win} — {gap}',
  nMascotLocked: 'Locked',
  nMascotPro: 'PRO · coming soon',
  nMascotUnlockedBadge: 'Unlocked',
  nMascotUnlockedTitle: 'New companion unlocked!',
  nMascotUse: 'Use now',
  nMascotLater: 'Later',

  // Scanner
  nCameraNeeded: 'Camera access needed',
  nCameraHint: 'ASCND scans barcodes to log packaged foods instantly',
  nAllowCamera: 'Allow Camera',
  nPointBarcode: 'Point at a barcode',
  nLookingUp: 'Looking up product…',
  nNotFound: 'Product not found — try again',

  // AI food scan
  nScanFood: 'Scan food',
  nAiScanTitle: 'AI Food Scan',
  nScanModeFood: 'Dish',
  nScanModeLabel: 'Label',
  nScanFoodHint: 'Point at your meal and tap the shutter',
  nScanLabelHint: 'Frame the nutrition facts panel',
  nAnalyzing: 'Analyzing…',
  nScanNoFood: 'No food detected — try again',
  /* Where the numbers came from. Two of these three modes read a printed
     figure; one guesses a portion size from a picture, and they are nowhere
     near equally accurate. Check what they are before adding. */
  nScanFromPhoto: 'Estimated from the photo — portion size is a guess. Check before adding.',
  nScanFromLabel: 'Read off the nutrition panel.',
  nScanRetake: 'Retake',
  nScanAdd: 'Add {n} items',
  nScanAddOne: 'Add 1 item',
  nRetake: 'Retake',
  nScanError: 'Scan failed — try again',

  nLegal: 'Policies & Legal',
  nTemplates: 'Templates',
  nTemplateName: 'Template name',
  nCreateExercise: 'New exercise',
  nMuscleGroup: 'Muscle group',
  nEquipment: 'Equipment',
  nExerciseName: 'Exercise name',
  nNoExercisesFound: 'No exercises found',
  nSuggestions: 'Suggestions',
  nRestSec: 'Rest',
  nDeleteTemplate: 'Delete template?',

  // Workout builder — the two-step flow
  nWbTitle: 'New workout',
  nWbStepPick: 'Choose exercises',
  nWbStepReview: 'Sets & name',
  nWbPickHint: 'Tap what you want in this workout. Sets and reps come next.',
  nWbAll: 'All',
  nWbSelected: '{n} selected',
  nWbNext: 'Next',
  nWbNoMatch: 'Nothing matches “{x}”',
  nWbCreateNamed: 'Create “{x}”',
  nWbLibraryEmpty: 'Your exercise library is empty',
  nWbAddMore: 'Add more exercises',
  nWbSummary: '{n} exercises · {s} sets · about {m} min',
  nWbNameHint: 'Named from the muscles you picked — change it if you like.',
  nWbNameOne: '{x} day',
  nWbNameTwo: '{a} & {b}',
  nWbType: 'Type',
  nWbSave: 'Save workout',
  nWbSets: 'Sets',
  nWbReps: 'Reps',
  nWbLoad: 'Weight',
  nWbBodyweight: 'Bodyweight',
  nWbRest: 'Rest between sets',
  nWbEffort: 'Effort',
  nWbEffortHint: 'How the last rep should feel. 10 is failure.',

  // Saved workout card — rest and effort read back
  nTplRest: 'Rest {x}',
  nTplNoRest: 'No rest',
  nTplEffort: 'Effort {x}/10',
  nWbMoveUp: 'Move earlier',
  nWbMoveDown: 'Move later',
  nWbRemove: 'Remove from workout',
  nWbDone: 'Done',
  nWbTypePush: 'Push',
  nWbTypePull: 'Pull',
  nWbTypeLegs: 'Legs',
  nWbTypeUpper: 'Upper body',
  nWbTypeLower: 'Lower body',
  nWbTypeFullBody: 'Full body',
  nWbTypeStrength: 'Strength',
  nWbTypeHypertrophy: 'Hypertrophy',
  nWbTypeCardio: 'Cardio',
  nWbTypeCustom: 'Custom',

  // Water & Steps detail
  nWaterTitle: 'Hydration',
  nStepsTitle: 'Steps',
  nLast7Days: 'Last 7 days',
  nAverage: 'Average',
  nRangeWeek: 'Week',
  nRangeMonth: 'Month',
  nRangeYear: 'Year',
  nRangeAll: 'All',
  nDailyAvg: 'Daily average',
  nTodayTotal: 'Today',
  nTodayLogs: 'Today’s log',
  nStepsGoal: 'Goal {x}',
  nQuickAdd: 'Quick add',
  // manual entry, for the amounts the presets do not cover
  nWaterCustom: 'Another amount',
  nWaterEntries: '{n} entries',
  nWaterEntriesOne: '1 entry',
  nWaterCustomTitle: 'How much did you drink?',
  nWaterTooMuch: 'That is more than {x} in one go — check the number',

  // Progress photos
  nPhotoFront: 'Front',
  nPhotoSide: 'Side',
  nPhotoBack: 'Back',
  nPhotoUploading: 'Uploading…',
  nPhotoDelete: 'Delete photo?',
  nPhotoAdd: 'Add progress photo',
  nPhotoCapture: 'Capture',

  // Today's diary — collapsed meal cards + quick stats
  nDiaryItems: '{n} items',
  nDiaryItemsOne: '1 item',
  nDiaryEntries: '{n} meals',
  // editing what is already logged
  nItemEdit: 'Edit servings',
  nItemDelete: 'Remove from log',
  nItemDeleteMsg: 'Remove {name} from today\'s log?',
  nItemServings: 'Servings',
  nServingsMore: 'More servings',
  nServingsLess: 'Fewer servings',
  nItemUpdated: 'Log updated',
  nQuickCalories: 'Calories',
  nQuickProtein: 'Protein',
  nQuickWater: 'Water',

  // Weight changes card (Progress)
  nWeightChanges: 'Weight Changes',
  nWcDays: '{n} day',
  nWcAllTime: 'All Time',
  nWcNoChange: 'No change',
  nWcIncrease: 'Increase',
  nWcDecrease: 'Decrease',
  nWcNoData: 'Log your weight to see changes here',

  // Weight goal (Progress weight chart)
  nQuickActions: 'Quick actions',
  nHealthAssistant: 'Health assistant',
  nQuickActionsClose: 'Close quick actions',
  nWeightGoal: 'Goal',
  nWeightGoalSet: 'Set a target weight',
  nWeightGoalTitle: 'Target weight',
  nWeightGoalEdit: 'Edit Weight Goal',
  nWeightGoalDone: 'Done',
  nWeightGoalGain: 'Gain weight',
  nWeightGoalLose: 'Lose weight',
  nWeightGoalMaintain: 'Maintain weight',
  nWeightGoalClear: 'Clear',
  nWeightGoalToGo: '{x} to go',
  nWeightGoalReached: 'Target reached',

  // The four ways to log a meal.
  //
  // Two labels each, and both are needed. `nWay*` is what the tile says — a
  // quarter of a card's width, so it has to hold on one line. `nAdd*` is what
  // VoiceOver says, where there is no width to fit and "Tìm món" alone does
  // not say what is being searched.
  nWayPhoto: 'Photo',
  nWayBarcode: 'Barcode',
  nWaySearch: 'Search',
  nWayManual: 'Manual',
  nAddCamera: 'Scan a meal',
  nAddBarcode: 'Scan a barcode',
  nAddSearch: 'Search food',
  nAddManual: 'Enter manually',

  // Meal builder
  nMealItems: 'Items',
  nMealNoItems: 'Search, scan, or add a food to start',
  nNutritionTotal: 'Nutrition total',
  nServings: 'Servings',
  nAiSuggest: 'AI suggest',
  nAiSuggestTitle: 'AI Meal Ideas',
  nAiSuggestHint: 'Based on your remaining macros today',
  nAiThinking: 'Cooking up ideas…',
  nAddThis: 'Add',
  nPrepTime: '{n} min',
  nAiNoIdeas: 'No suggestions right now — try later',

  // Reminders (local notifications)
  nRemindersTitle: 'Reminders',
  nRemindersDesc: 'Daily nudges to keep your streak',
  nRemindersEnable: 'Allow notifications',
  nRemindersDenied: 'Notifications are off. Enable them in iOS Settings › ASCND.',
  nReminderWater: 'Drink water',
  nReminderWaterBody: 'Time for a glass of water 💧',
  nReminderSupplements: 'Supplements',
  nReminderSupplementsBody: 'Take your supplements 💊',
  nReminderBedtime: 'Wind down',
  nReminderBedtimeBody: 'Bedtime soon — start winding down 😴',
  nReminderWeighIn: 'Morning weigh-in',
  nReminderWeighInBody: 'Log your weight before breakfast ⚖️',
  nReminderWorkout: 'Train today',
  nReminderWorkoutBody: 'Your plan has a session scheduled 💪',
  nReminderTime: 'Time',
  nReminderEveryHours: 'Every {n}h',

  // Offline
  nOffline: 'Offline — showing saved data',
  nHealthSynced: 'Apple Health synced!',

  // Mascot room
  nRoomQuests: 'Daily quests',
  nRoomQuestsHint: 'Train, eat, hydrate — earn coins for your buddy',
  nRoomWeeklyBonus: 'Weekly challenge bonus',
  nRoomShop: 'Shop',
  nRoomDressing: 'Dressing Room',
  nRoomOverview: 'Room',
  nRoomOverviewHint: 'Pick a corner of the room above.',
  nRoomOutfits: 'Outfits',
  nRoomCloset: 'Closet',
  nRoomGymGear: 'Gym gear',
  nRoomStageSkins: 'Stages',
  nRoomUse: 'Use',
  nRoomUsing: 'Using',
  nRoomClaim: 'Claim',
  nRoomClaimed: 'Claimed',
  nRoomBuy: 'Buy',
  nRoomWear: 'Wear',
  nRoomTakeOff: 'Take off',
  nRoomWearing: 'Wearing',
  nRoomPlaced: 'In your gym',
  nRoomPlace: 'Place',
  nRoomAll: 'All',
  nRoomOwned: 'Owned',
  nRoomLockLevel: 'Lv.{n}',
  nRoomCollections: 'Collections',
  nRoomCollectionsHint: 'Collect a full set for a special reward!',
  nRoomSetProgress: '{a}/{b} owned',
  nRoomSetDone: 'Set complete!',
  nRoomEmptyCat: 'More coming soon',
  nRoomSetClaimed: 'Reward claimed',
  nRoomNotEnough: 'Not enough coins yet — finish more quests!',
  nRoomCoins: 'coins',
  nRoomEarned: '+{n} coins!',
  nRoomBought: 'Purchased!',
  nRoomUpgrades: 'Room upgrades',
  nRoomInstalled: 'Installed',
  nRoomStreak: '{n}-day streak',
  nRoomLearned: 'Koa has noticed: you usually log {what} around {time}',
  nFreezeTitle: 'Streak Freeze',
  nFreezeHeld: '{n}/{max} in the drawer',
  nFreezeHint: 'Covers one missed day automatically. Koa only spends one when it actually saves the streak.',
  nFreezeBuy: 'Buy · {n}',
  nFreezeFull: 'Drawer full',
  nFreezeSaved: 'A freeze covered {n} day',
  nFreezeSavedPlural: 'Freezes covered {n} days',
  /* Nouns, for the sentence above. The win phrases nearby are whole sentences
     with emoji in them ("Meals logged 🍽") and read as nonsense inside another
     sentence — a label is not a message. */
  nThingMeal: 'meals',
  nThingWorkout: 'training',
  nThingWater: 'water',
  nThingSleep: 'sleep',
  nThingSteps: 'steps',
  nStreakLit: '{n}-day streak, today is logged',
  nStreakAtRisk: '{n}-day streak, nothing logged today yet',
  nStageStreak: 'Day streak',
  nStageQuests: 'Quests',
  nRoomLevel: 'Level {n}',
  nRoomLevelHint: '{n} XP to the next level',
  nRoomLevelUp: 'Level up! Your buddy reached level {n}',
  nRoomMoodTired: "I'm feeling sluggish today… log a meal or a workout to wake me up!",
  nRoomWardrobe: 'Wardrobe',
  nRoomChangeBuddy: 'Change buddy',
  nRoomWelcome: 'Welcome gift: +{n} coins!',
  // Rank ladder
  nRoomNextRank: 'Next: {r} at level {n}',
  nRoomMaxRank: 'Top rank reached — legendary!',
  nRoomRankUp: 'New rank unlocked: {r}!',
  nRoomJourney: 'Journey',
  nRoomLevelsToRank: '{n} levels to {r}',
  // Today's energy
  nRoomEnergy: "Today's energy",
  nRoomEnergyEmpty: 'Running on empty — log a meal or a workout to wake me up.',
  nRoomEnergyLow: 'Just getting started — keep the day going!',
  nRoomEnergyMid: 'Feeling good — a couple more to go.',
  nRoomEnergyFull: 'Fully charged! Every daily goal is done.',
  nRoomSigMeal: 'Meal',
  nRoomSigWorkout: 'Workout',
  nRoomSigWater: 'Water',
  nRoomSigSleep: 'Sleep',
  nRoomSigSteps: 'Steps',

  // App lock (Face ID / biometrics)
  nLockTitle: 'App Lock',
  nLockDesc: 'Require Face ID to open ASCND',
  nLockUnavailable: 'Biometric lock is unavailable on this device',
  nLockPrompt: 'Unlock ASCND',
  nLockLocked: 'ASCND is locked',
  nLockUnlock: 'Unlock',
};

const vi: typeof en = {
  nGoodMorning: 'Chào buổi sáng',
  nGoodAfternoon: 'Chào buổi chiều',
  nGoodEvening: 'Chào buổi tối',
  nReadiness: 'Mức sẵn sàng',
  nReadinessHint: 'Ghi giấc ngủ và buổi tập để có điểm số',
  nActivity: 'Hoạt động',
  nSteps: 'bước',
  nKcalToday: 'kcal hôm nay',
  nSleep: 'Giấc ngủ',
  nLastNight: 'Đêm qua',
  nWater: 'Nước',
  nStayHydrated: 'uống đủ nước nhé',
  nOfTarget: 'mục tiêu {x}',
  nSyncHealth: 'Đồng bộ Apple Health',
  nLogShort: 'Ghi',
  nQuality: 'Chất lượng',

  nToday: 'Hôm nay',
  nProtein: 'Đạm',
  nCarbs: 'Tinh bột',
  nFat: 'Béo',
  nLogMealBtn: 'Ghi bữa ăn',
  nNoMeals: 'Chưa có bữa nào',
  nNoMealsHint: 'Ghi bữa đầu tiên trong ngày ở nút phía trên',
  nBreakfast: 'Bữa sáng',
  nLunch: 'Bữa trưa',
  nDinner: 'Bữa tối',
  nSnack: 'Ăn vặt',
  nPreWorkout: 'Trước tập',
  nPostWorkout: 'Sau tập',
  nFavorites: 'Yêu thích',
  nRecent: 'Gần đây',

  nThisWeek: 'Tuần này',
  nSessions: 'buổi tập',
  nVolume: 'Khối lượng',
  nKgLifted: 'kg đã nâng',
  nLogWorkoutBtn: 'Ghi buổi tập',
  nNoWorkouts: 'Chưa có buổi tập nào',
  nNoWorkoutsHint: 'Ghi buổi đầu tiên — mức sẵn sàng sẽ thích ứng theo khối lượng tập',

  nWeight: 'Cân nặng',
  nLast30d: '30 ngày qua',
  nLast14d: '14 ngày qua',
  nNotEnoughData: 'Chưa đủ dữ liệu',
  nBuildTrendHint: 'Ghi giấc ngủ và buổi tập để dựng xu hướng',

  nLogMealTitle: 'Ghi bữa ăn',
  nSearchFoods: 'Tìm món ăn…',
  nWhatDidYouEat: 'Bạn đã ăn gì? (không bắt buộc)',
  nCalories: 'Calo (kcal)',
  nProteinG: 'Đạm (g)',
  nCarbsG: 'Tinh bột (g)',
  nFatG: 'Béo (g)',
  nSaveMeal: 'Lưu bữa ăn',

  nLogWorkoutTitle: 'Ghi buổi tập',
  nWorkoutName: 'Tên buổi tập (VD: Ngày đẩy)',
  nSets: 'Các set',
  nExercise: 'Bài tập',
  nReps: 'reps',
  nAddSet: 'Thêm set',
  nRpe: 'Độ gắng sức (RPE)',
  nSaveWorkout: 'Lưu buổi tập',
  nLgBwHint: 'Bỏ trống ô cân nặng nếu là set tay không.',
  nLgNewExercise: 'Bài tập khác',
  nLgNeedReps: 'Set có số rep thì mới được lưu.',

  nLogSleepTitle: 'Ghi giấc ngủ',
  nBedtime: 'Giờ đi ngủ',
  nWakeUp: 'Giờ dậy',
  nDuration: 'Thời lượng',
  nHowSleep: 'Bạn ngủ thế nào?',
  nSaveSleep: 'Lưu giấc ngủ',

  nDailyTarget: 'Mục tiêu ngày',
  nGoal: 'Mục tiêu',
  nTrainingLevel: 'Trình độ tập',
  nAbout: 'Thông tin',
  nVersion: 'Phiên bản',
  nSignOut: 'Đăng xuất',
  nSignOutConfirm: 'Bạn chắc chắn muốn đăng xuất?',
  nCancel: 'Huỷ',

  nSignInSubtitle: 'Đăng nhập để tiếp tục',
  nSignUpSubtitle: 'Tạo tài khoản của bạn',
  nYourName: 'Tên của bạn',
  nEmail: 'Email',
  nPassword: 'Mật khẩu',
  nSignIn: 'Đăng nhập',
  nSignUp: 'Đăng ký',
  nNoAccount: 'Chưa có tài khoản? ',
  nHaveAccount: 'Đã có tài khoản? ',

  nAskCoach: 'Hỏi huấn luyện viên',
  nAskCoachHint: 'Tập luyện, dinh dưỡng, phục hồi — trả lời dựa trên dữ liệu thật của bạn',
  nMessageCoach: 'Nhắn cho coach…',
  nHistory: 'Lịch sử',
  nNoHistory: 'Chưa có hội thoại nào',

  nAwards: 'Thành tích',
  nNoAwards: 'Chưa có thành tích nào',
  nNoAwardsHint: 'Cứ ghi chép đều — thành tích sẽ tự mở khoá',
  nChallenges: 'Thử thách',
  nNoChallenges: 'Tuần này chưa có thử thách',
  nNoChallengesHint: 'Thử thách tuần xuất hiện khi bạn bắt đầu ghi chép',
  nCompleted: 'Hoàn thành',
  nChallengeDone: 'Hoàn thành thử thách',
  nGrocery: 'Danh sách đi chợ',
  nAddItem: 'Thêm món cần mua…',
  nGroceryLeft: 'còn {n} món',
  nNoGrocery: 'Danh sách trống',
  nNoGroceryHint: 'Thêm nguyên liệu bạn cần mua',

  nSupplements: 'Thực phẩm bổ sung',
  nTakenToday: 'đã uống hôm nay',
  nWeightTitle: 'Ghi cân nặng',
  nLogWeight: 'Ghi',
  nAllSupplementsDone: 'Hôm nay uống đủ rồi',
  nReadinessTrend: 'Xu hướng sẵn sàng',
  nSmartTips: 'Gợi ý thông minh',
  nTipsHint: 'AI phân tích từ dữ liệu gần đây của bạn',
  nTipsLoading: 'Đang đọc xu hướng…',
  nTipsRefresh: 'Làm mới',
  nTipsEmpty: 'Ghi thêm để mở khoá gợi ý',
  // read failed — deliberately not the same words as an empty day
  // Cố ý không nhắc "hôm nay": thẻ này còn hiện ở Tiến trình và Buổi tập.
  nLoadFailed: 'Không tải được dữ liệu',
  nLoadFailedHint: 'Dữ liệu của bạn vẫn an toàn, chỉ là app chưa lấy được.',
  nCalibrateHint:
    'Đo tiêu hao thật của bạn từ lượng ăn và biến động cân nặng, rồi đề xuất mục tiêu calo khớp với nó.',
  nRetry: 'Thử lại',
  // ── tên cho trình đọc màn hình, nút chỉ có icon ──
  a11yBack: 'Quay lại',
  a11yClose: 'Đóng',
  a11yDismiss: 'Bỏ qua',
  a11yDelete: 'Xoá',
  a11yEdit: 'Sửa',
  a11yAdd: 'Thêm',
  a11yMore: 'Thêm tuỳ chọn',
  a11yIncrease: 'Tăng',
  a11yDecrease: 'Giảm',
  a11ySettings: 'Mở cài đặt',
  a11ySearch: 'Tìm kiếm',
  a11yClearSearch: 'Xoá ô tìm kiếm',
  a11yLogMeal: 'Ghi bữa ăn',
  a11yAskCoach: 'Hỏi huấn luyện viên',
  a11yCloseCoach: 'Đóng huấn luyện viên',
  a11yFavourite: 'Bật/tắt yêu thích',
  a11yTakePhoto: 'Chụp ảnh',
  a11ySwitchCamera: 'Đổi camera',
  a11yPrevWeek: 'Tuần trước',
  a11yNextWeek: 'Tuần sau',
  a11yEditGoal: 'Sửa mục tiêu',
  a11yOpenRoom: 'Mở phòng của Koa',
  a11yCheckOff: 'Đánh dấu đã dùng',
  a11yExpand: 'Xem chi tiết',
  a11ySend: 'Gửi tin nhắn',
  a11yHistory: 'Lịch sử trò chuyện',
  a11yNewChat: 'Cuộc trò chuyện mới',
  a11yShare: 'Chia sẻ',
  a11yScanFood: 'Quét món ăn bằng camera',
  a11yScanBarcode: 'Quét mã vạch',
  a11yRemove: 'Bỏ khỏi danh sách',
  a11yEditLayout: 'Sắp xếp lại bảng điều khiển',
  a11yDoneEditing: 'Xong sắp xếp',
  a11yAcceptTerms: 'Đồng ý điều khoản',
  a11yMoveUp: 'Chuyển lên',
  a11yMoveDown: 'Chuyển xuống',
  a11ySleepQuality: 'Chất lượng giấc ngủ {x} trên 5',
  // ── xoá tài khoản ──
  nDeleteAccount: 'Xoá tài khoản',
  nDeleteAccountDesc: 'Xoá vĩnh viễn tài khoản và toàn bộ dữ liệu trong đó',
  nDeleteAccountTitle: 'Xoá tài khoản của bạn?',
  nDeleteAccountBody:
    'Thao tác này xoá sạch bữa ăn, buổi tập, giấc ngủ, cân nặng và tủ đồ của Koa. Không thể hoàn tác. Hãy xuất dữ liệu trước nếu bạn muốn giữ lại.',
  nDeleteAccountConfirm: 'Xoá tất cả',
  nDeleteAccountDone: 'Tài khoản của bạn đã được xoá.',
  nDeleteAccountNotSetUp: 'Máy chủ chưa bật chức năng xoá tài khoản.',
  nDeleteAccountFailed: 'Không xoá được tài khoản. Chưa có gì bị xoá.',
  a11yPrevItem: 'Món trước',
  a11yNextItem: 'Món sau',
  a11yAddWater: 'Thêm {x} {unit}',
  // ── lịch sử cân nặng và sửa sai ──
  nWeightHistory: 'Cân nặng đã ghi',
  nWeightEntries: '{n} lần',
  nWeightEntriesOne: '1 lần',
  nWeightSeeAll: 'Xem tất cả {n} lần ghi',
  nDeleteWeight: 'Xoá số cân này',
  nDeleteWeightMsg: 'Xoá bản ghi {x}? Biểu đồ và BMI sẽ được tính lại.',
  // ── buổi tập đã ghi và sửa sai ──
  nDeleteSession: 'Xoá buổi tập này',
  nDeleteSessionMsg: 'Xoá {x}? Khối lượng tập và điểm sẵn sàng sẽ được tính lại.',
  // AI edge functions — one message per distinct cause, so wiring a new
  // Supabase project up tells you what is missing instead of "it failed"
  aiNotDeployed: 'Tính năng AI này chưa được cài trên máy chủ.',
  aiProviderError: 'Dịch vụ AI chưa trả lời được. Thử lại sau một lát nhé.',
  aiSignedOut: 'Bạn cần đăng nhập lại để dùng tính năng AI.',
  aiOffline: 'Không có kết nối — AI cần internet.',
  aiRateLimited: 'Bạn đã dùng hết lượt AI lúc này. Thử lại sau nhé.',
  aiUnknown: 'Có lỗi khi gọi AI.',
  nDiaryLoadFailed: 'Không tải được các bữa ăn',
  nNoSupplements: 'Chưa có supplement nào',
  nNoSupplementsHint: 'Thêm stack của bạn trên bản web — checklist sẽ đồng bộ về đây',
  nExercises: 'Thư viện bài tập',
  nSearchExercises: 'Tìm bài tập…',
  nNoExercises: 'Không tìm thấy bài tập',
  nNoExercisesHint: 'Thư viện bài tập đồng bộ từ bản web',
  nRoutine: 'Lịch tập tuần',
  nRest: 'Nghỉ',
  nDeload: 'Deload',
  nChooseWorkout: 'Chọn buổi tập',
  nRoutineHint: 'Chạm vào một ngày để gán buổi tập, đánh dấu nghỉ, hoặc bật deload',
  nRoutineDone: 'Hoàn thành',
  nRoutineTodo: 'Chờ tập',
  nRoutineMissed: 'Chưa tập',
  nRoutineRestDay: 'Nghỉ ngơi',
  nRoutineRestHint: 'Nghỉ ngơi hoặc vận động nhẹ',
  nRoutineExercises: '{n} bài tập',
  nRoutineMinutes: '{n} phút',
  nRoutineEffort: 'RPE {x}',
  nRoutineEffortRange: 'RPE {a}–{b}',
  nRoutineToday: 'Hôm nay',
  nRoutineNoTemplates: 'Chưa lưu buổi tập nào — tạo một cái trước đã.',
  nRdSet: 'Set {n}',
  nRdProgress: '{done}/{total} set',
  nRdFinish: 'Hoàn thành buổi tập',
  nRdResting: 'Nghỉ',
  nRdSkip: 'Bỏ qua',
  nRdEmptyPlan: 'Ngày này chưa có buổi tập nào',
  nRdSaved: 'Đã ghi buổi tập',
  nRdBodyweight: 'Không tạ',
  nRdAlready: 'Đã ghi buổi tập',
  nRdLoggedAt: 'lúc {t}',
  nRdPlanToday: 'Theo lịch hôm nay',
  nRdUsePlan: 'Dùng',
  nMealPlans: 'Kế hoạch ăn',
  nMealPlanNone: 'Chưa có thực đơn nào',
  nMealPlanWhat: 'Thực đơn là vài ngày ăn được viết sẵn, để câu "hôm nay ăn gì" đã có câu trả lời từ trước.',
  nMealPlanNew: 'Tạo kế hoạch ăn',
  nMealPlanOpen: 'Mở',
  nMealsPerDay: 'bữa/ngày',
  nDay: 'Ngày',
  nNoMealPlans: 'Chưa có kế hoạch ăn',
  nMpAddFood: 'Thêm món',
  nMpStepPlanHint: 'Tên bạn sẽ gọi kế hoạch này khi quay lại',
  nMpStepSlotsHint: 'Mỗi ngày trong kế hoạch có mấy bữa',
  nMpPlanNameEg: 'VD: Meal Prep Tuần 1',
  nMpNextAddFood: 'Tạo rồi thêm món',
  nExNameHint: 'Tên bạn sẽ gõ để tìm khi thêm vào buổi tập',
  nExGroupHint: 'Bài này nằm ở nhóm nào trong thư viện',
  nExGearHint: 'Không bắt buộc — tạ đòn, tạ đơn, máy, hoặc không gì cả',
  nMpStepPlan: 'Kế hoạch',
  nMpStepDay: 'Ngày',
  nMpStepMeal: 'Bữa',
  nMpStepFood: 'Món',
  nMpStepDayHint: 'Món này thuộc ngày nào trong kế hoạch',
  nMpStepMealHint: 'Bữa nào trong ngày đó',
  nMpStepFoodHint: 'Tìm rồi chạm để thêm. Bảng không đóng lại — một bữa hiếm khi chỉ có một món.',
  nMpAddTitle: 'Thêm món',
  nMpAddedN: 'Đã thêm {n}',
  nMpDone: 'Xong',
  nMpPickFood: 'Chọn món',
  nMpEmptyDay: 'Chưa có món nào',
  nMpAvgPerDay: '{x} kcal/ngày',
  nMpTarget: 'mục tiêu {x}',
  nMpPctTarget: '{p}% mục tiêu',
  nMpDayEmptyHint: 'Ngày này chưa có món nào.',
  nMpPlanEmpty: 'Kế hoạch này chưa có món nào',
  nMpWeekTotal: '{x} kcal cả tuần',
  nMpFromList: 'Từ danh sách của bạn',
  nMpNoMatch: 'Không có món nào khớp “{x}”',
  nMpAlready: 'đã thêm',
  nMpEatIt: 'Ghi vào hôm nay',
  nMpEaten: 'Có trong hôm nay',
  nMpAgainTitle: 'Hôm nay đã có rồi',
  nMpAgainBody: 'Nhật ký hôm nay đã có một bữa {m} đúng các món này. Ghi thêm lần nữa?',
  nMpAgainYes: 'Ghi thêm',
  nMpEatDone: 'Đã thêm {m} vào nhật ký hôm nay',
  nMpNoFibre: 'Ghi từ kế hoạch thì không có chất xơ — kế hoạch không lưu số đó.',
  // Ăn lại bữa đã ăn
  nRmTitle: 'Ăn lại bữa này',
  nRmHint: 'Điền sẵn vào form — xem lại rồi lưu.',
  nRmYesterday: 'hôm qua',
  nRmToday: 'hôm nay',
  nRmDaysAgo: '{n} ngày trước',
  nRmFoods: '{n} món',
  nWeeklyReview: 'Tổng kết tuần',
  nAiAnalysis: 'Phân tích AI',
  nWeeklyReviewHint: 'Để AI phân tích tuần của bạn và đưa gợi ý cho tuần tới',
  nAnalyzeWeek: 'Phân tích với AI',
  nWeekScore: 'Điểm tuần',

  nMascotTitle: 'Bạn đồng hành',
  nMascotToggleHint: 'Linh vật sẽ nhắc bạn dựa trên dữ liệu hôm nay',
  nMascotSleep: 'Chào buổi sáng! Đêm qua ngủ sao rồi? Ghi lại để mình tính điểm sẵn sàng nhé 😴',
  nMascotMeal: 'Hôm nay chưa ghi bữa nào — nạp năng lượng rồi ghi lại nha! 🍽',
  nMascotWater: 'Kiểm tra nước nè — bạn mới uống chưa được nửa mục tiêu 💧',
  nMascotWorkout: 'Giờ này tập là đẹp đó. Sẵn sàng chưa? 💪',
  nMascotPraise: 'Hôm nay bạn làm tốt lắm. Giữ vững phong độ nha! 🔥',
  nMascotHello: 'Mình đang theo dõi chỉ số của bạn — ghi gì đó đi, mình cổ vũ!',
  // ── Koa naming what you did, then what is left ──
  // Short on purpose: the two get joined into one speech bubble, and a bubble
  // people actually read is one line.
  nMascotWinSleep: 'Ghi giấc ngủ rồi 😴',
  nMascotWinMeal: 'Có ghi bữa rồi 🍽',
  nMascotWinWater: 'Đủ nước rồi 💧',
  nMascotWinWorkout: 'Tập xong rồi 💪',
  nMascotGapSleep: 'ghi thêm đêm qua nữa nhé',
  nMascotGapMeal: 'ghi bữa ăn nữa nha',
  nMascotGapWater: 'uống thêm nước đi',
  nMascotGapWorkout: 'tập một buổi nữa là đẹp',
  nMascotThen: '{win} — {gap}',
  nMascotLocked: 'Chưa mở khoá',
  nMascotPro: 'PRO · sắp ra mắt',
  nMascotUnlockedBadge: 'Đã mở khoá',
  nMascotUnlockedTitle: 'Mở khoá nhân vật mới!',
  nMascotUse: 'Dùng ngay',
  nMascotLater: 'Để sau',

  nCameraNeeded: 'Cần quyền camera',
  nCameraHint: 'ASCND quét mã vạch để ghi thực phẩm đóng gói tức thì',
  nAllowCamera: 'Cho phép Camera',
  nPointBarcode: 'Hướng camera vào mã vạch',
  nLookingUp: 'Đang tra cứu sản phẩm…',
  nNotFound: 'Không tìm thấy — thử lại',

  // AI food scan
  nScanFood: 'Quét món ăn',
  nAiScanTitle: 'Quét món bằng AI',
  nScanModeFood: 'Món ăn',
  nScanModeLabel: 'Nhãn',
  nScanFoodHint: 'Hướng vào bữa ăn rồi nhấn chụp',
  nScanLabelHint: 'Đưa bảng thành phần dinh dưỡng vào khung',
  nAnalyzing: 'Đang phân tích…',
  nScanNoFood: 'Không nhận ra món ăn — thử lại',
  nScanFromPhoto: 'Ước tính từ ảnh — khẩu phần là phỏng đoán. Kiểm lại trước khi thêm.',
  nScanFromLabel: 'Đọc từ bảng dinh dưỡng.',
  nScanRetake: 'Chụp lại',
  nScanAdd: 'Thêm {n} món',
  nScanAddOne: 'Thêm 1 món',
  nRetake: 'Chụp lại',
  nScanError: 'Quét thất bại — thử lại',

  nLegal: 'Chính sách & Pháp lý',
  nTemplates: 'Mẫu buổi tập',
  nTemplateName: 'Tên mẫu',
  nCreateExercise: 'Bài tập mới',
  nMuscleGroup: 'Nhóm cơ',
  nEquipment: 'Dụng cụ',
  nExerciseName: 'Tên bài tập',
  nNoExercisesFound: 'Không tìm thấy bài tập',
  nSuggestions: 'Gợi ý',
  nRestSec: 'Nghỉ',
  nDeleteTemplate: 'Xoá mẫu này?',

  // Workout builder — the two-step flow
  nWbTitle: 'Buổi tập mới',
  nWbStepPick: 'Chọn bài tập',
  nWbStepReview: 'Số set & tên',
  nWbPickHint: 'Chạm vào bài bạn muốn tập. Số set và rep chỉnh ở bước sau.',
  nWbAll: 'Tất cả',
  nWbSelected: 'Đã chọn {n}',
  nWbNext: 'Tiếp',
  nWbNoMatch: 'Không có bài nào khớp “{x}”',
  nWbCreateNamed: 'Tạo “{x}”',
  nWbLibraryEmpty: 'Thư viện bài tập đang trống',
  nWbAddMore: 'Thêm bài tập',
  nWbSummary: '{n} bài · {s} set · khoảng {m} phút',
  nWbNameHint: 'Tên đặt theo nhóm cơ bạn chọn — đổi lại nếu muốn.',
  nWbNameOne: 'Tập {x}',
  nWbNameTwo: '{a} & {b}',
  nWbType: 'Kiểu buổi tập',
  nWbSave: 'Lưu buổi tập',
  nWbSets: 'Số set',
  nWbReps: 'Số rep',
  nWbLoad: 'Mức tạ',
  nWbBodyweight: 'Không tạ',
  nWbRest: 'Nghỉ giữa các set',
  nWbEffort: 'Độ gắng sức',
  nWbEffortHint: 'Rep cuối nên nặng cỡ nào. 10 là hết sức.',

  // Saved workout card — rest and effort read back
  nTplRest: 'Nghỉ {x}',
  nTplNoRest: 'Không nghỉ',
  nTplEffort: 'Gắng sức {x}/10',
  nWbMoveUp: 'Đưa lên trước',
  nWbMoveDown: 'Đưa xuống sau',
  nWbRemove: 'Bỏ khỏi buổi tập',
  nWbDone: 'Xong',
  nWbTypePush: 'Đẩy',
  nWbTypePull: 'Kéo',
  nWbTypeLegs: 'Chân',
  nWbTypeUpper: 'Thân trên',
  nWbTypeLower: 'Thân dưới',
  nWbTypeFullBody: 'Toàn thân',
  nWbTypeStrength: 'Sức mạnh',
  nWbTypeHypertrophy: 'Phì đại cơ',
  nWbTypeCardio: 'Cardio',
  nWbTypeCustom: 'Tuỳ chỉnh',

  // Water & Steps detail
  nWaterTitle: 'Nước uống',
  nStepsTitle: 'Bước chân',
  nLast7Days: '7 ngày qua',
  nAverage: 'Trung bình',
  nRangeWeek: 'Tuần',
  nRangeMonth: 'Tháng',
  nRangeYear: 'Năm',
  nRangeAll: 'Tất cả',
  nDailyAvg: 'Trung bình ngày',
  nTodayTotal: 'Hôm nay',
  nTodayLogs: 'Nhật ký hôm nay',
  nStepsGoal: 'Mục tiêu {x}',
  nQuickAdd: 'Thêm nhanh',
  // manual entry, for the amounts the presets do not cover
  nWaterCustom: 'Lượng khác',
  nWaterEntries: '{n} lần',
  nWaterEntriesOne: '1 lần',
  nWaterCustomTitle: 'Bạn đã uống bao nhiêu?',
  nWaterTooMuch: 'Nhiều hơn {x} trong một lần — kiểm tra lại số nhé',

  // Progress photos
  nPhotoFront: 'Trước',
  nPhotoSide: 'Nghiêng',
  nPhotoBack: 'Sau',
  nPhotoUploading: 'Đang tải lên…',
  nPhotoDelete: 'Xoá ảnh?',
  nPhotoAdd: 'Thêm ảnh tiến trình',
  nPhotoCapture: 'Chụp',

  // Today's diary — collapsed meal cards + quick stats
  nDiaryItems: '{n} món',
  nDiaryItemsOne: '1 món',
  nDiaryEntries: '{n} bữa',
  // editing what is already logged
  nItemEdit: 'Sửa khẩu phần',
  nItemDelete: 'Xoá khỏi nhật ký',
  nItemDeleteMsg: 'Xoá {name} khỏi nhật ký hôm nay?',
  nItemServings: 'Khẩu phần',
  nServingsMore: 'Tăng khẩu phần',
  nServingsLess: 'Giảm khẩu phần',
  nItemUpdated: 'Đã cập nhật nhật ký',
  nQuickCalories: 'Calo',
  nQuickProtein: 'Protein',
  nQuickWater: 'Nước',

  // Weight changes card (Progress)
  nWeightChanges: 'Thay đổi cân nặng',
  nWcDays: '{n} ngày',
  nWcAllTime: 'Toàn bộ',
  nWcNoChange: 'Không đổi',
  nWcIncrease: 'Tăng',
  nWcDecrease: 'Giảm',
  nWcNoData: 'Ghi cân nặng để xem thay đổi ở đây',

  // Weight goal (Progress weight chart)
  nQuickActions: 'Thao tác nhanh',
  nHealthAssistant: 'Trợ lý sức khoẻ',
  nQuickActionsClose: 'Đóng thao tác nhanh',
  nWeightGoal: 'Mục tiêu',
  nWeightGoalSet: 'Đặt cân nặng mục tiêu',
  nWeightGoalTitle: 'Cân nặng mục tiêu',
  nWeightGoalEdit: 'Sửa mục tiêu cân nặng',
  nWeightGoalDone: 'Xong',
  nWeightGoalGain: 'Tăng cân',
  nWeightGoalLose: 'Giảm cân',
  nWeightGoalMaintain: 'Giữ cân',
  nWeightGoalClear: 'Xoá',
  nWeightGoalToGo: 'còn {x}',
  nWeightGoalReached: 'Đã đạt mục tiêu',

  // Bốn cách ghi một bữa ăn — xem chú thích ở bản tiếng Anh
  nWayPhoto: 'Chụp ảnh',
  nWayBarcode: 'Mã vạch',
  nWaySearch: 'Tìm món',
  nWayManual: 'Nhập tay',
  nAddCamera: 'Quét bữa ăn',
  nAddBarcode: 'Quét mã vạch',
  nAddSearch: 'Tìm thực phẩm',
  nAddManual: 'Nhập tay số liệu',

  // Meal builder
  nMealItems: 'Các món',
  nMealNoItems: 'Tìm, quét hoặc thêm món để bắt đầu',
  nNutritionTotal: 'Tổng dinh dưỡng',
  nServings: 'Khẩu phần',
  nAiSuggest: 'AI gợi ý',
  nAiSuggestTitle: 'AI gợi ý bữa ăn',
  nAiSuggestHint: 'Dựa trên lượng macro còn lại hôm nay',
  nAiThinking: 'Đang nghĩ món…',
  nAddThis: 'Thêm',
  nPrepTime: '{n} phút',
  nAiNoIdeas: 'Chưa có gợi ý — thử lại sau',

  // Reminders (local notifications)
  nRemindersTitle: 'Nhắc nhở',
  nRemindersDesc: 'Nhắc mỗi ngày để giữ chuỗi thói quen',
  nRemindersEnable: 'Cho phép thông báo',
  nRemindersDenied: 'Thông báo đang tắt. Bật trong Cài đặt iOS › ASCND.',
  nReminderWater: 'Uống nước',
  nReminderWaterBody: 'Đến giờ uống một cốc nước rồi 💧',
  nReminderSupplements: 'Thực phẩm bổ sung',
  nReminderSupplementsBody: 'Nhớ uống thực phẩm bổ sung 💊',
  nReminderBedtime: 'Chuẩn bị ngủ',
  nReminderBedtimeBody: 'Sắp đến giờ ngủ — thư giãn thôi 😴',
  nReminderWeighIn: 'Cân buổi sáng',
  nReminderWeighInBody: 'Ghi cân nặng trước bữa sáng ⚖️',
  nReminderWorkout: 'Tập hôm nay',
  nReminderWorkoutBody: 'Lịch của bạn có buổi tập hôm nay 💪',
  nReminderTime: 'Giờ',
  nReminderEveryHours: 'Mỗi {n} giờ',

  // Offline
  nOffline: 'Ngoại tuyến — đang hiển thị dữ liệu đã lưu',
  nHealthSynced: 'Đã đồng bộ Apple Health!',

  // Mascot room
  nRoomQuests: 'Nhiệm vụ hôm nay',
  nRoomQuestsHint: 'Tập, ăn, uống nước — kiếm xu cho bạn đồng hành',
  nRoomWeeklyBonus: 'Thưởng thử thách tuần',
  nRoomShop: 'Cửa hàng',
  nRoomDressing: 'Phòng thay đồ',
  nRoomOverview: 'Toàn cảnh',
  nRoomOverviewHint: 'Chọn một góc phòng ở trên.',
  nRoomOutfits: 'Trang phục',
  nRoomCloset: 'Tủ đồ',
  nRoomGymGear: 'Đồ phòng gym',
  nRoomStageSkins: 'Sân khấu',
  nRoomUse: 'Dùng',
  nRoomUsing: 'Đang dùng',
  nRoomClaim: 'Nhận',
  nRoomClaimed: 'Đã nhận',
  nRoomBuy: 'Mua',
  nRoomWear: 'Mặc',
  nRoomTakeOff: 'Cởi',
  nRoomWearing: 'Đang mặc',
  nRoomPlaced: 'Đã đặt trong phòng',
  nRoomPlace: 'Đặt vào',
  nRoomAll: 'Tất cả',
  nRoomOwned: 'Đã sở hữu',
  nRoomLockLevel: 'Lv.{n}',
  nRoomCollections: 'Bộ sưu tập',
  nRoomCollectionsHint: 'Thu thập đủ bộ để nhận thưởng đặc biệt!',
  nRoomSetProgress: 'Đã có {a}/{b}',
  nRoomSetDone: 'Đủ bộ!',
  nRoomEmptyCat: 'Sắp có thêm đồ',
  nRoomSetClaimed: 'Đã nhận thưởng',
  nRoomNotEnough: 'Chưa đủ xu — hoàn thành thêm nhiệm vụ nhé!',
  nRoomCoins: 'xu',
  nRoomEarned: '+{n} xu!',
  nRoomBought: 'Đã mua!',
  nRoomUpgrades: 'Nâng cấp phòng',
  nRoomInstalled: 'Đã lắp đặt',
  nRoomStreak: 'Chuỗi {n} ngày',
  nRoomLearned: 'Koa để ý: bạn thường ghi {what} vào khoảng {time}',
  nFreezeTitle: 'Bảo hiểm chuỗi',
  nFreezeHeld: 'Đang có {n}/{max}',
  nFreezeHint: 'Tự bù một ngày lỡ. Koa chỉ dùng khi nó thật sự cứu được chuỗi.',
  nFreezeBuy: 'Mua · {n}',
  nFreezeFull: 'Đã đầy',
  nFreezeSaved: 'Đã bù {n} ngày',
  nFreezeSavedPlural: 'Đã bù {n} ngày',
  nThingMeal: 'bữa ăn',
  nThingWorkout: 'buổi tập',
  nThingWater: 'nước uống',
  nThingSleep: 'giấc ngủ',
  nThingSteps: 'bước chân',
  nStreakLit: 'Chuỗi {n} ngày, hôm nay đã ghi',
  nStreakAtRisk: 'Chuỗi {n} ngày, hôm nay chưa ghi gì',
  nStageStreak: 'Ngày streak',
  nStageQuests: 'Nhiệm vụ',
  nRoomLevel: 'Cấp {n}',
  nRoomLevelHint: 'Còn {n} XP tới cấp tiếp theo',
  nRoomLevelUp: 'Lên cấp! Bạn đồng hành đạt cấp {n}',
  nRoomMoodTired: 'Hôm nay tớ uể oải quá… ghi một bữa ăn hoặc tập một chút cho tớ tỉnh nhé!',
  nRoomWardrobe: 'Tủ đồ',
  nRoomChangeBuddy: 'Đổi linh vật',
  nRoomWelcome: 'Quà chào mừng: +{n} xu!',
  // Rank ladder
  nRoomNextRank: 'Tiếp theo: {r} ở cấp {n}',
  nRoomMaxRank: 'Đã đạt danh hiệu cao nhất — huyền thoại!',
  nRoomRankUp: 'Mở danh hiệu mới: {r}!',
  nRoomJourney: 'Hành trình',
  nRoomLevelsToRank: 'Còn {n} cấp tới {r}',
  // Today's energy
  nRoomEnergy: 'Năng lượng hôm nay',
  nRoomEnergyEmpty: 'Đang cạn năng lượng — ghi bữa ăn hoặc buổi tập để đánh thức tớ nhé.',
  nRoomEnergyLow: 'Vừa khởi động — tiếp tục nào!',
  nRoomEnergyMid: 'Đang khoẻ dần — còn vài mục nữa thôi.',
  nRoomEnergyFull: 'Nạp đầy năng lượng! Hoàn thành mọi mục tiêu hôm nay.',
  nRoomSigMeal: 'Ăn',
  nRoomSigWorkout: 'Tập',
  nRoomSigWater: 'Nước',
  nRoomSigSleep: 'Ngủ',
  nRoomSigSteps: 'Bước',

  // App lock (Face ID / sinh trắc)
  nLockTitle: 'Khoá ứng dụng',
  nLockDesc: 'Yêu cầu Face ID để mở ASCND',
  nLockUnavailable: 'Thiết bị không hỗ trợ khoá sinh trắc',
  nLockPrompt: 'Mở khoá ASCND',
  nLockLocked: 'ASCND đang khoá',
  nLockUnlock: 'Mở khoá',
};

export const nativeStrings: Record<AppLang, typeof en> = { vi, en };
export type NativeStrings = typeof en;
