"""Các ca phá thử của B (#14), đưa vào repo ở #25. Mỗi ca: phá ĐÚNG MỘT chốt
trên bản sao migration, và đòi câu ASSERT đỏ đầu tiên của bộ đích chứa
`expect`. Chép nguyên văn từ bình luận của B ở #25 (88 ca, 88/88 trên
`53c9b89`); chạy bằng `b_reverse.py`.

  green_ok=True   PHẢI xanh — còn một lớp bảo vệ dự phòng (15a, R13a)
  extra / also    phá thêm chỗ khác, trong cùng / một migration khác
  nth             lần xuất hiện thứ mấy; 'all' là thay mọi chỗ
"""
F = 'foundation'
FM = 'community_foundation'
CASES = [
  # ── hồ sơ ──
  dict(suite=F, id='1', mig=FM, how='trigger không gạt is_official khi TẠO',
       old='      NEW.is_official := false;', new='      NULL;', expect='1 người thường'),
  dict(suite=F, id='2', mig=FM, how='trigger không giữ is_official khi SỬA',
       old='      NEW.is_official := OLD.is_official;', new='      NULL;', expect='2 người thường'),
  dict(suite=F, id='3', mig=FM, how='policy INSERT hồ sơ bỏ auth.uid() = user_id',
       old='  ON public.community_profiles FOR INSERT TO authenticated\n  WITH CHECK (auth.uid() = user_id);',
       new='  ON public.community_profiles FOR INSERT TO authenticated\n  WITH CHECK (true);', expect='3 tạo được'),
  dict(suite=F, id='4', mig=FM, how='bỏ CHECK định dạng handle',
       old="UNIQUE CHECK (handle ~ '^[a-z0-9_.]{3,24}$')", new='UNIQUE', expect='4 handle'),
  dict(suite=F, id='37', mig=FM, how='trigger gạt is_official cả với dashboard',
       old="  IF current_user IN ('authenticated', 'anon') THEN\n    IF TG_OP = 'INSERT' THEN",
       new="  IF true THEN\n    IF TG_OP = 'INSERT' THEN", expect='37 dashboard'),
  # ── chia sẻ ──
  dict(suite=F, id='5', mig=FM, how='thêm policy INSERT mở cho community_posts',
       old='CREATE POLICY "Authors delete their own posts"',
       new='CREATE POLICY "x_open_insert" ON public.community_posts FOR INSERT TO authenticated WITH CHECK (true);\nCREATE POLICY "Authors delete their own posts"',
       expect='5 client INSERT'),
  dict(suite=F, id='11', mig=FM, how='bỏ lọc set khởi động (vế này do 12 canh: set khởi động 20 kg không bao giờ là set nặng nhất)',
       old="    WHERE coalesce((e->>'warmup')::boolean, false) = false\n", new='', expect='12 set khởi động'),
  dict(suite=F, id='12', mig=FM, how='đếm cả set khởi động (giữ top set)',
       old='      count(*)                                          AS n_sets,',
       new="      count(*) + 1                                      AS n_sets,", expect='12 set khởi động'),
  dict(suite=F, id='14', mig=FM, how='coi mọi bài là thư viện',
       old="'library',      coalesce(x.user_id IS NULL AND x.id IS NOT NULL, false),",
       new="'library',      coalesce(x.id IS NOT NULL, false),", expect='14 bài tự tạo'),
  dict(suite=F, id='15a', mig=FM, how='bỏ chốt "đã chia sẻ" trong hàm — UNIQUE còn, nên PHẢI vẫn xanh (lớp dự phòng; 15b phá cả hai)', green_ok=True,
       old='  IF EXISTS (SELECT 1 FROM public.community_posts WHERE author_id = v_uid AND source_id = p_session_id) THEN',
       new='  IF false THEN', expect='15 chia sẻ trùng'),
  dict(suite=F, id='15b', mig=FM, how='bỏ CẢ chốt trong hàm LẪN UNIQUE(author_id, source_id)',
       old='  UNIQUE (author_id, source_id)', new='  CHECK (true)', expect='15 chia sẻ trùng', extra=[
         ('  IF EXISTS (SELECT 1 FROM public.community_posts WHERE author_id = v_uid AND source_id = p_session_id) THEN', '  IF false THEN')]),
  dict(suite=F, id='11b', mig=FM, how='set nặng nhất lấy reps THẤP nhất (24x8)',
       old='(array_agg(w ORDER BY w DESC, r DESC))[1]         AS top_w,\n      (array_agg(r ORDER BY w DESC, r DESC))[1]         AS top_r',
       new='(array_agg(w ORDER BY w DESC, r ASC))[1]         AS top_w,\n      (array_agg(r ORDER BY w DESC, r ASC))[1]         AS top_r', expect='11 set nặng nhất'),
  dict(suite=F, id='27b', mig=FM, how='ĐỐI CHỨNG: chặn mọi báo cáo người dùng',
       old="WITH CHECK (auth.uid() = reporter_id AND status = 'open');", new="WITH CHECK (auth.uid() = reporter_id AND status = 'open' AND reported_user_id IS NULL);", expect='27b'),
  dict(suite=F, id='16', mig=FM, how='bỏ lọc chủ buổi tập',
       old='WHERE id = p_session_id AND user_id = v_uid;', new='WHERE id = p_session_id;', expect='16 chia sẻ được'),
  dict(suite=F, id='18', mig=FM, how='không gạt phút ngoài 1..600',
       old="'minutes',       CASE WHEN p_minutes BETWEEN 1 AND 600 THEN p_minutes END,",
       new="'minutes',       p_minutes,", expect='18 phút'),
  # ── người xem ──
  dict(suite=F, id='19', mig=FM, how='bài "followers" hiện với mọi người',
       old="        visibility = 'public'\n        OR EXISTS", new="        true\n        OR EXISTS", expect='19 B phải thấy'),
  dict(suite=F, id='20', mig=FM, how='bỏ nhánh "đang theo dõi" của policy đọc bài',
       old='WHERE f.follower_id = auth.uid() AND f.followee_id = community_posts.author_id',
       new='WHERE false', expect='20 theo dõi rồi'),
  dict(suite=F, id='21', mig=FM, how='thêm policy UPDATE mở cho community_posts',
       old='CREATE POLICY "Authors delete their own posts"',
       new='CREATE POLICY "x_open_update" ON public.community_posts FOR UPDATE TO authenticated USING (true) WITH CHECK (true);\nCREATE POLICY "Authors delete their own posts"',
       expect='21 người xem sửa'),
  dict(suite=F, id='22', mig=FM, how='bỏ trigger đếm bình luận',
       old='CREATE TRIGGER community_comments_count\n  AFTER INSERT OR DELETE ON public.community_comments\n  FOR EACH ROW EXECUTE FUNCTION public.community_count_bump();',
       new='', expect='22 bộ đếm'),
  # ── chặn ──
  dict(suite=F, id='23', mig=FM, how='policy đọc bài bỏ vế chặn',
       old='      AND NOT public.community_blocked_between(auth.uid(), author_id)\n      AND (\n        visibility',
       new='      AND (\n        visibility', expect='23 người BỊ chặn'),
  dict(suite=F, id='24', mig=FM, how='trigger chặn không gỡ theo dõi',
       old='  DELETE FROM public.community_follows\n  WHERE (follower_id = NEW.blocker_id AND followee_id = NEW.blocked_id)\n     OR (follower_id = NEW.blocked_id AND followee_id = NEW.blocker_id);',
       new='  NULL;', expect='24 chặn không gỡ'),
  dict(suite=F, id='25', mig=FM, how='policy theo dõi bỏ vế chặn',
       old='WITH CHECK (auth.uid() = follower_id AND NOT public.community_blocked_between(follower_id, followee_id));',
       new='WITH CHECK (auth.uid() = follower_id);', expect='25 theo dõi lại'),
  dict(suite=F, id='26', mig=FM, how='ai cũng đọc được dòng chặn',
       old='ON public.community_blocks FOR SELECT TO authenticated USING (auth.uid() = blocker_id);',
       new='ON public.community_blocks FOR SELECT TO authenticated USING (true);', expect='26 người bị chặn đọc'),
  # ── báo cáo ──
  dict(suite=F, id='27', mig=FM, how="policy báo cáo bỏ status = 'open'",
       old="WITH CHECK (auth.uid() = reporter_id AND status = 'open');",
       new='WITH CHECK (auth.uid() = reporter_id);', expect='27 tự đóng'),
  dict(suite=F, id='28', mig=FM, how='ngưỡng tự ẩn bài hạ xuống 2',
       old='WHERE post_id = NEW.post_id\n  ) >= 3 THEN', new='WHERE post_id = NEW.post_id\n  ) >= 2 THEN', expect='28 hai báo cáo'),
  dict(suite=F, id='29', mig=FM, how='ngưỡng tự ẩn bài nâng lên 4',
       old='WHERE post_id = NEW.post_id\n  ) >= 3 THEN', new='WHERE post_id = NEW.post_id\n  ) >= 4 THEN', expect='29 ba người'),
  dict(suite=F, id='30', mig=FM, how='policy đọc bài bỏ NOT hidden',
       old='    OR (\n      NOT hidden\n      AND NOT public.community_blocked_between(auth.uid(), author_id)\n      AND (\n        visibility',
       new='    OR (\n      true\n      AND NOT public.community_blocked_between(auth.uid(), author_id)\n      AND (\n        visibility',
       expect='30 bài đã ẩn'),
  dict(suite=F, id='31', mig=FM, how='ai cũng đọc được báo cáo',
       old='ON public.community_reports FOR SELECT TO authenticated USING (auth.uid() = reporter_id);',
       new='ON public.community_reports FOR SELECT TO authenticated USING (true);', expect='31 đọc được báo cáo'),
  dict(suite=F, id='32', mig=FM, how='policy đọc bài bỏ nhánh "của mình"',
       old='  USING (\n    author_id = auth.uid()\n    OR (\n      NOT hidden', new='  USING (\n    false\n    OR (\n      NOT hidden',
       expect='32 tác giả'),
  dict(suite=F, id='33', mig=FM, how='bình luận không còn FK/cascade về bài',
       old='  post_id    uuid NOT NULL REFERENCES public.community_posts(id) ON DELETE CASCADE,\n  author_id  uuid NOT NULL DEFAULT auth.uid()',
       new='  post_id    uuid NOT NULL,\n  author_id  uuid NOT NULL DEFAULT auth.uid()', expect='33 xoá bài'),
  # ── anon ──
  dict(suite=F, id='34', mig=FM, how='GRANT share_workout cho anon',
       old='REVOKE EXECUTE ON FUNCTION public.share_workout(uuid, text, text, integer) FROM PUBLIC, anon;',
       new='GRANT EXECUTE ON FUNCTION public.share_workout(uuid, text, text, integer) TO anon;', expect='34 anon'),
  dict(suite=F, id='35', mig=FM, how='policy đọc bài mở cho anon, bài công khai',
       old='CREATE POLICY "Authors delete their own posts"',
       new="CREATE POLICY \"x_anon_read\" ON public.community_posts FOR SELECT TO anon USING (visibility = 'public');\nCREATE POLICY \"Authors delete their own posts\"",
       expect='35 anon đọc'),
  # ── xoá tài khoản ──
  dict(suite=F, id='36', mig=FM, how='hồ sơ không còn FK/cascade về auth.users',
       old='  user_id      uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,',
       new='  user_id      uuid PRIMARY KEY,', expect='36 xoá tài khoản'),
]

P = 'progress'
PM = 'community_progress'
CASES += [
  dict(suite=P, id='P1', mig=PM, how='vòng eo luôn bật', old='  IF p_waist THEN', new='  IF true THEN', expect='P1 chỉ số TẮT'),
  dict(suite=P, id='P2', mig=PM, how='cân nặng bỏ lọc khoảng ngày',
       old='      WHERE user_id = v_uid AND date > v_from AND date <= v_to\n    ), wk AS (',
       new='      WHERE user_id = v_uid\n    ), wk AS (', expect='P2 đầu/cuối'),
  dict(suite=P, id='P5', mig=PM, how='cân nặng luôn bật', old='  IF p_weight THEN', new='  IF true THEN', expect='P5 cân nặng tắt'),
  dict(suite=P, id='P8', mig=PM, how='sức mạnh bỏ lọc set khởi động',
       old="          AND coalesce((e->>'warmup')::boolean, false) = false\n", new='', expect='P8 Bench'),
  dict(suite=P, id='P9', mig=PM, how='đọc được bài tự tạo của người khác (bỏ lọc chủ bài)',
       old='    WHERE id = p_lift_exercise_id AND (user_id IS NULL OR user_id = v_uid);',
       new='    WHERE id = p_lift_exercise_id;', expect='P9 đọc được'),
  dict(suite=P, id='P9b', mig=PM, how='sức mạnh bỏ lọc chủ BUỔI TẬP (đọc buổi của người khác)',
       old='        WHERE s.user_id = v_uid\n          AND (s.date_time', new='        WHERE true\n          AND (s.date_time', expect='P19 biểu đồ sức mạnh'),
  dict(suite=P, id='P10', mig=PM, how='bỏ chốt số tuần 1..52',
       old='  IF p_weeks IS NULL OR p_weeks NOT BETWEEN 1 AND 52 THEN', new='  IF false THEN', expect='P10 số tuần'),
  dict(suite=P, id='P10b', mig=PM, how='ĐỐI CHỨNG: trần số tuần hạ xuống 51',
       old='  IF p_weeks IS NULL OR p_weeks NOT BETWEEN 1 AND 52 THEN', new='  IF p_weeks IS NULL OR p_weeks NOT BETWEEN 1 AND 51 THEN', expect='P10b'),
  dict(suite=P, id='P11', mig=PM, how='bỏ chốt "không có gì để chia sẻ"',
       old='  IF v_w IS NULL AND v_waist IS NULL AND v_lift IS NULL THEN', new='  IF false THEN', expect='P11 không bật'),
  dict(suite=P, id='P12', mig=PM, how='share_progress bỏ chốt hồ sơ',
       old='  IF NOT EXISTS (SELECT 1 FROM public.community_profiles WHERE user_id = v_uid) THEN', new='  IF false THEN', expect='P12 đăng được'),
  dict(suite=P, id='P15', mig=PM, how='cân nặng: một điểm cũng thành "thay đổi"',
       old='    SELECT CASE WHEN (SELECT count(*) FROM pts) >= 2 THEN jsonb_build_object(', nth=1,
       new='    SELECT CASE WHEN (SELECT count(*) FROM pts) >= 1 THEN jsonb_build_object(', expect='P15 một điểm'),
  dict(suite=P, id='P16', mig=PM, how='cân nặng bỏ lọc user_id (bắt ở P15 trước — cùng lỗi; P16b đo riêng P16)',
       old='      WHERE user_id = v_uid AND date > v_from AND date <= v_to\n    ), wk AS (',
       new='      WHERE date > v_from AND date <= v_to\n    ), wk AS (', expect='P15 một điểm'),
  dict(suite=P, id='P16b', mig=PM, how='cân nặng rò dữ liệu người khác khi khoảng > 1 tuần (P15 không chạm tới)',
       old='      WHERE user_id = v_uid AND date > v_from AND date <= v_to\n    ), wk AS (',
       new='      WHERE (user_id = v_uid OR p_weeks > 1) AND date > v_from AND date <= v_to\n    ), wk AS (', expect='P16 payload của Q'),
  dict(suite=P, id='P17', mig=PM, how='GRANT build_progress_payload cho anon',
       old='REVOKE EXECUTE ON FUNCTION public.build_progress_payload(integer, boolean, boolean, uuid) FROM PUBLIC, anon;',
       new='GRANT EXECUTE ON FUNCTION public.build_progress_payload(integer, boolean, boolean, uuid) TO anon;', expect='P17 anon'),
  dict(suite=P, id='P18', mig=PM, how='GRANT share_progress cho anon',
       old='REVOKE EXECUTE ON FUNCTION public.share_progress(integer, boolean, boolean, uuid, text, text) FROM PUBLIC, anon;',
       new='GRANT EXECUTE ON FUNCTION public.share_progress(integer, boolean, boolean, uuid, text, text) TO anon;', expect='P18 anon'),
]

C = 'challenges'
CM = 'community_challenges'
CASES += [
  dict(suite=C, id='C1', mig=CM, how='thêm policy INSERT mở cho community_challenges',
       old='CREATE POLICY "Signed-in users can read challenges"',
       new='CREATE POLICY "x_open" ON public.community_challenges FOR INSERT TO authenticated WITH CHECK (true);\nCREATE POLICY "Signed-in users can read challenges"', expect='C1 client tạo'),
  dict(suite=C, id='C2', mig=CM, how='tham gia bỏ vế "còn mở"',
       old='    AND claimed_at IS NULL\n    AND EXISTS (SELECT 1 FROM public.community_challenges c WHERE c.id = challenge_id AND c.ends_on >= current_date)',
       new='    AND claimed_at IS NULL', expect='C2 tham gia được'),
  dict(suite=C, id='C3', mig=CM, how='tham gia bỏ vế claimed_at IS NULL',
       old='    auth.uid() = user_id\n    AND claimed_at IS NULL\n    AND EXISTS', new='    auth.uid() = user_id\n    AND EXISTS', expect='C3 tham gia kèm'),
  dict(suite=C, id='C4', mig=CM, how='thêm policy UPDATE mở cho thành viên',
       old='CREATE POLICY "Users leave unclaimed challenges"',
       new='CREATE POLICY "x_upd" ON public.community_challenge_members FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (true);\nCREATE POLICY "Users leave unclaimed challenges"', expect='C4 tự đánh dấu'),
  dict(suite=C, id='C6', mig=CM, how='đếm BUỔI thay vì NGÀY', old='  SELECT count(DISTINCT ((s.date_time', new='  SELECT count(((s.date_time', expect='C6 tiến độ'),
  dict(suite=C, id='C6b', mig=CM, how='bỏ lọc khoảng ngày của thử thách',
       old="    AND ((s.date_time AT TIME ZONE 'UTC') + make_interval(mins => greatest(-720, least(840, coalesce(p_offset_min, 0)))))::date\n        BETWEEN c.starts_on AND c.ends_on;",
       new='    ;', expect='C6 tiến độ'),
  dict(suite=C, id='C8', mig=CM, how='nhận thưởng bỏ chốt "đã đạt"',
       old='  IF public.community_challenge_progress(p_challenge, v_uid, p_offset_min) < c.target THEN', new='  IF false THEN', expect='C8 nhận thưởng khi chưa đạt'),
  dict(suite=C, id='C9', mig=CM, how='hàm đo tiến độ gọi được từ client',
       old='REVOKE EXECUTE ON FUNCTION public.community_challenge_progress(uuid, uuid, integer) FROM PUBLIC, anon, authenticated;',
       new='GRANT EXECUTE ON FUNCTION public.community_challenge_progress(uuid, uuid, integer) TO authenticated;', expect='C9 client gọi thẳng'),
  dict(suite=C, id='C10', mig=CM, how='ai cũng đọc được danh sách thành viên',
       old='ON public.community_challenge_members FOR SELECT TO authenticated USING (auth.uid() = user_id);',
       new='ON public.community_challenge_members FOR SELECT TO authenticated USING (true);', expect='C10 đọc được'),
  dict(suite=C, id='C13', mig=CM, how='bỏ chốt "đã nhận"', old='  IF v_claimed IS NOT NULL THEN', new='  IF false THEN', expect='C13 nhận thưởng HAI'),
  dict(suite=C, id='C14', mig=CM, how='rời được cả khi đã nhận',
       old='  USING (auth.uid() = user_id AND claimed_at IS NULL);', new='  USING (auth.uid() = user_id);', expect='C14 rời được'),
  dict(suite=C, id='C18', mig=CM, how='bỏ lệch múi giờ (đếm theo UTC)', nth='all',
       old='coalesce(p_offset_min, 0)', new='0', expect='C18 theo UTC+7'),
  dict(suite=C, id='C19', mig=CM, how='GRANT tổng quan cho anon',
       old='REVOKE EXECUTE ON FUNCTION public.community_challenges_overview(integer) FROM PUBLIC, anon;',
       new='GRANT EXECUTE ON FUNCTION public.community_challenges_overview(integer) TO anon;', expect='C19 anon'),
  dict(suite=C, id='C20', mig=CM, how='GRANT nhận thưởng cho anon',
       old='REVOKE EXECUTE ON FUNCTION public.claim_community_challenge(uuid, integer) FROM PUBLIC, anon;',
       new='GRANT EXECUTE ON FUNCTION public.claim_community_challenge(uuid, integer) TO anon;', expect='C20 anon'),
]

V = 'privacy'
VM = 'community_privacy'
CASES += [
  dict(suite=V, id='V2', mig=VM, how='ai cũng đọc được cài đặt',
       old='ON public.community_settings FOR SELECT TO authenticated USING (auth.uid() = user_id);',
       new='ON public.community_settings FOR SELECT TO authenticated USING (true);', expect='V2 đọc được'),
  dict(suite=V, id='V3', mig=VM, how='tạo cài đặt cho người khác',
       old='ON public.community_settings FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);',
       new='ON public.community_settings FOR INSERT TO authenticated WITH CHECK (true);', expect='V3 tạo được'),
  dict(suite=V, id='V4', mig=VM, how='policy UPDATE mở toang',
       old='  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);', new='  USING (true) WITH CHECK (true);', expect='V4 sửa được'),
  dict(suite=V, id='V5', mig=VM, how="bỏ CHECK giá trị hiển thị",
       old="DEFAULT 'public' CHECK (default_visibility IN ('public', 'followers')),", new="DEFAULT 'public',", expect='V5 giá trị'),
  dict(suite=V, id='V6', mig=VM, how='UPDATE bỏ WITH CHECK',
       old='  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);', new='  USING (auth.uid() = user_id) WITH CHECK (true);', expect='V6 chuyển được'),
  dict(suite=V, id='V7', mig=FM, how='ai cũng đọc được dòng chặn (policy ở nền móng)',
       old='ON public.community_blocks FOR SELECT TO authenticated USING (auth.uid() = blocker_id);',
       new='ON public.community_blocks FOR SELECT TO authenticated USING (true);', expect='V7 thấy được'),
  dict(suite=V, id='V9', mig=FM, how='bỏ chặn xoá được dòng của người khác (policy ở nền móng)',
       old='ON public.community_blocks FOR DELETE TO authenticated USING (auth.uid() = blocker_id);',
       new='ON public.community_blocks FOR DELETE TO authenticated USING (true);', expect='V9 bỏ chặn gỡ'),
  dict(suite=V, id='V12', mig=FM, how='xoá được bài của người khác (policy ở nền móng)',
       old='ON public.community_posts FOR DELETE TO authenticated USING (auth.uid() = author_id);',
       new='ON public.community_posts FOR DELETE TO authenticated USING (true);', expect='V12 xoá lây'),
  dict(suite=V, id='V14', mig=VM, how='thêm policy đọc cài đặt cho anon',
       old='CREATE POLICY "Users create their own community settings"',
       new='CREATE POLICY "x_anon" ON public.community_settings FOR SELECT TO anon USING (true);\nCREATE POLICY "Users create their own community settings"', expect='V14 anon'),
  dict(suite=V, id='V15', mig=VM, how='cài đặt không còn FK/cascade về auth.users',
       old='  user_id            uuid PRIMARY KEY DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,',
       new='  user_id            uuid PRIMARY KEY DEFAULT auth.uid(),', expect='V15 xoá tài khoản'),
]

R = 'recipe'
RM = 'community_recipe'
CASES += [
  dict(suite=R, id='R1', mig=RM, how='GRANT share_recipe cho anon',
       old='REVOKE EXECUTE ON FUNCTION public.share_recipe(uuid, text, text, text) FROM PUBLIC, anon;',
       new='GRANT EXECUTE ON FUNCTION public.share_recipe(uuid, text, text, text) TO anon;', expect='R1 anon'),
  dict(suite=R, id='R1b', mig=RM, how='REVOKE share_recipe khỏi authenticated (gỡ GRANT thôi không đủ: mặc định đã cấp)',
       old='REVOKE EXECUTE ON FUNCTION public.share_recipe(uuid, text, text, text) FROM PUBLIC, anon;',
       new='REVOKE EXECUTE ON FUNCTION public.share_recipe(uuid, text, text, text) FROM PUBLIC, anon, authenticated;', expect='R1b',
       extra=[('GRANT EXECUTE ON FUNCTION public.share_recipe(uuid, text, text, text) TO authenticated;', '')]),
  dict(suite=R, id='R2', mig=FM, how='thêm policy INSERT mở cho community_posts',
       old='CREATE POLICY "Authors delete their own posts"',
       new='CREATE POLICY "x_open_insert" ON public.community_posts FOR INSERT TO authenticated WITH CHECK (true);\nCREATE POLICY "Authors delete their own posts"',
       expect='R2 client INSERT'),
  dict(suite=R, id='R5', mig=RM, how='nhân kcal thêm một lần với servings',
       old="'kcal',      round(coalesce(it.kcal, 0)),", new="'kcal',      round(coalesce(it.kcal, 0) * it.servings),", expect='R5 macro'),
  dict(suite=R, id='R10', mig=RM, how='bịa khối lượng cho dòng gõ tay',
       old='CASE WHEN f.id IS NOT NULL AND f.serving_g > 0 AND it.servings > 0\n                        THEN round(it.servings * f.serving_g) END',
       new='CASE WHEN true\n                        THEN round(it.servings * coalesce(f.serving_g, 100)) END', expect='R10 dòng gõ tay'),
  dict(suite=R, id='R12', mig=RM, how='lấy tổng của BỮA thay vì các dòng',
       old="(SELECT coalesce(sum((x->>'kcal')::numeric), 0) FROM jsonb_array_elements(v_ingredients) x)",
       new='(SELECT total_kcal FROM meal_entries WHERE id = p_entry_id)', expect='R12 thẻ lấy'),
  dict(suite=R, id='R13a', mig=RM, how='bỏ chốt "đã chia sẻ" — UNIQUE còn, nên PHẢI vẫn xanh (lớp dự phòng)', green_ok=True,
       old='  IF EXISTS (SELECT 1 FROM public.community_posts WHERE author_id = v_uid AND source_id = p_entry_id) THEN', new='  IF false THEN', expect='R13'),
  dict(suite=R, id='R13b', mig=FM, how='bỏ UNIQUE(author_id, source_id) (chốt trong hàm Recipe cũng bỏ)',
       old='  UNIQUE (author_id, source_id)', new='  CHECK (true)', expect='R13 chia sẻ trùng',
       also=[(RM, '  IF EXISTS (SELECT 1 FROM public.community_posts WHERE author_id = v_uid AND source_id = p_entry_id) THEN', '  IF false THEN')]),
  dict(suite=R, id='R14', mig=RM, how='bỏ chốt bữa của chính mình', old=' AND e.user_id = v_uid', new='', expect='R14 chia sẻ được'),
  dict(suite=R, id='R15', mig=RM, how='bỏ chốt bữa rỗng', old='  IF v_n = 0 THEN', new='  IF false THEN', expect='R15 bữa rỗng'),
  dict(suite=R, id='R16', mig=RM, how='bỏ chốt tên trống', old='char_length(v_title) < 1 OR ', new='', expect='R16 tên món trống'),
  dict(suite=R, id='R17', mig=RM, how='bỏ chốt tên quá 80', old=' OR char_length(v_title) > 80', new='', expect='R17 tên món quá'),
  dict(suite=R, id='R18', mig=RM, how='bỏ chốt visibility',
       old="  IF p_visibility NOT IN ('public', 'followers') THEN", new='  IF false THEN', expect='R18 visibility'),
  dict(suite=R, id='R18b', mig=RM, how='ĐỐI CHỨNG: tên lệch mép (> 79)', old='char_length(v_title) > 80', new='char_length(v_title) > 79', expect='R18b'),
  dict(suite=R, id='R19', mig=RM, how='bỏ chốt hồ sơ',
       old='  IF NOT EXISTS (SELECT 1 FROM public.community_profiles WHERE user_id = v_uid) THEN', new='  IF false THEN', expect='R19'),
]

N = 'notifications'
NM = 'community_notifications'
CASES += [
  dict(suite=N, id='N19', mig=NM, how='thêm policy đọc thông báo cho anon',
       old='ALTER TABLE public.community_notifications ENABLE ROW LEVEL SECURITY;',
       new='ALTER TABLE public.community_notifications ENABLE ROW LEVEL SECURITY;\nCREATE POLICY "x_anon" ON public.community_notifications FOR SELECT TO anon USING (true);',
       expect='N19 anon'),
]
