"""Các ca phá thử của B (#14, đưa vào repo ở #25) và của A (#75). Mỗi ca: phá ĐÚNG MỘT chốt
trên bản sao migration, và đòi câu ASSERT đỏ đầu tiên của bộ đích chứa
`expect`. Chép nguyên văn từ bình luận của B ở #25 (88 ca, 88/88 trên
`53c9b89`); chạy bằng `b_reverse.py`.

  green_ok=True   PHẢI xanh — còn một lớp bảo vệ dự phòng (15a, R13a)
  extra / also    phá thêm chỗ khác, trong cùng / một migration khác
  nth             lần xuất hiện thứ mấy; 'all' là thay mọi chỗ
"""
F = 'foundation'
FM = 'community_foundation'
CASES = [
  # ── hồ sơ ──
  dict(suite=F, id='1', mig=FM, how='trigger không gạt is_official khi TẠO',
       old='      NEW.is_official := false;', new='      NULL;', expect='1 người thường'),
  dict(suite=F, id='2', mig=FM, how='trigger không giữ is_official khi SỬA',
       old='      NEW.is_official := OLD.is_official;', new='      NULL;', expect='2 người thường'),
  dict(suite=F, id='3', mig=FM, how='policy INSERT hồ sơ bỏ auth.uid() = user_id',
       old='  ON public.community_profiles FOR INSERT TO authenticated\n  WITH CHECK (auth.uid() = user_id);',
       new='  ON public.community_profiles FOR INSERT TO authenticated\n  WITH CHECK (true);', expect='3 tạo được'),
  dict(suite=F, id='4', mig=FM, how='bỏ CHECK định dạng handle',
       old="UNIQUE CHECK (handle ~ '^[a-z0-9_.]{3,24}$')", new='UNIQUE', expect='4 handle'),
  dict(suite=F, id='37', mig=FM, how='trigger gạt is_official cả với dashboard',
       old="  IF current_user IN ('authenticated', 'anon') THEN\n    IF TG_OP = 'INSERT' THEN",
       new="  IF true THEN\n    IF TG_OP = 'INSERT' THEN", expect='37 dashboard'),
  # ── chia sẻ ──
  dict(suite=F, id='5', mig=FM, how='thêm policy INSERT mở cho community_posts',
       old='CREATE POLICY "Authors delete their own posts"',
       new='CREATE POLICY "x_open_insert" ON public.community_posts FOR INSERT TO authenticated WITH CHECK (true);\nCREATE POLICY "Authors delete their own posts"',
       expect='5 client INSERT'),
  dict(suite=F, id='11', mig=FM, how='bỏ lọc set khởi động (vế này do 12 canh: set khởi động 20 kg không bao giờ là set nặng nhất)',
       old="    WHERE coalesce((e->>'warmup')::boolean, false) = false\n", new='', expect='12 set khởi động'),
  dict(suite=F, id='12', mig=FM, how='đếm cả set khởi động (giữ top set)',
       old='      count(*)                                          AS n_sets,',
       new="      count(*) + 1                                      AS n_sets,", expect='12 set khởi động'),
  dict(suite=F, id='14', mig=FM, how='coi mọi bài là thư viện',
       old="'library',      coalesce(x.user_id IS NULL AND x.id IS NOT NULL, false),",
       new="'library',      coalesce(x.id IS NOT NULL, false),", expect='14 bài tự tạo'),
  dict(suite=F, id='15a', mig=FM, how='bỏ chốt "đã chia sẻ" trong hàm — UNIQUE còn, nên PHẢI vẫn xanh (lớp dự phòng; 15b phá cả hai)', green_ok=True,
       old='  IF EXISTS (SELECT 1 FROM public.community_posts WHERE author_id = v_uid AND source_id = p_session_id) THEN',
       new='  IF false THEN', expect='15 chia sẻ trùng'),
  dict(suite=F, id='15b', mig=FM, how='bỏ CẢ chốt trong hàm LẪN UNIQUE(author_id, source_id)',
       old='  UNIQUE (author_id, source_id)', new='  CHECK (true)', expect='15 chia sẻ trùng', extra=[
         ('  IF EXISTS (SELECT 1 FROM public.community_posts WHERE author_id = v_uid AND source_id = p_session_id) THEN', '  IF false THEN')]),
  dict(suite=F, id='11b', mig=FM, how='set nặng nhất lấy reps THẤP nhất (24x8)',
       old='(array_agg(w ORDER BY w DESC, r DESC))[1]         AS top_w,\n      (array_agg(r ORDER BY w DESC, r DESC))[1]         AS top_r',
       new='(array_agg(w ORDER BY w DESC, r ASC))[1]         AS top_w,\n      (array_agg(r ORDER BY w DESC, r ASC))[1]         AS top_r', expect='11 set nặng nhất'),
  dict(suite=F, id='27b', mig=FM, how='ĐỐI CHỨNG: chặn mọi báo cáo người dùng',
       old="WITH CHECK (auth.uid() = reporter_id AND status = 'open');", new="WITH CHECK (auth.uid() = reporter_id AND status = 'open' AND reported_user_id IS NULL);", expect='27b'),
  dict(suite=F, id='16', mig=FM, how='bỏ lọc chủ buổi tập',
       old='WHERE id = p_session_id AND user_id = v_uid;', new='WHERE id = p_session_id;', expect='16 chia sẻ được'),
  dict(suite=F, id='18', mig=FM, how='không gạt phút ngoài 1..600',
       old="'minutes',       CASE WHEN p_minutes BETWEEN 1 AND 600 THEN p_minutes END,",
       new="'minutes',       p_minutes,", expect='18 phút'),
  # ── người xem ──
  dict(suite=F, id='19', mig=FM, how='bài "followers" hiện với mọi người',
       old="        visibility = 'public'\n        OR EXISTS", new="        true\n        OR EXISTS", expect='19 B phải thấy'),
  dict(suite=F, id='20', mig=FM, how='bỏ nhánh "đang theo dõi" của policy đọc bài',
       old='WHERE f.follower_id = auth.uid() AND f.followee_id = community_posts.author_id',
       new='WHERE false', expect='20 theo dõi rồi'),
  dict(suite=F, id='21', mig=FM, how='thêm policy UPDATE mở cho community_posts',
       old='CREATE POLICY "Authors delete their own posts"',
       new='CREATE POLICY "x_open_update" ON public.community_posts FOR UPDATE TO authenticated USING (true) WITH CHECK (true);\nCREATE POLICY "Authors delete their own posts"',
       expect='21 người xem sửa'),
  dict(suite=F, id='22', mig=FM, how='bỏ trigger đếm bình luận',
       old='CREATE TRIGGER community_comments_count\n  AFTER INSERT OR DELETE ON public.community_comments\n  FOR EACH ROW EXECUTE FUNCTION public.community_count_bump();',
       new='', expect='22 bộ đếm'),
  # ── chặn ──
  dict(suite=F, id='23', mig=FM, how='policy đọc bài bỏ vế chặn',
       old='      AND NOT public.community_blocked_between(auth.uid(), author_id)\n      AND (\n        visibility',
       new='      AND (\n        visibility', expect='23 người BỊ chặn'),
  dict(suite=F, id='24', mig=FM, how='trigger chặn không gỡ theo dõi',
       old='  DELETE FROM public.community_follows\n  WHERE (follower_id = NEW.blocker_id AND followee_id = NEW.blocked_id)\n     OR (follower_id = NEW.blocked_id AND followee_id = NEW.blocker_id);',
       new='  NULL;', expect='24 chặn không gỡ'),
  dict(suite=F, id='25', mig=FM, how='policy theo dõi bỏ vế chặn',
       old='WITH CHECK (auth.uid() = follower_id AND NOT public.community_blocked_between(follower_id, followee_id));',
       new='WITH CHECK (auth.uid() = follower_id);', expect='25 theo dõi lại'),
  dict(suite=F, id='26', mig=FM, how='ai cũng đọc được dòng chặn',
       old='ON public.community_blocks FOR SELECT TO authenticated USING (auth.uid() = blocker_id);',
       new='ON public.community_blocks FOR SELECT TO authenticated USING (true);', expect='26 người bị chặn đọc'),
  # ── báo cáo ──
  dict(suite=F, id='27', mig=FM, how="policy báo cáo bỏ status = 'open'",
       old="WITH CHECK (auth.uid() = reporter_id AND status = 'open');",
       new='WITH CHECK (auth.uid() = reporter_id);', expect='27 tự đóng'),
  dict(suite=F, id='28', mig=FM, how='ngưỡng tự ẩn bài hạ xuống 2',
       old='WHERE post_id = NEW.post_id\n  ) >= 3 THEN', new='WHERE post_id = NEW.post_id\n  ) >= 2 THEN', expect='28 hai báo cáo'),
  dict(suite=F, id='29', mig=FM, how='ngưỡng tự ẩn bài nâng lên 4',
       old='WHERE post_id = NEW.post_id\n  ) >= 3 THEN', new='WHERE post_id = NEW.post_id\n  ) >= 4 THEN', expect='29 ba người'),
  dict(suite=F, id='30', mig=FM, how='policy đọc bài bỏ NOT hidden',
       old='    OR (\n      NOT hidden\n      AND NOT public.community_blocked_between(auth.uid(), author_id)\n      AND (\n        visibility',
       new='    OR (\n      true\n      AND NOT public.community_blocked_between(auth.uid(), author_id)\n      AND (\n        visibility',
       expect='30 bài đã ẩn'),
  dict(suite=F, id='31', mig=FM, how='ai cũng đọc được báo cáo',
       old='ON public.community_reports FOR SELECT TO authenticated USING (auth.uid() = reporter_id);',
       new='ON public.community_reports FOR SELECT TO authenticated USING (true);', expect='31 đọc được báo cáo'),
  dict(suite=F, id='32', mig=FM, how='policy đọc bài bỏ nhánh "của mình"',
       old='  USING (\n    author_id = auth.uid()\n    OR (\n      NOT hidden', new='  USING (\n    false\n    OR (\n      NOT hidden',
       expect='32 tác giả'),
  dict(suite=F, id='33', mig=FM, how='bình luận không còn FK/cascade về bài',
       old='  post_id    uuid NOT NULL REFERENCES public.community_posts(id) ON DELETE CASCADE,\n  author_id  uuid NOT NULL DEFAULT auth.uid()',
       new='  post_id    uuid NOT NULL,\n  author_id  uuid NOT NULL DEFAULT auth.uid()', expect='33 xoá bài'),
  # ── anon ──
  dict(suite=F, id='34', mig=FM, how='GRANT share_workout cho anon',
       old='REVOKE EXECUTE ON FUNCTION public.share_workout(uuid, text, text, integer) FROM PUBLIC, anon;',
       new='GRANT EXECUTE ON FUNCTION public.share_workout(uuid, text, text, integer) TO anon;', expect='34 anon'),
  dict(suite=F, id='35', mig=FM, how='policy đọc bài mở cho anon, bài công khai',
       old='CREATE POLICY "Authors delete their own posts"',
       new="CREATE POLICY \"x_anon_read\" ON public.community_posts FOR SELECT TO anon USING (visibility = 'public');\nCREATE POLICY \"Authors delete their own posts\"",
       expect='35 anon đọc'),
  # ── xoá tài khoản ──
  dict(suite=F, id='36', mig=FM, how='hồ sơ không còn FK/cascade về auth.users',
       old='  user_id      uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,',
       new='  user_id      uuid PRIMARY KEY,', expect='36 xoá tài khoản'),
]

P = 'progress'
PM = 'community_progress'
CASES += [
  dict(suite=P, id='P1', mig=PM, how='vòng eo luôn bật', old='  IF p_waist THEN', new='  IF true THEN', expect='P1 chỉ số TẮT'),
  dict(suite=P, id='P2', mig=PM, how='cân nặng bỏ lọc khoảng ngày',
       old='      WHERE user_id = v_uid AND date > v_from AND date <= v_to\n    ), wk AS (',
       new='      WHERE user_id = v_uid\n    ), wk AS (', expect='P2 đầu/cuối'),
  dict(suite=P, id='P5', mig=PM, how='cân nặng luôn bật', old='  IF p_weight THEN', new='  IF true THEN', expect='P5 cân nặng tắt'),
  dict(suite=P, id='P8', mig=PM, how='sức mạnh bỏ lọc set khởi động',
       old="          AND coalesce((e->>'warmup')::boolean, false) = false\n", new='', expect='P8 Bench'),
  dict(suite=P, id='P9', mig=PM, how='đọc được bài tự tạo của người khác (bỏ lọc chủ bài)',
       old='    WHERE id = p_lift_exercise_id AND (user_id IS NULL OR user_id = v_uid);',
       new='    WHERE id = p_lift_exercise_id;', expect='P9 đọc được'),
  dict(suite=P, id='P9b', mig=PM, how='sức mạnh bỏ lọc chủ BUỔI TẬP (đọc buổi của người khác)',
       old='        WHERE s.user_id = v_uid\n          AND (s.date_time', new='        WHERE true\n          AND (s.date_time', expect='P19 biểu đồ sức mạnh'),
  dict(suite=P, id='P10', mig=PM, how='bỏ chốt số tuần 1..52',
       old='  IF p_weeks IS NULL OR p_weeks NOT BETWEEN 1 AND 52 THEN', new='  IF false THEN', expect='P10 số tuần'),
  dict(suite=P, id='P10b', mig=PM, how='ĐỐI CHỨNG: trần số tuần hạ xuống 51',
       old='  IF p_weeks IS NULL OR p_weeks NOT BETWEEN 1 AND 52 THEN', new='  IF p_weeks IS NULL OR p_weeks NOT BETWEEN 1 AND 51 THEN', expect='P10b'),
  dict(suite=P, id='P11', mig=PM, how='bỏ chốt "không có gì để chia sẻ"',
       old='  IF v_w IS NULL AND v_waist IS NULL AND v_lift IS NULL THEN', new='  IF false THEN', expect='P11 không bật'),
  dict(suite=P, id='P12', mig=PM, how='share_progress bỏ chốt hồ sơ',
       old='  IF NOT EXISTS (SELECT 1 FROM public.community_profiles WHERE user_id = v_uid) THEN', new='  IF false THEN', expect='P12 đăng được'),
  dict(suite=P, id='P15', mig=PM, how='cân nặng: một điểm cũng thành "thay đổi"',
       old='    SELECT CASE WHEN (SELECT count(*) FROM pts) >= 2 THEN jsonb_build_object(', nth=1,
       new='    SELECT CASE WHEN (SELECT count(*) FROM pts) >= 1 THEN jsonb_build_object(', expect='P15 một điểm'),
  dict(suite=P, id='P16', mig=PM, how='cân nặng bỏ lọc user_id (bắt ở P15 trước — cùng lỗi; P16b đo riêng P16)',
       old='      WHERE user_id = v_uid AND date > v_from AND date <= v_to\n    ), wk AS (',
       new='      WHERE date > v_from AND date <= v_to\n    ), wk AS (', expect='P15 một điểm'),
  dict(suite=P, id='P16b', mig=PM, how='cân nặng rò dữ liệu người khác khi khoảng > 1 tuần (P15 không chạm tới)',
       old='      WHERE user_id = v_uid AND date > v_from AND date <= v_to\n    ), wk AS (',
       new='      WHERE (user_id = v_uid OR p_weeks > 1) AND date > v_from AND date <= v_to\n    ), wk AS (', expect='P16 payload của Q'),
  dict(suite=P, id='P17', mig=PM, how='GRANT build_progress_payload cho anon',
       old='REVOKE EXECUTE ON FUNCTION public.build_progress_payload(integer, boolean, boolean, uuid) FROM PUBLIC, anon;',
       new='GRANT EXECUTE ON FUNCTION public.build_progress_payload(integer, boolean, boolean, uuid) TO anon;', expect='P17 anon'),
  dict(suite=P, id='P18', mig=PM, how='GRANT share_progress cho anon',
       old='REVOKE EXECUTE ON FUNCTION public.share_progress(integer, boolean, boolean, uuid, text, text) FROM PUBLIC, anon;',
       new='GRANT EXECUTE ON FUNCTION public.share_progress(integer, boolean, boolean, uuid, text, text) TO anon;', expect='P18 anon'),
]

C = 'challenges'
CM = 'community_challenges'
CASES += [
  dict(suite=C, id='C1', mig=CM, how='thêm policy INSERT mở cho community_challenges',
       old='CREATE POLICY "Signed-in users can read challenges"',
       new='CREATE POLICY "x_open" ON public.community_challenges FOR INSERT TO authenticated WITH CHECK (true);\nCREATE POLICY "Signed-in users can read challenges"', expect='C1 client tạo'),
  dict(suite=C, id='C2', mig=CM, how='tham gia bỏ vế "còn mở"',
       old='    AND claimed_at IS NULL\n    AND EXISTS (SELECT 1 FROM public.community_challenges c WHERE c.id = challenge_id AND c.ends_on >= current_date)',
       new='    AND claimed_at IS NULL', expect='C2 tham gia được'),
  dict(suite=C, id='C3', mig=CM, how='tham gia bỏ vế claimed_at IS NULL',
       old='    auth.uid() = user_id\n    AND claimed_at IS NULL\n    AND EXISTS', new='    auth.uid() = user_id\n    AND EXISTS', expect='C3 tham gia kèm'),
  dict(suite=C, id='C4', mig=CM, how='thêm policy UPDATE mở cho thành viên',
       old='CREATE POLICY "Users leave unclaimed challenges"',
       new='CREATE POLICY "x_upd" ON public.community_challenge_members FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (true);\nCREATE POLICY "Users leave unclaimed challenges"', expect='C4 tự đánh dấu'),
  dict(suite=C, id='C6', mig=CM, how='đếm BUỔI thay vì NGÀY', old='  SELECT count(DISTINCT ((s.date_time', new='  SELECT count(((s.date_time', expect='C6 tiến độ'),
  dict(suite=C, id='C6b', mig=CM, how='bỏ lọc khoảng ngày của thử thách',
       old="    AND ((s.date_time AT TIME ZONE 'UTC') + make_interval(mins => greatest(-720, least(840, coalesce(p_offset_min, 0)))))::date\n        BETWEEN c.starts_on AND c.ends_on;",
       new='    ;', expect='C6 tiến độ'),
  dict(suite=C, id='C8', mig=CM, how='nhận thưởng bỏ chốt "đã đạt"',
       old='  IF public.community_challenge_progress(p_challenge, v_uid, p_offset_min) < c.target THEN', new='  IF false THEN', expect='C8 nhận thưởng khi chưa đạt'),
  dict(suite=C, id='C9', mig=CM, how='hàm đo tiến độ gọi được từ client',
       old='REVOKE EXECUTE ON FUNCTION public.community_challenge_progress(uuid, uuid, integer) FROM PUBLIC, anon, authenticated;',
       new='GRANT EXECUTE ON FUNCTION public.community_challenge_progress(uuid, uuid, integer) TO authenticated;', expect='C9 client gọi thẳng'),
  dict(suite=C, id='C10', mig=CM, how='ai cũng đọc được danh sách thành viên',
       old='ON public.community_challenge_members FOR SELECT TO authenticated USING (auth.uid() = user_id);',
       new='ON public.community_challenge_members FOR SELECT TO authenticated USING (true);', expect='C10 đọc được'),
  dict(suite=C, id='C13', mig=CM, how='bỏ chốt "đã nhận"', old='  IF v_claimed IS NOT NULL THEN', new='  IF false THEN', expect='C13 nhận thưởng HAI'),
  dict(suite=C, id='C14', mig=CM, how='rời được cả khi đã nhận',
       old='  USING (auth.uid() = user_id AND claimed_at IS NULL);', new='  USING (auth.uid() = user_id);', expect='C14 rời được'),
  dict(suite=C, id='C18', mig=CM, how='bỏ lệch múi giờ (đếm theo UTC)', nth='all',
       old='coalesce(p_offset_min, 0)', new='0', expect='C18 theo UTC+7'),
  dict(suite=C, id='C19', mig=CM, how='GRANT tổng quan cho anon',
       old='REVOKE EXECUTE ON FUNCTION public.community_challenges_overview(integer) FROM PUBLIC, anon;',
       new='GRANT EXECUTE ON FUNCTION public.community_challenges_overview(integer) TO anon;', expect='C19 anon'),
  dict(suite=C, id='C20', mig=CM, how='GRANT nhận thưởng cho anon',
       old='REVOKE EXECUTE ON FUNCTION public.claim_community_challenge(uuid, integer) FROM PUBLIC, anon;',
       new='GRANT EXECUTE ON FUNCTION public.claim_community_challenge(uuid, integer) TO anon;', expect='C20 anon'),
]

V = 'privacy'
VM = 'community_privacy'
CASES += [
  dict(suite=V, id='V2', mig=VM, how='ai cũng đọc được cài đặt',
       old='ON public.community_settings FOR SELECT TO authenticated USING (auth.uid() = user_id);',
       new='ON public.community_settings FOR SELECT TO authenticated USING (true);', expect='V2 đọc được'),
  dict(suite=V, id='V3', mig=VM, how='tạo cài đặt cho người khác',
       old='ON public.community_settings FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);',
       new='ON public.community_settings FOR INSERT TO authenticated WITH CHECK (true);', expect='V3 tạo được'),
  dict(suite=V, id='V4', mig=VM, how='policy UPDATE mở toang',
       old='  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);', new='  USING (true) WITH CHECK (true);', expect='V4 sửa được'),
  dict(suite=V, id='V5', mig=VM, how="bỏ CHECK giá trị hiển thị",
       old="DEFAULT 'public' CHECK (default_visibility IN ('public', 'followers')),", new="DEFAULT 'public',", expect='V5 giá trị'),
  dict(suite=V, id='V6', mig=VM, how='UPDATE bỏ WITH CHECK',
       old='  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);', new='  USING (auth.uid() = user_id) WITH CHECK (true);', expect='V6 chuyển được'),
  dict(suite=V, id='V7', mig=FM, how='ai cũng đọc được dòng chặn (policy ở nền móng)',
       old='ON public.community_blocks FOR SELECT TO authenticated USING (auth.uid() = blocker_id);',
       new='ON public.community_blocks FOR SELECT TO authenticated USING (true);', expect='V7 thấy được'),
  dict(suite=V, id='V9', mig=FM, how='bỏ chặn xoá được dòng của người khác (policy ở nền móng)',
       old='ON public.community_blocks FOR DELETE TO authenticated USING (auth.uid() = blocker_id);',
       new='ON public.community_blocks FOR DELETE TO authenticated USING (true);', expect='V9 bỏ chặn gỡ'),
  dict(suite=V, id='V12', mig=FM, how='xoá được bài của người khác (policy ở nền móng)',
       old='ON public.community_posts FOR DELETE TO authenticated USING (auth.uid() = author_id);',
       new='ON public.community_posts FOR DELETE TO authenticated USING (true);', expect='V12 xoá lây'),
  dict(suite=V, id='V14', mig=VM, how='thêm policy đọc cài đặt cho anon',
       old='CREATE POLICY "Users create their own community settings"',
       new='CREATE POLICY "x_anon" ON public.community_settings FOR SELECT TO anon USING (true);\nCREATE POLICY "Users create their own community settings"', expect='V14 anon'),
  dict(suite=V, id='V15', mig=VM, how='cài đặt không còn FK/cascade về auth.users',
       old='  user_id            uuid PRIMARY KEY DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,',
       new='  user_id            uuid PRIMARY KEY DEFAULT auth.uid(),', expect='V15 xoá tài khoản'),
]

R = 'recipe'
RM = 'community_recipe'
CASES += [
  dict(suite=R, id='R1', mig=RM, how='GRANT share_recipe cho anon',
       old='REVOKE EXECUTE ON FUNCTION public.share_recipe(uuid, text, text, text) FROM PUBLIC, anon;',
       new='GRANT EXECUTE ON FUNCTION public.share_recipe(uuid, text, text, text) TO anon;', expect='R1 anon'),
  dict(suite=R, id='R1b', mig=RM, how='REVOKE share_recipe khỏi authenticated (gỡ GRANT thôi không đủ: mặc định đã cấp)',
       old='REVOKE EXECUTE ON FUNCTION public.share_recipe(uuid, text, text, text) FROM PUBLIC, anon;',
       new='REVOKE EXECUTE ON FUNCTION public.share_recipe(uuid, text, text, text) FROM PUBLIC, anon, authenticated;', expect='R1b',
       extra=[('GRANT EXECUTE ON FUNCTION public.share_recipe(uuid, text, text, text) TO authenticated;', '')]),
  dict(suite=R, id='R2', mig=FM, how='thêm policy INSERT mở cho community_posts',
       old='CREATE POLICY "Authors delete their own posts"',
       new='CREATE POLICY "x_open_insert" ON public.community_posts FOR INSERT TO authenticated WITH CHECK (true);\nCREATE POLICY "Authors delete their own posts"',
       expect='R2 client INSERT'),
  dict(suite=R, id='R5', mig=RM, how='nhân kcal thêm một lần với servings',
       old="'kcal',      round(coalesce(it.kcal, 0)),", new="'kcal',      round(coalesce(it.kcal, 0) * it.servings),", expect='R5 macro'),
  dict(suite=R, id='R10', mig=RM, how='bịa khối lượng cho dòng gõ tay',
       old='CASE WHEN f.id IS NOT NULL AND f.serving_g > 0 AND it.servings > 0\n                        THEN round(it.servings * f.serving_g) END',
       new='CASE WHEN true\n                        THEN round(it.servings * coalesce(f.serving_g, 100)) END', expect='R10 dòng gõ tay'),
  dict(suite=R, id='R12', mig=RM, how='lấy tổng của BỮA thay vì các dòng',
       old="(SELECT coalesce(sum((x->>'kcal')::numeric), 0) FROM jsonb_array_elements(v_ingredients) x)",
       new='(SELECT total_kcal FROM meal_entries WHERE id = p_entry_id)', expect='R12 thẻ lấy'),
  dict(suite=R, id='R13a', mig=RM, how='bỏ chốt "đã chia sẻ" — UNIQUE còn, nên PHẢI vẫn xanh (lớp dự phòng)', green_ok=True,
       old='  IF EXISTS (SELECT 1 FROM public.community_posts WHERE author_id = v_uid AND source_id = p_entry_id) THEN', new='  IF false THEN', expect='R13'),
  dict(suite=R, id='R13b', mig=FM, how='bỏ UNIQUE(author_id, source_id) (chốt trong hàm Recipe cũng bỏ)',
       old='  UNIQUE (author_id, source_id)', new='  CHECK (true)', expect='R13 chia sẻ trùng',
       also=[(RM, '  IF EXISTS (SELECT 1 FROM public.community_posts WHERE author_id = v_uid AND source_id = p_entry_id) THEN', '  IF false THEN')]),
  dict(suite=R, id='R14', mig=RM, how='bỏ chốt bữa của chính mình', old=' AND e.user_id = v_uid', new='', expect='R14 chia sẻ được'),
  dict(suite=R, id='R15', mig=RM, how='bỏ chốt bữa rỗng', old='  IF v_n = 0 THEN', new='  IF false THEN', expect='R15 bữa rỗng'),
  dict(suite=R, id='R16', mig=RM, how='bỏ chốt tên trống', old='char_length(v_title) < 1 OR ', new='', expect='R16 tên món trống'),
  dict(suite=R, id='R17', mig=RM, how='bỏ chốt tên quá 80', old=' OR char_length(v_title) > 80', new='', expect='R17 tên món quá'),
  dict(suite=R, id='R18', mig=RM, how='bỏ chốt visibility',
       old="  IF p_visibility NOT IN ('public', 'followers') THEN", new='  IF false THEN', expect='R18 visibility'),
  dict(suite=R, id='R18b', mig=RM, how='ĐỐI CHỨNG: tên lệch mép (> 79)', old='char_length(v_title) > 80', new='char_length(v_title) > 79', expect='R18b'),
  dict(suite=R, id='R19', mig=RM, how='bỏ chốt hồ sơ',
       old='  IF NOT EXISTS (SELECT 1 FROM public.community_profiles WHERE user_id = v_uid) THEN', new='  IF false THEN', expect='R19'),
  # #74: ca duy nhất của `recipe.reverse.sh` chưa có ở đây — 12 ca kia trùng ý
  # với R1, R1b, R5, R10, R12, R14–R19, R18b. Nhắm đúng tệp định nghĩa SAU CÙNG
  # của share_recipe (bản của #7 bị nó ghi đè), như khoá tên tệp đầy đủ của #75.
  dict(suite=R, id='R11b', mig='20260930150000_community_recipe_no_eaten_at', how='ghi lại giờ ăn vào payload công khai',
       old="'ingredientCount', v_n,", new="'eatenAt', now(), 'ingredientCount', v_n,", expect='R11b payload công khai mang giờ ăn'),
]

N = 'notifications'
NM = 'community_notifications'
CASES += [
  dict(suite=N, id='N19', mig=NM, how='thêm policy đọc thông báo cho anon',
       old='ALTER TABLE public.community_notifications ENABLE ROW LEVEL SECURITY;',
       new='ALTER TABLE public.community_notifications ENABLE ROW LEVEL SECURITY;\nCREATE POLICY "x_anon" ON public.community_notifications FOR SELECT TO anon USING (true);',
       expect='N19 anon'),
]

# ── các ca của A (#75), từ a-suites.reverse.sh (đã bỏ) ──
# Chuyển TỰ ĐỘNG, không chép tay: chạy đúng biểu thức sed của mỗi dòng `try` lên
# migration thật, so hai bản để lấy chuỗi cũ/mới chính xác, rồi nới ngữ cảnh theo
# DÒNG tới khi chuỗi cũ là duy nhất. `mig` là TÊN TỆP đầy đủ (có mốc thời gian):
# ca của A nhắm đúng tệp định nghĩa sau cùng, và `community_search` trần sẽ khớp cả
# tệp `_unaccent`, nơi chuỗi của hàm gợi ý không có. Bỏ 11 ca trùng với ca của B
# (cùng kịch bản đích, cùng ý phá): 21, P1, P8, C6, C9, C13, C19, C20, V2, V4, V5.
CASES += [
  dict(suite='challenges', id='A·R1', mig='20260930120000_community_challenges', how='(A) nhắc: cửa sổ tổng quan 7 → 2', old='  WHERE c.ends_on >= current_date - 7 AND c.starts_on <= current_date + 30', new='  WHERE c.ends_on >= current_date - 2 AND c.starts_on <= current_date + 30', expect='R1 '),
  dict(suite='challenges', id='A·R2', mig='20260930120000_community_challenges', how='(A) nhắc: cửa sổ tổng quan 7 → 9', old='  WHERE c.ends_on >= current_date - 7 AND c.starts_on <= current_date + 30', new='  WHERE c.ends_on >= current_date - 9 AND c.starts_on <= current_date + 30', expect='R2 '),
  dict(suite='challenges', id='A·R3', mig='20260930120000_community_challenges', how='(A) nhắc: nhận thưởng cấm sau hạn', old='  IF c.reward_coins > 0 THEN', new="  IF c.ends_on < current_date THEN RAISE EXCEPTION 'ended' USING ERRCODE = '22023'; END IF;\n  IF c.reward_coins > 0 THEN", expect='R3 '),
  dict(suite='notifications', id='A·N1', mig='20260930140000_community_notifications', how='(A) thông báo: client tự ghi', old='ALTER TABLE public.community_notifications ENABLE ROW LEVEL SECURITY;\n\nCREATE POLICY "Users read their own notifications"', new='ALTER TABLE public.community_notifications ENABLE ROW LEVEL SECURITY;\nCREATE POLICY "open" ON public.community_notifications FOR INSERT TO authenticated WITH CHECK (true);\n\nCREATE POLICY "Users read their own notifications"', expect='N1 '),
  dict(suite='notifications', id='A·N3', mig='20260930140000_community_notifications', how='(A) thông báo: bỏ dọn khi bỏ thích', old="    WHERE kind = 'like' AND post_id = OLD.post_id AND actor_id = OLD.user_id;", new='    WHERE false AND post_id = OLD.post_id AND actor_id = OLD.user_id;', expect='N3 '),
  dict(suite='notifications', id='A·community_notifications_check', mig='20260930140000_community_notifications', how='(A) thông báo: tự báo cho mình', old='  IF v_to IS NULL OR v_to = v_actor', new='  IF v_to IS NULL', expect='community_notifications_check'),
  dict(suite='notifications', id='A·N8', mig='20260930140000_community_notifications', how='(A) thông báo: bỏ dọn khi xoá bình luận', old='  comment_id uuid REFERENCES public.community_comments(id) ON DELETE CASCADE,', new='  comment_id uuid,', expect='N8 '),
  dict(suite='notifications', id='A·N9', mig='20260930140000_community_notifications', how='(A) thông báo: bỏ dọn khi bị ẩn', old='  FOR EACH ROW WHEN (NEW.hidden AND NOT OLD.hidden) EXECUTE FUNCTION public.community_unnotify();', new='  FOR EACH ROW WHEN (false) EXECUTE FUNCTION public.community_unnotify();', expect='N9 '),
  dict(suite='notifications', id='A·N10a', mig='20260930140000_community_notifications', how='(A) thông báo: bỏ dọn khi bỏ theo dõi', old="    WHERE kind = 'follow' AND user_id = OLD.followee_id AND actor_id = OLD.follower_id;", new='    WHERE false AND user_id = OLD.followee_id AND actor_id = OLD.follower_id;', expect='N10a '),
  dict(suite='notifications', id='A·N11', mig='20260930140000_community_notifications', how='(A) thông báo: SELECT mở', old='  USING (auth.uid() = user_id AND NOT public.community_blocked_between(user_id, actor_id));', new='  USING (true);', expect='N11 '),
  dict(suite='notifications', id='A·N13', mig='20260930140000_community_notifications', how='(A) thông báo: thêm policy UPDATE', old='ALTER TABLE public.community_notifications ENABLE ROW LEVEL SECURITY;\n\nCREATE POLICY "Users read their own notifications"', new='ALTER TABLE public.community_notifications ENABLE ROW LEVEL SECURITY;\nCREATE POLICY "open" ON public.community_notifications FOR UPDATE TO authenticated USING (true);\n\nCREATE POLICY "Users read their own notifications"', expect='N13 '),
  dict(suite='notifications', id='A·N14', mig='20260930140000_community_notifications', how='(A) thông báo: RPC đánh dấu hộp người khác', old='  WHERE user_id = v_uid AND read_at IS NULL;', new='  WHERE read_at IS NULL;', expect='N14 '),
  dict(suite='notifications', id='A·N16', mig='20260930140000_community_notifications', how='(A) thông báo: RLS bỏ lọc chặn', old='  USING (auth.uid() = user_id AND NOT public.community_blocked_between(user_id, actor_id));', new='  USING (auth.uid() = user_id);', expect='N16 '),
  dict(suite='notifications', id='A·N18', mig='20260930140000_community_notifications', how='(A) thông báo: trigger bỏ lọc chặn', old='     OR public.community_blocked_between(v_to, v_actor) THEN', new='     THEN', expect='N18 '),
  dict(suite='notifications', id='A·N20', mig='20260930140000_community_notifications', how='(A) thông báo: anon gọi RPC', old='REVOKE EXECUTE ON FUNCTION public.community_mark_notifications_read() FROM PUBLIC, anon;', new='GRANT EXECUTE ON FUNCTION public.community_mark_notifications_read() TO anon;', expect='N20 '),
  dict(suite='search', id='A·S2', mig='20260930170000_community_search_unaccent', how='(A) tìm: bỏ lọc chặn', old='    AND NOT public.community_blocked_between(v_uid, p.user_id)', new='    AND true', expect='S2 '),
  dict(suite='search', id='A·S4', mig='20260930170000_community_search_unaccent', how='(A) tìm: không thoát ký tự đại diện', old="  v_pat := replace(replace(replace(v_q, '\\', '\\\\'), '%', '\\%'), '_', '\\_');", new='  v_pat := v_q;', expect='S4 '),
  dict(suite='search', id='A·S2', mig='20260930170000_community_search_unaccent', how='(A) tìm: không loại chính mình', old='  WHERE p.user_id <> v_uid', new='  WHERE true', expect='S2 '),
  dict(suite='search', id='A·S8', mig='20260930170000_community_search_unaccent', how='(A) tìm: nới trần 20 → 21', old='  LIMIT 20;', new='  LIMIT 21;', expect='S8 '),
  dict(suite='search', id='A·G1', mig='20260930160000_community_search', how='(A) gợi ý: đếm cả bài chỉ-theo-dõi', old="            WHERE x.author_id = p.user_id AND x.visibility = 'public' AND NOT x.hidden", new='            WHERE x.author_id = p.user_id AND NOT x.hidden', expect='G1 '),
  dict(suite='search', id='A·G1', mig='20260930160000_community_search', how='(A) gợi ý: đếm cả bài bị ẩn', old="            WHERE x.author_id = p.user_id AND x.visibility = 'public' AND NOT x.hidden", new="            WHERE x.author_id = p.user_id AND x.visibility = 'public'", expect='G1 '),
  dict(suite='search', id='A·G1', mig='20260930160000_community_search', how='(A) gợi ý: không loại người đã theo dõi', old='      AND NOT EXISTS (SELECT 1 FROM public.community_follows f WHERE f.follower_id = v_uid AND f.followee_id = p.user_id)', new='', expect='G1 '),
  dict(suite='search', id='A·S10', mig='20260930170000_community_search_unaccent', how='(A) tìm: anon gọi được', old='REVOKE EXECUTE ON FUNCTION public.community_search_profiles(text) FROM PUBLIC, anon;', new='GRANT EXECUTE ON FUNCTION public.community_search_profiles(text) TO anon;', expect='S10 '),
  dict(suite='search', id='A·U1', mig='20260930170000_community_search_unaccent', how='(A) không dấu: gập không bỏ dấu', old="    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeeeeeeeeeeeeeeeeeeeeeiiiiiiiiiiiooooooooooooooooooooooooooooooooooouuuuuuuuuuuuuuuuuuuuuuuyyyyyyyyyyyddd'));", new="    'àÀáÁạẠảẢãÃâÂầẦấẤậẬẩẨẫẪăĂằẰắẮặẶẳẲẵẴAèÈéÉẹẸẻẺẽẼêÊềỀếẾệỆểỂễỄEìÌíÍịỊỉỈĩĨIòÒóÓọỌỏỎõÕôÔồỒốỐộỘổỔỗỖơƠờỜớỚợỢởỞỡỠOùÙúÚụỤủỦũŨưƯừỪứỨựỰửỬữỮUỳỲýÝỵỴỷỶỹỸYđĐD'));", expect='U1 '),
  dict(suite='search', id='A·U3', mig='20260930170000_community_search_unaccent', how='(A) không dấu: không gập chuỗi tìm', old="  v_q   text := public.community_fold(btrim(coalesce(p_q, '')));", new="  v_q   text := lower(btrim(coalesce(p_q, '')));", expect='U3 '),
  dict(suite='search', id='A·U6', mig='20260930170000_community_search_unaccent', how='(A) không dấu: hàm gập mở cho anon', old='REVOKE EXECUTE ON FUNCTION public.community_fold(text) FROM PUBLIC, anon, authenticated;', new='GRANT EXECUTE ON FUNCTION public.community_fold(text) TO anon;', expect='U6 '),
  dict(suite='challenge_history', id='A·H1', mig='20260930180000_community_challenge_history', how='(A) lịch sử: gồm cả chưa nhận', old='  WHERE m.user_id = auth.uid() AND m.claimed_at IS NOT NULL', new='  WHERE m.user_id = auth.uid()', expect='H1 '),
  dict(suite='challenge_history', id='A·H2', mig='20260930180000_community_challenge_history', how='(A) lịch sử: DEFINER và bỏ lọc mình', old="SECURITY INVOKER\nSET search_path = public\nAS $$\n  SELECT c.id, c.title, c.description, c.target, c.starts_on, c.ends_on,\n         coalesce(t.amount, 0)::integer, m.claimed_at\n  FROM public.community_challenge_members m\n  JOIN public.community_challenges c ON c.id = m.challenge_id\n  LEFT JOIN public.mascot_transactions t ON t.user_id = m.user_id AND t.ref_key = 'cc:' || c.id::text\n  WHERE m.user_id = auth.uid() AND m.claimed_at IS NOT NULL", new="SECURITY DEFINER\nSET search_path = public\nAS $$\n  SELECT c.id, c.title, c.description, c.target, c.starts_on, c.ends_on,\n         coalesce(t.amount, 0)::integer, m.claimed_at\n  FROM public.community_challenge_members m\n  JOIN public.community_challenges c ON c.id = m.challenge_id\n  LEFT JOIN public.mascot_transactions t ON t.user_id = m.user_id AND t.ref_key = 'cc:' || c.id::text\n  WHERE m.claimed_at IS NOT NULL", expect='H2 '),
  dict(suite='challenge_history', id='A·H3', mig='20260930180000_community_challenge_history', how='(A) lịch sử: thưởng hiện tại thay sổ', old='         coalesce(t.amount, 0)::integer, m.claimed_at', new='         c.reward_coins, m.claimed_at', expect='H3 '),
  dict(suite='challenge_history', id='A·H4', mig='20260930180000_community_challenge_history', how='(A) lịch sử: bỏ ghép sổ = rơi dòng 0 xu', old="  LEFT JOIN public.mascot_transactions t ON t.user_id = m.user_id AND t.ref_key = 'cc:' || c.id::text", new="  JOIN public.mascot_transactions t ON t.user_id = m.user_id AND t.ref_key = 'cc:' || c.id::text", expect='H4 '),
  dict(suite='challenge_history', id='A·H5', mig='20260930180000_community_challenge_history', how='(A) lịch sử: cũ nhất đứng đầu', old='  ORDER BY m.claimed_at DESC', new='  ORDER BY m.claimed_at ASC', expect='H5 '),
  dict(suite='challenge_history', id='A·H9', mig='20260930180000_community_challenge_history', how='(A) lịch sử: anon gọi được', old='REVOKE EXECUTE ON FUNCTION public.community_challenge_history() FROM PUBLIC, anon;', new='GRANT EXECUTE ON FUNCTION public.community_challenge_history() TO anon;', expect='H9 '),
]

# ── #79: phủ các nhãn của bộ Tìm người chưa từng bị phá thử ──
CASES += [
  dict(suite='search', id='S1', mig='20260930170000_community_search_unaccent', how='(A) tìm: một ký tự cũng hỏi', old='  IF char_length(v_q) < 2 THEN', new='  IF char_length(v_q) < 1 THEN', expect='S1 '),
  dict(suite='search', id='S3', mig='20260930170000_community_search_unaccent', how="(A) tìm: không bỏ '@' đầu", old="  v_q := left(ltrim(v_q, '@'), 40);", new='  v_q := left(v_q, 40);', expect='S3 '),
  dict(suite='search', id='S5', mig='20260930170000_community_search_unaccent', how="(A) tìm: không thoát '%'", old="  v_pat := replace(replace(replace(v_q, '\\', '\\\\'), '%', '\\%'), '_', '\\_');", new="  v_pat := replace(replace(v_q, '\\', '\\\\'), '_', '\\_');", expect='S5 '),
  dict(suite='search', id='S6', mig='20260930170000_community_search_unaccent', how='(A) tìm: bỏ "đúng handle đứng đầu"', old='  ORDER BY (p.handle = v_q) DESC, p.is_official DESC, p.handle', new='  ORDER BY p.is_official DESC, p.handle', expect='S6 '),
  dict(suite='search', id='S7', mig='20260930170000_community_search_unaccent', how='(A) tìm: cờ đang-theo-dõi luôn true', old='         EXISTS (SELECT 1 FROM public.community_follows f WHERE f.follower_id = v_uid AND f.followee_id = p.user_id)', new='         true', expect='S7 '),
  dict(suite='search', id='S9', mig='20260930170000_community_search_unaccent', how='(A) tìm: loại tài khoản chính thức', old='  WHERE p.user_id <> v_uid\n    AND NOT public.community_blocked_between(v_uid, p.user_id)\n    AND (', new='  WHERE p.user_id <> v_uid\n    AND NOT public.community_blocked_between(v_uid, p.user_id)\n    AND NOT p.is_official\n    AND (', expect='S9 '),
  dict(suite='search', id='S2b', mig='20260930170000_community_search_unaccent', how='(A) tìm: loại MỌI ai dính một dòng chặn (không chỉ với mình)', old='    AND NOT public.community_blocked_between(v_uid, p.user_id)\n    AND (', new='    AND NOT EXISTS (SELECT 1 FROM public.community_blocks b WHERE b.blocked_id = p.user_id OR b.blocker_id = p.user_id)\n    AND (', expect='S2b '),
  dict(suite='search', id='U2', mig='20260930170000_community_search_unaccent', how="(A) bỏ dấu: 'Đ' hoa không được gập (đổi thành 'Ð' trông giống)", old="    'àÀáÁạẠảẢãÃâÂầẦấẤậẬẩẨẫẪăĂằẰắẮặẶẳẲẵẴAèÈéÉẹẸẻẺẽẼêÊềỀếẾệỆểỂễỄEìÌíÍịỊỉỈĩĨIòÒóÓọỌỏỎõÕôÔồỒốỐộỘổỔỗỖơƠờỜớỚợỢởỞỡỠOùÙúÚụỤủỦũŨưƯừỪứỨựỰửỬữỮUỳỲýÝỵỴỷỶỹỸYđĐD',", new="    'àÀáÁạẠảẢãÃâÂầẦấẤậẬẩẨẫẪăĂằẰắẮặẶẳẲẵẴAèÈéÉẹẸẻẺẽẼêÊềỀếẾệỆểỂễỄEìÌíÍịỊỉỈĩĨIòÒóÓọỌỏỎõÕôÔồỒốỐộỘổỔỗỖơƠờỜớỚợỢởỞỡỠOùÙúÚụỤủỦũŨưƯừỪứỨựỰửỬữỮUỳỲýÝỵỴỷỶỹỸYđÐD',", expect='U2 '),
  dict(suite='search', id='U4', mig='20260930170000_community_search_unaccent', how="(A) bỏ dấu: 'Á' hoa không được gập", old="    'àÀáÁạẠảẢãÃâÂầẦấẤậẬẩẨẫẪăĂằẰắẮặẶẳẲẵẴAèÈéÉẹẸẻẺẽẼêÊềỀếẾệỆểỂễỄEìÌíÍịỊỉỈĩĨIòÒóÓọỌỏỎõÕôÔồỒốỐộỘổỔỗỖơƠờỜớỚợỢởỞỡỠOùÙúÚụỤủỦũŨưƯừỪứỨựỰửỬữỮUỳỲýÝỵỴỷỶỹỸYđĐD',", new="    'àÀáǺạẠảẢãÃâÂầẦấẤậẬẩẨẫẪăĂằẰắẮặẶẳẲẵẴAèÈéÉẹẸẻẺẽẼêÊềỀếẾệỆểỂễỄEìÌíÍịỊỉỈĩĨIòÒóÓọỌỏỎõÕôÔồỒốỐộỘổỔỗỖơƠờỜớỚợỢởỞỡỠOùÙúÚụỤủỦũŨưƯừỪứỨựỰửỬữỮUỳỲýÝỵỴỷỶỹỸYđĐD',", expect='U4 '),
  dict(suite='search', id='U5', mig='20260930170000_community_search_unaccent', how="(A) bỏ dấu: 'Ứ' hoa không được gập", old="    'àÀáÁạẠảẢãÃâÂầẦấẤậẬẩẨẫẪăĂằẰắẮặẶẳẲẵẴAèÈéÉẹẸẻẺẽẼêÊềỀếẾệỆểỂễỄEìÌíÍịỊỉỈĩĨIòÒóÓọỌỏỎõÕôÔồỒốỐộỘổỔỗỖơƠờỜớỚợỢởỞỡỠOùÙúÚụỤủỦũŨưƯừỪứỨựỰửỬữỮUỳỲýÝỵỴỷỶỹỸYđĐD',", new="    'àÀáÁạẠảẢãÃâÂầẦấẤậẬẩẨẫẪăĂằẰắẮặẶẳẲẵẴAèÈéÉẹẸẻẺẽẼêÊềỀếẾệỆểỂễỄEìÌíÍịỊỉỈĩĨIòÒóÓọỌỏỎõÕôÔồỒốỐộỘổỔỗỖơƠờỜớỚợỢởỞỡỠOùÙúÚụỤủỦũŨưƯừỪứǗựỰửỬữỮUỳỲýÝỵỴỷỶỹỸYđĐD',", expect='U5 '),
  dict(suite='search', id='G2', mig='20260930160000_community_search', how='(A) gợi ý: đếm bài gấp đôi', old='(SELECT count(*)::integer FROM public.community_posts x', new='(SELECT (count(*) * 2)::integer FROM public.community_posts x', expect='G2 '),
  dict(suite='search', id='G3', mig='20260930160000_community_search', how='(A) gợi ý: loại người được BẤT KỲ AI theo dõi', old='      AND NOT EXISTS (SELECT 1 FROM public.community_follows f WHERE f.follower_id = v_uid AND f.followee_id = p.user_id)', new='      AND NOT EXISTS (SELECT 1 FROM public.community_follows f WHERE f.followee_id = p.user_id)', expect='G3 '),
  dict(suite='search', id='G4', mig='20260930160000_community_search', how='(A) gợi ý: anon gọi được', old='REVOKE EXECUTE ON FUNCTION public.community_follow_suggestions() FROM PUBLIC, anon;', new='GRANT EXECUTE ON FUNCTION public.community_follow_suggestions() TO anon;', expect='G4 '),
]

# ── #79: phủ các nhãn của bộ Lịch sử thử thách và Thử thách ──
CASES += [
  dict(suite='challenge_history', id='H1b', mig='20260930180000_community_challenge_history', how='(A) lịch sử: "đã hết hạn" thay "đã nhận"', old='  WHERE m.user_id = auth.uid() AND m.claimed_at IS NOT NULL', new='  WHERE m.user_id = auth.uid() AND (m.claimed_at IS NOT NULL OR c.ends_on < current_date)', expect='H1b '),
  dict(suite='challenge_history', id='H6', mig='20260930120000_community_challenges', how='(A) tổng quan: cửa sổ 7 → 45 ngày (lịch sử thành thừa)', old='  WHERE c.ends_on >= current_date - 7 AND', new='  WHERE c.ends_on >= current_date - 45 AND', expect='H6 '),
  dict(suite='challenge_history', id='H8', mig='20260930180000_community_challenge_history', how='(A) lịch sử: chỉ thử thách đã hết hạn (nhận sớm thì mất)', old='  WHERE m.user_id = auth.uid() AND m.claimed_at IS NOT NULL', new='  WHERE m.user_id = auth.uid() AND m.claimed_at IS NOT NULL AND c.ends_on < current_date', expect='H8 '),
  dict(suite='challenges', id='C5', mig='20260930120000_community_challenges', how='(A) tổng quan: cờ "đã tham gia" luôn false', old='    me.user_id IS NOT NULL,\n    CASE', new='    false,\n    CASE', expect='C5 '),
  dict(suite='challenges', id='C7', mig='20260930120000_community_challenges', how='(A) tổng quan: đếm người tham gia của MỌI thử thách', old='SELECT count(*)::integer FROM public.community_challenge_members m WHERE m.challenge_id = c.id', new='SELECT count(*)::integer FROM public.community_challenge_members m', expect='C7 '),
  dict(suite='challenges', id='C11', mig='20260930120000_community_challenges', how='(A) tổng quan: kẹp tiến độ ở đích', old='CASE WHEN me.user_id IS NOT NULL THEN public.community_challenge_progress(c.id, v_uid, p_offset_min) ELSE 0 END', new='CASE WHEN me.user_id IS NOT NULL THEN least(c.target, public.community_challenge_progress(c.id, v_uid, p_offset_min)) ELSE 0 END', expect='C11 '),
  dict(suite='challenges', id='C12', mig='20260930120000_community_challenges', how='(A) nhận thưởng: trả 0 thay số xu', old='  RETURN c.reward_coins;', new='  RETURN 0;', expect='C12 '),
  dict(suite='challenges', id='C15', mig='20260930120000_community_challenges', how='(A) nhận thưởng: đánh dấu đã nhận mà không ghi sổ', old='  IF c.reward_coins > 0 THEN', new='  IF c.reward_coins > 100000 THEN', expect='C15 '),
  dict(suite='challenges', id='C16', mig='20260930120000_community_challenges', how='(A) nhận thưởng: ghi sổ gấp đôi', old='VALUES (v_uid, c.reward_coins, ', new='VALUES (v_uid, c.reward_coins * 2, ', expect='C16 '),
  dict(suite='challenges', id='C17', mig='20260930120000_community_challenges', how='(A) tiến độ: lệch 0 bị coi là "không gửi" → mặc định UTC+7', old='coalesce(p_offset_min, 0)', new='coalesce(nullif(p_offset_min, 0), 420)', expect='C17 ', nth='all'),
]

# ── #79: phủ các nhãn của bộ Thông báo và Quyền riêng tư ──
CASES += [
  dict(suite='notifications', id='N2', mig='20260930140000_community_notifications', how='(A) thông báo: trigger thích chạy khi SỬA thay khi THÊM', old='  AFTER INSERT ON public.community_likes\n', new='  AFTER UPDATE ON public.community_likes\n', expect='N2 '),
  dict(suite='notifications', id='N5', mig='20260930140000_community_notifications', how='(A) thông báo: tự báo cho mình — bỏ CẢ chốt trong trigger LẪN CHECK của bảng', old='  IF v_to IS NULL OR v_to = v_actor', new='  IF v_to IS NULL', expect='N5 ', extra=(('  CHECK (user_id <> actor_id),\n', ''),)),
  dict(suite='notifications', id='N6·fk', mig='20260930140000_community_notifications', how='(A) thông báo: bỏ chốt "có hồ sơ" — khoá ngoại về hồ sơ vẫn chặn (lớp thứ hai)', old='     OR NOT EXISTS (SELECT 1 FROM public.community_profiles WHERE user_id = v_actor)\n', new='', expect='community_notifications_actor_id_fkey'),
  dict(suite='notifications', id='N6', mig='20260930140000_community_notifications', how='(A) thông báo: bỏ chốt "có hồ sơ" VÀ khoá ngoại về hồ sơ', old='     OR NOT EXISTS (SELECT 1 FROM public.community_profiles WHERE user_id = v_actor)\n', new='', expect='N6 ', extra=(('  actor_id   uuid NOT NULL REFERENCES public.community_profiles(user_id) ON DELETE CASCADE,', '  actor_id   uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,'),)),
  dict(suite='notifications', id='N7', mig='20260930140000_community_notifications', how='(A) thông báo: gộp mọi bình luận của một người trên một bài thành một dòng', old="    INSERT INTO public.community_notifications (user_id, actor_id, kind, post_id, comment_id)\n    VALUES (v_to, v_actor, 'comment', NEW.post_id, NEW.id);", new="    INSERT INTO public.community_notifications (user_id, actor_id, kind, post_id, comment_id)\n    SELECT v_to, v_actor, 'comment', NEW.post_id, NEW.id\n    WHERE NOT EXISTS (SELECT 1 FROM public.community_notifications x WHERE x.kind = 'comment' AND x.post_id = NEW.post_id AND x.actor_id = v_actor);", expect='N7 '),
  dict(suite='notifications', id='N12', mig='20260930140000_community_notifications', how='(A) thông báo: RLS đòi bài còn đó — rơi mất thông báo theo dõi', old='  USING (auth.uid() = user_id AND NOT public.community_blocked_between(user_id, actor_id));', new='  USING (auth.uid() = user_id AND NOT public.community_blocked_between(user_id, actor_id)\n         AND EXISTS (SELECT 1 FROM public.community_posts p WHERE p.id = post_id));', expect='N12 '),
  dict(suite='notifications', id='N15', mig='20260930140000_community_notifications', how='(A) thông báo: đếm trước, UPDATE mất lọc người (con số trả về vẫn đúng)', old='  UPDATE public.community_notifications SET read_at = now()\n  WHERE user_id = v_uid AND read_at IS NULL;\n  GET DIAGNOSTICS v_n = ROW_COUNT;', new='  SELECT count(*)::integer INTO v_n FROM public.community_notifications WHERE user_id = v_uid AND read_at IS NULL;\n  UPDATE public.community_notifications SET read_at = now()\n  WHERE read_at IS NULL;', expect='N15 '),
  dict(suite='notifications', id='N17', mig='20260927120000_community_foundation', how='(A) thông báo: chặn thì XOÁ thông báo giữa hai người (thay vì RLS giấu)', old='     OR (follower_id = NEW.blocked_id AND followee_id = NEW.blocker_id);\n  RETURN NEW;', new='     OR (follower_id = NEW.blocked_id AND followee_id = NEW.blocker_id);\n  DELETE FROM public.community_notifications\n  WHERE (user_id = NEW.blocker_id AND actor_id = NEW.blocked_id)\n     OR (user_id = NEW.blocked_id AND actor_id = NEW.blocker_id);\n  RETURN NEW;', expect='N17 '),
  dict(suite='notifications', id='N21·u', mig='20260930140000_community_notifications', how='(A) thông báo: bỏ khoá ngoại người nhận — hộp vẫn sạch nhờ cascade của bài/lượt theo dõi', old='  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,', new='  user_id    uuid NOT NULL,', expect='N21 ', green_ok=True),
  dict(suite='privacy', id='V1', mig='20260930130000_community_privacy', how='(A) cài đặt: mặc định "followers"', old="  default_visibility text NOT NULL DEFAULT 'public' CHECK", new="  default_visibility text NOT NULL DEFAULT 'followers' CHECK", expect='V1 '),
  dict(suite='privacy', id='V8', mig='20260927120000_community_foundation', how='(A) chặn: không có đường bỏ chặn (policy DELETE đóng)', old='ON public.community_blocks FOR DELETE TO authenticated USING (auth.uid() = blocker_id);', new='ON public.community_blocks FOR DELETE TO authenticated USING (false);', expect='V8 '),
  dict(suite='privacy', id='V10', mig='20260927120000_community_foundation', how='(A) chặn: bỏ chặn tự theo dõi lại', old='CREATE TRIGGER community_blocks_unfollow\n  AFTER INSERT ON public.community_blocks\n  FOR EACH ROW EXECUTE FUNCTION public.community_blocks_unfollow();', new='CREATE TRIGGER community_blocks_unfollow\n  AFTER INSERT ON public.community_blocks\n  FOR EACH ROW EXECUTE FUNCTION public.community_blocks_unfollow();\nCREATE FUNCTION public.community_blocks_refollow() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $f$\nBEGIN\n  INSERT INTO public.community_follows (follower_id, followee_id) VALUES (OLD.blocker_id, OLD.blocked_id) ON CONFLICT DO NOTHING;\n  RETURN OLD;\nEND $f$;\nCREATE TRIGGER community_blocks_refollow AFTER DELETE ON public.community_blocks\n  FOR EACH ROW EXECUTE FUNCTION public.community_blocks_refollow();', expect='V10 '),
  dict(suite='privacy', id='V11', mig='20260927120000_community_foundation', how='(A) bài: không ai xoá được bài (policy DELETE đóng)', old='ON public.community_posts FOR DELETE TO authenticated USING (auth.uid() = author_id);', new='ON public.community_posts FOR DELETE TO authenticated USING (false);', expect='V11 '),
  dict(suite='privacy', id='V13', mig='20260927120000_community_foundation', how='(A) bài: xoá bài cuối cùng thì dọn luôn hồ sơ', old='ON public.community_posts FOR DELETE TO authenticated USING (auth.uid() = author_id);', new='ON public.community_posts FOR DELETE TO authenticated USING (auth.uid() = author_id);\nCREATE FUNCTION public.community_posts_drop_empty_profile() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $f$\nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM public.community_posts WHERE author_id = OLD.author_id) THEN\n    DELETE FROM public.community_profiles WHERE user_id = OLD.author_id;\n  END IF;\n  RETURN OLD;\nEND $f$;\nCREATE TRIGGER community_posts_drop_empty_profile AFTER DELETE ON public.community_posts\n  FOR EACH ROW EXECUTE FUNCTION public.community_posts_drop_empty_profile();', expect='V13 '),
]
CASES += [
  dict(suite='notifications', id='N10', mig='20260930140000_community_notifications', how='(A) thông báo: trigger theo dõi chạy khi SỬA thay khi THÊM (N10a vẫn xanh: 0 là 0)', old='  AFTER INSERT ON public.community_follows\n', new='  AFTER UPDATE ON public.community_follows\n', expect='N10 '),
]
